### ISSUE TITLE
WIREGUARD_PRIVATE_KEY_SECRETFILE missing

### ISSUE THREAD

**Issue by Mladia** [qdm12/gluetun#1758] opened 2023-07-21 20:27 UTC
https://github.com/qdm12/gluetun/blob/c5cc240a6cf8b97de8bcf199b8ad23a49deb2b48/Dockerfile#L96C19-L96C19

Currently, the possibility of using a secrets file for Wireguard is missing. 
This functionality is present for instance with Openvpn and the OPENVPN_USER_SECRETFILE.

As I understand, one of the things is to add
```WIREGUARD_PRIVATE_KEY_SECRETFILE=/run/secrets/wireguard_private_key \```.
to the Dockerfile

Would this be all?

**Comment by qdm12** [comment] 2023-07-22 09:15
Duplicate of #614

Also see https://github.com/qdm12/gluetun/pull/1348#issuecomment-1646538214 and feel free to subscribe to the issue or pr mentioned to be alerted once it's done. Thanks!

**Closed by qdm12** 2023-07-22 09:15 UTC
