### ISSUE TITLE
Bug: ...

### ISSUE THREAD

**Issue by ehinkle27** [qdm12/gluetun#329] opened 2020-12-30 19:03 UTC
**Host OS** (approximate answer is fine too): Ubuntu 18

**Is this urgent?**: No

**What VPN provider are you using**: PIA

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-12-30T15:54:51Z (commit fb8a615)
```

**What's the problem** 🤔
When turning of DOT and specifying an external DNS server it constantly loops on resolving github

That feature doesn't work

**Share your logs...**

...*careful to remove i.e. token information with PIA port forwarding*

```log

2020-12-30T11:53:46.818-0700    INFO    firewall: setting VPN connection through firewall...
2020-12-30T11:53:46.818-0700    INFO    http server: listening on 0.0.0.0:8000
2020-12-30T11:53:46.819-0700    INFO    dns over tls: using plaintext DNS at address 1.1.1.1
2020-12-30T11:53:46.819-0700    INFO    dns configurator: using DNS address 1.1.1.1 internally
2020-12-30T11:53:46.819-0700    INFO    dns configurator: using DNS address 1.1.1.1 system wide
2020-12-30T11:53:46.824-0700    INFO    openvpn configurator: starting openvpn
2020-12-30T11:53:46.828-0700    INFO    openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
2020-12-30T11:53:46.828-0700    INFO    openvpn: library versions: OpenSSL 1.1.1i  8 Dec 2020, LZO 2.10
2020-12-30T11:53:46.829-0700    INFO    openvpn: CRL: loaded 1 CRLs from file [[INLINE]]
2020-12-30T11:53:46.829-0700    INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]143.244.46.65:1197
2020-12-30T11:53:46.829-0700    INFO    openvpn: UDP link local: (not bound)
2020-12-30T11:53:46.829-0700    INFO    openvpn: UDP link remote: [AF_INET]143.244.46.65:1197
2020-12-30T11:53:47.290-0700    INFO    openvpn: [newjersey405] Peer Connection Initiated with [AF_INET]143.244.46.65:1197
2020-12-30T11:53:48.513-0700    INFO    openvpn: OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
2020-12-30T11:53:48.513-0700    INFO    openvpn: OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
2020-12-30T11:53:48.513-0700    INFO    openvpn: TUN/TAP device tun0 opened
2020-12-30T11:53:48.513-0700    INFO    openvpn: /sbin/ip link set dev tun0 up mtu 1500
2020-12-30T11:53:48.515-0700    INFO    openvpn: /sbin/ip addr add dev tun0 10.5.110.2/24 broadcast 10.5.110.255
2020-12-30T11:53:48.521-0700    WARN    openvpn: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
2020-12-30T11:53:48.521-0700    INFO    openvpn: UID set to nonrootuser
2020-12-30T11:53:48.521-0700    INFO    openvpn: Initialization Sequence Completed
2020-12-30T11:53:48.521-0700    INFO    dns configurator: downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
2020-12-30T11:53:49.371-0700    INFO    dns configurator: downloading root key from https://raw.githubusercontent.com/qdm12/files/master/root.key.updated
2020-12-30T11:53:49.548-0700    INFO    dns configurator: generating Unbound configuration
2020-12-30T11:53:49.549-0700    INFO    dns configurator: 0 hostnames blocked overall
2020-12-30T11:53:49.549-0700    INFO    dns configurator: 0 IP addresses blocked overall
2020-12-30T11:53:49.549-0700    INFO    dns configurator: starting unbound
2020-12-30T11:53:49.550-0700    INFO    dns configurator: using DNS address 127.0.0.1 internally
2020-12-30T11:53:49.550-0700    INFO    dns configurator: using DNS address 127.0.0.1 system wide
2020-12-30T11:53:49.617-0700    INFO    unbound: start of service (unbound 1.10.1).
2020-12-30T11:53:49.852-0700    WARN    dns configurator: could not resolve github.com (try 1 of 6): lookup github.com on 1.1.1.1:53: server misbehaving
2020-12-30T11:53:49.955-0700    WARN    dns configurator: could not resolve github.com (try 2 of 6): lookup github.com on 1.1.1.1:53: server misbehaving
2020-12-30T11:53:50.257-0700    WARN    dns configurator: could not resolve github.com (try 3 of 6): lookup github.com on 1.1.1.1:53: server misbehaving
2020-12-30T11:53:50.759-0700    WARN    dns configurator: could not resolve github.com (try 4 of 6): lookup github.com on 1.1.1.1:53: server misbehaving
2020-12-30T11:53:50.811-0700    INFO    http server: 404 GET  wrote 41B to 10.29.5.22:56333 in 21.527µs
2020-12-30T11:53:50.920-0700    INFO    http server: 404 GET /favicon.ico wrote 41B to 10.29.5.22:56333 in 12.579µs
2020-12-30T11:53:51.761-0700    WARN    dns configurator: could not resolve github.com (try 5 of 6): lookup github.com on 1.1.1.1:53: server misbehaving
2020-12-30T11:53:53.763-0700    WARN    dns configurator: could not resolve github.com (try 6 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:53:53.763-0700    INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
2020-12-30T11:53:53.763-0700    INFO    dns configurator: using DNS address 1.1.1.1 internally
2020-12-30T11:53:53.763-0700    INFO    dns configurator: using DNS address 1.1.1.1 system wide
2020-12-30T11:53:53.763-0700    WARN    dns over tls: Unbound does not seem to be working after 6 tries
2020-12-30T11:53:53.764-0700    INFO    dns over tls: attempting restart in 10 seconds
2020-12-30T11:53:53.764-0700    INFO    VPN routing IP address: 143.244.46.65
2020-12-30T11:54:03.764-0700    INFO    dns configurator: starting unbound
2020-12-30T11:54:03.765-0700    INFO    dns configurator: using DNS address 127.0.0.1 internally
2020-12-30T11:54:03.765-0700    INFO    dns configurator: using DNS address 127.0.0.1 system wide
2020-12-30T11:54:03.831-0700    INFO    unbound: start of service (unbound 1.10.1).
.0.1:53: server misbehaving
2020-12-30T11:59:35.093-0700    INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
2020-12-30T11:59:35.093-0700    INFO    dns configurator: using DNS address 1.1.1.1 internally
2020-12-30T11:59:35.093-0700    INFO    dns configurator: using DNS address 1.1.1.1 system wide
2020-12-30T11:59:35.129-0700    WARN    dns over tls: Unbound does not seem to be working after 6 tries
2020-12-30T11:59:35.129-0700    INFO    dns over tls: attempting restart in 10 seconds
2020-12-30T11:59:45.129-0700    INFO    dns configurator: starting unbound
2020-12-30T11:59:45.131-0700    INFO    dns configurator: using DNS address 127.0.0.1 internally
2020-12-30T11:59:45.131-0700    INFO    dns configurator: using DNS address 127.0.0.1 system wide
2020-12-30T11:59:45.206-0700    INFO    unbound: start of service (unbound 1.10.1).
2020-12-30T11:59:46.183-0700    WARN    dns configurator: could not resolve github.com (try 1 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:46.284-0700    WARN    dns configurator: could not resolve github.com (try 2 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:46.595-0700    WARN    dns configurator: could not resolve github.com (try 3 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:47.098-0700    WARN    dns configurator: could not resolve github.com (try 4 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:48.099-0700    WARN    dns configurator: could not resolve github.com (try 5 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:50.101-0700    WARN    dns configurator: could not resolve github.com (try 6 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T11:59:50.101-0700    INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
2020-12-30T11:59:50.102-0700    INFO    dns configurator: using DNS address 1.1.1.1 internally
2020-12-30T11:59:50.102-0700    INFO    dns configurator: using DNS address 1.1.1.1 system wide
2020-12-30T11:59:50.189-0700    WARN    dns over tls: Unbound does not seem to be working after 6 tries
2020-12-30T11:59:50.190-0700    INFO    dns over tls: attempting restart in 10 seconds
2020-12-30T12:00:00.190-0700    INFO    dns configurator: starting unbound
2020-12-30T12:00:00.191-0700    INFO    dns configurator: using DNS address 127.0.0.1 internally
2020-12-30T12:00:00.191-0700    INFO    dns configurator: using DNS address 127.0.0.1 system wide
2020-12-30T12:00:00.267-0700    INFO    unbound: start of service (unbound 1.10.1).
2020-12-30T12:00:03.157-0700    WARN    dns configurator: could not resolve github.com (try 1 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:03.259-0700    WARN    dns configurator: could not resolve github.com (try 2 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:03.562-0700    WARN    dns configurator: could not resolve github.com (try 3 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:04.064-0700    WARN    dns configurator: could not resolve github.com (try 4 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:05.067-0700    WARN    dns configurator: could not resolve github.com (try 5 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:07.070-0700    WARN    dns configurator: could not resolve github.com (try 6 of 6): lookup github.com on 127.0.0.1:53: server misbehaving
2020-12-30T12:00:07.071-0700    INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
2020-12-30T12:00:07.071-0700    INFO    dns configurator: using DNS address 1.1.1.1 internally
2020-12-30T12:00:07.071-0700    INFO    dns configurator: using DNS address 1.1.1.1 system wide
2020-12-30T12:00:07.368-0700    WARN    dns over tls: Unbound does not seem to be working after 6 tries
2020-12-30T12:00:07.368-0700    INFO    dns over tls: attempting restart in 10 seconds
2020-12-30T12:00:17.368-0700    INFO    dns configurator: starting unbound
2020-12-30T12:00:17.370-0700    INFO    dns configurator: using DNS address 127.0.0.1 internally
2020-12-30T12:00:17.370-0700    INFO    dns configurator: using DNS address 127.0.0.1 system wide
2020-12-30T12:00:17.471-0700    INFO    unbound: start of service (unbound 1.10.1).

```

**Comment by ehinkle27** [comment] 2020-12-30 19:07
Here is my docker compose service:
  gluetun-vpn:
#    image: itsdaspecialk/pia-openvpn:latest
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - net_admin
    dns:
      - 209.222.18.222
      - 209.222.18.218
    ports:
      - 9091:9091/tcp
      - 8080:8080/tcp
      - 8000:8000/tcp
      - 8388:8388/tcp
      - 8888:8888/tcp
      - 8388:8388/udp
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/gluetun:/gluetun
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      UMASK: 002
      TZ: $TZ
      REGION: "US EAST"
      VPNSP: "private internet access"
      OPENVPN_USER: "username"
      OPENVPN_PASSWORD: "XXXX"
      DOT: "off"
      DNS_PLAINTEXT_ADDRESS: "1.1.1.1"
#      FIREWALL_OUTBOUND_SUBNETS: "192.168.90.0/24"
      FIREWALL_INPUT_PORTS: "8000,8080,8888,8388"

**Comment by qdm12** [comment] 2020-12-30 20:58
Hello there! Your issue is very likely a duplicate of #326 please have a look there for the solution. Thanks for taking the time to create the issue still 👍

**Closed by qdm12** 2020-12-30 20:58 UTC

**Comment by qdm12** [comment] 2020-12-30 21:00
A few notes on your docker-compose.yml:

- The addresses specified by `dns:` will be overridden by `DNS_PLAINTEXT_ADDRESS` (if that's an issue for you, please create another issue)
- `UMASK` is not used
- `USER_ID` should be `PUID` and `GROUP_ID` should be `PGID`

Also please wait for the [build of qmcgaw/gluetun](https://github.com/qdm12/gluetun/runs/1627765855) to finish before pulling it 😉
