### ISSUE TITLE
Bug:  Failed to load updated MTU of device

### ISSUE THREAD

**Issue by millionsofplayers** [qdm12/gluetun#1794] opened 2023-08-11 19:16 UTC
### Is this urgent?

None

### Host OS

Debian (openmediavault)

### CPU arch

x86_64

### VPN service provider

AirVPN

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2023-08-04T11:14:39.159Z (commit 082a38b)

### What's the problem 🤔

Can't use gluetun with a AirVPN + Wireguard combo.

### Share your logs

```plain text
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2023-08-04T11:14:39.159Z (commit 082a38b)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-08-11T19:00:35Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.2 and family v4
2023-08-11T19:00:35Z INFO [routing] local ethernet link found: eth0
2023-08-11T19:00:35Z INFO [routing] local ipnet found: 172.22.0.0/16
2023-08-11T19:00:35Z INFO [routing] local ipnet found: fe80::/64
2023-08-11T19:00:36Z INFO [firewall] enabling...
2023-08-11T19:00:36Z INFO [firewall] enabled successfully
2023-08-11T19:00:39Z INFO [storage] merging by most recent 17692 hardcoded servers and 17692 servers read from /gluetun/servers.json
2023-08-11T19:00:40Z INFO Alpine version: 3.18.2
2023-08-11T19:00:42Z INFO OpenVPN 2.5 version: 2.5.8
2023-08-11T19:00:42Z INFO OpenVPN 2.6 version: 2.6.5
2023-08-11T19:00:42Z INFO Unbound version: 1.17.1
2023-08-11T19:00:42Z INFO IPtables version: v1.8.9
2023-08-11T19:00:42Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: airvpn
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Countries: united states
|   |       └── Wireguard selection settings:
|   └── Wireguard settings:
|       ├── Private key: YHz...Gw=
|       ├── Pre-shared key: 02u...hc=
|       ├── Interface addresses:
|       |   ├── 10.185.196.145/32
|       |   └── fd7d:76ee:e68f:a993:8271:20be:ba5f:2d2b/128
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── VPN input ports:
|       └── 9389
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   └── Process GID: 1000
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2023-08-11T19:00:42Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.2 and family v4
2023-08-11T19:00:42Z INFO [routing] adding route for 0.0.0.0/0
2023-08-11T19:00:42Z INFO [firewall] setting allowed subnets...
2023-08-11T19:00:42Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.2 and family v4
2023-08-11T19:00:42Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2023-08-11T19:00:42Z INFO [dns over tls] using plaintext DNS at address 1.1.1.1
2023-08-11T19:00:42Z INFO [http server] http server listening on [::]:8000
2023-08-11T19:00:42Z INFO [healthcheck] listening on 127.0.0.1:9999
2023-08-11T19:00:42Z INFO [firewall] allowing VPN connection...
2023-08-11T19:00:42Z INFO [wireguard] Using userspace implementation since Kernel support does not exist
2023-08-11T19:00:43Z INFO [wireguard] Connecting to [2a0d:5600:2:5:41e0:91df:ee8b:fa]:1637
2023-08-11T19:00:43Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-08-11T19:00:43Z INFO [firewall] setting allowed input port 9389 through interface tun0...
2023-08-11T19:00:43Z ERROR [wireguard] peer(PyLC…g+hk) - Failed to send handshake initiation: write udp [::]:43335: sendmmsg: network is unreachable
2023-08-11T19:00:43Z INFO [dns over tls] downloading DNS over TLS cryptographic files
2023-08-11T19:00:48Z ERROR [wireguard] peer(PyLC…g+hk) - Failed to send handshake initiation: write udp [::]:43335: sendmmsg: network is unreachable
2023-08-11T19:00:50Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-08-11T19:00:50Z INFO [vpn] stopping
2023-08-11T19:00:50Z INFO [firewall] removing allowed port 9389...
2023-08-11T19:00:50Z ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
2023-08-11T19:00:50Z ERROR [wireguard] Failed to load updated MTU of device: failed to get MTU of TUN device: no such device
2023-08-11T19:00:50Z INFO [vpn] starting
2023-08-11T19:00:50Z INFO [firewall] allowing VPN connection...
2023-08-11T19:00:51Z INFO [wireguard] Using available kernelspace implementation
2023-08-11T19:00:51Z INFO [wireguard] Connecting to 199.249.230.46:1637
2023-08-11T19:00:51Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-08-11T19:00:51Z INFO [firewall] setting allowed input port 9389 through interface tun0...
2023-08-11T19:00:51Z INFO [healthcheck] healthy!
2023-08-11T19:00:53Z WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.185.196.145:46234->1.1.1.1:53: i/o timeout
2023-08-11T19:00:53Z INFO [dns over tls] attempting restart in 10s
2023-08-11T19:01:03Z INFO [dns over tls] downloading DNS over TLS cryptographic files
2023-08-11T19:01:04Z INFO [dns over tls] downloading hostnames and IP block lists
2023-08-11T19:01:13Z WARN Caught OS signal terminated, shutting down
2023-08-11T19:01:13Z INFO updater ticker: terminated ✔️
2023-08-11T19:01:13Z INFO dns ticker: terminated ✔️
2023-08-11T19:01:13Z INFO http server: terminated ✔️
2023-08-11T19:01:13Z INFO control: terminated ✔️
2023-08-11T19:01:13Z INFO updater: terminated ✔️
2023-08-11T19:01:13Z INFO public IP: terminated ✔️
2023-08-11T19:01:13Z INFO tickers: terminated ✔️
2023-08-11T19:01:13Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: operation was canceled
2023-08-11T19:01:13Z INFO HTTP health server: terminated ✔️
2023-08-11T19:01:13Z INFO [firewall] removing allowed port 9389...
2023-08-11T19:01:14Z INFO vpn: terminated ✔️
2023-08-11T19:01:14Z INFO port forwarding: terminated ✔️
2023-08-11T19:01:14Z INFO shadowsocks proxy: terminated ✔️
2023-08-11T19:01:14Z INFO http proxy: terminated ✔️
2023-08-11T19:01:14Z INFO unbound: terminated ✔️
2023-08-11T19:01:14Z WARN other: group shutdown timed out: 1 out of 4 goroutines: public IP: goroutine shutdown timed out: after 400ms ⚠️
2023-08-11T19:01:14Z INFO [routing] routing cleanup...
2023-08-11T19:01:14Z INFO [routing] default route found: interface eth0, gateway 172.22.0.1, assigned IP 172.22.0.2 and family v4
2023-08-11T19:01:14Z INFO [routing] deleting route for 0.0.0.0/0
2023-08-11T19:01:14Z WARN Shutdown not completed gracefully: ordered shutdown timed out: other: group shutdown timed out: 1 out of 4 goroutines: public IP: goroutine shutdown timed out: after 400ms
```

### Share your configuration

```yml
(used docker-autocompose for this, i don't remember where my gluetun compose file is)

version: "3.6"
services:
  gluetun:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "gluetun"
    entrypoint:
      - "/gluetun-entrypoint"
    environment:
      - "OPENVPN_CLIENTKEY_SECRETFILE=/run/secrets/openvpn_clientkey"
      - "DNS_UPDATE_PERIOD=24h"
      - "OPENVPN_ENCRYPTED_KEY="
      - "OPENVPN_FLAGS="
      - "HEALTH_SUCCESS_WAIT_DURATION=5s"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DNS_ADDRESS=127.0.0.1"
      - "UPDATER_VPN_SERVICE_PROVIDERS="
      - "HTTPPROXY_USER_SECRETFILE=/run/secrets/httpproxy_user"
      - "PUBLICIP_FILE=/tmp/gluetun/ip"
      - "VPN_ENDPOINT_PORT="
      - "HEALTH_VPN_DURATION_ADDITION=5s"
      - "HTTP_CONTROL_SERVER_ADDRESS=:8000"
      - "OPENVPN_VERBOSITY=1"
      - "VPN_ENDPOINT_IP="
      - "DNS_KEEP_NAMESERVER=off"
      - "OPENVPN_CIPHERS="
      - "HTTPPROXY="
      - "PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port"
      - "VERSION_INFORMATION=on"
      - "SHADOWSOCKS=off"
      - "PUID="
      - "PREMIUM_ONLY="
      - "SHADOWSOCKS_PASSWORD_SECRETFILE=/run/secrets/shadowsocks_password"
      - "SERVER_HOSTNAMES="
      - "SERVER_NAMES="
      - "OPENVPN_PASSWORD_SECRETFILE=/run/secrets/openvpn_password"
      - "FIREWALL_VPN_INPUT_PORTS=9389"
      - "OPENVPN_VERSION=2.5"
      - "OPENVPN_USER="
      - "OPENVPN_CERT=---"
      - "OPENVPN_KEY=---"
      - "HTTPPROXY_PASSWORD="
      - "PPROF_ENABLED=no"
      - "VPN_TYPE=wireguard"
      - "WIREGUARD_PRIVATE_KEY=---"
      - "HEALTH_TARGET_ADDRESS=cloudflare.com:443"
      - "DOT_VALIDATION_LOGLEVEL=0"
      - "WIREGUARD_MTU="
      - "OPENVPN_CUSTOM_CONFIG="
      - "SHADOWSOCKS_PASSWORD="
      - "DOT_IPV6=off"
      - "BLOCK_ADS=off"
      - "WIREGUARD_PUBLIC_KEY="
      - "TZ="
      - "PPROF_MUTEX_PROFILE_RATE=0"
      - "WIREGUARD_IMPLEMENTATION=auto"
      - "DOT_VERBOSITY=1"
      - "OPENVPN_KEY_PASSPHRASE="
      - "DOT_VERBOSITY_DETAILS=0"
      - "UPDATER_MIN_RATIO=0.8"
      - "DOT_PRIVATE_ADDRESS=---"
      - "PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET="
      - "BLOCK_SURVEILLANCE=off"
      - "OPENVPN_PROCESS_USER="
      - "DOT=on"
      - "VPN_SERVICE_PROVIDER=airvpn"
      - "OPENVPN_IPV6=on"
      - "SERVER_CITIES="
      - "SERVER_NUMBER="
      - "SERVER_COUNTRIES=United States"
      - "OPENVPN_USER_SECRETFILE=/run/secrets/openvpn_user"
      - "SERVER_REGIONS="
      - "PGID="
      - "PPROF_HTTP_SERVER_ADDRESS=:6060"
      - "HEALTH_VPN_DURATION_INITIAL=6s"
      - "MULTIHOP_ONLY="
      - "VPN_PORT_FORWARDING_STATUS_FILE=/tmp/gluetun/forwarded_port"
      - "SHADOWSOCKS_LOG=off"
      - "HTTPPROXY_USER="
      - "SHADOWSOCKS_CIPHER=---"
      - "HTTPPROXY_PASSWORD_SECRETFILE=/run/secrets/httpproxy_password"
      - "WIREGUARD_PRESHARED_KEY=---"
      - "PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=off"
      - "SHADOWSOCKS_LISTENING_ADDRESS=:8388"
      - "LOG_LEVEL=info"
      - "PPROF_BLOCK_PROFILE_RATE=0"
      - "OPENVPN_PASSWORD="
      - "VPN_PORT_FORWARDING=off"
      - "DOT_PROVIDERS=cloudflare"
      - "UNBLOCK="
      - "HTTPPROXY_LISTENING_ADDRESS=:8888"
      - "OPENVPN_PROTOCOL=udp"
      - "VPN_INTERFACE=tun0"
      - "FIREWALL_DEBUG=off"
      - "FIREWALL=on"
      - "HEALTH_SERVER_ADDRESS=127.0.0.1:9999"
      - "OPENVPN_CLIENTCRT_SECRETFILE=/run/secrets/openvpn_clientcrt"
      - "WIREGUARD_ADDRESSES=---"
      - "FREE_ONLY="
      - "FIREWALL_OUTBOUND_SUBNETS="
      - "PUBLICIP_PERIOD=12h"
      - "OPENVPN_ENCRYPTED_KEY_SECRETFILE=/run/secrets/openvpn_encrypted_key"
      - "HTTPPROXY_LOG=off"
      - "UPDATER_PERIOD=0"
      - "BLOCK_MALICIOUS=on"
      - "OPENVPN_KEY_PASSPHRASE_SECRETFILE=/run/secrets/openvpn_key_passphrase"
      - "DOT_CACHING=on"
      - "OWNED_ONLY=no"
      - "ISP="
      - "FIREWALL_INPUT_PORTS="
      - "OPENVPN_AUTH="
      - "WIREGUARD_ALLOWED_IPS="
      - "VPN_PORT_FORWARDING_PROVIDER="
      - "HTTPPROXY_STEALTH=off"
      - "HTTP_CONTROL_SERVER_LOG=on"
    hostname: "713d9e8576eb"
    image: "qmcgaw/gluetun:latest"
    ipc: "private"
    labels:
      (removed since i don't think you need this for the issue)
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "gluetun_default"
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8080:8080/tcp"
    restart: "unless-stopped"
networks:
  gluetun_default:
    external: true
    name: "gluetun_default"
```

**Comment by qdm12** [comment] 2023-08-19 09:44
```
Failed to load updated MTU of device: failed to get MTU of TUN device: no such device
```

Looks suspicious, try adding

```yml
devices:
  - /dev/net/tun:/dev/net/tun
```

Maybe also ipv6 is at fault 🤔?

**Comment by millionsofplayers** [comment] 2023-08-31 16:33
Sorry about the late reply, I use portainer. How would I add that in through portainer?

**Comment by bnhf** [comment] 2023-08-31 16:48
@millionsofplayers 

> Sorry about the late reply, I use portainer. How would I add that in through portainer?

It would go in your gluetun Portainer-Stack, typically right after ```cap_add:```, though the postion is not important.

Something like this:
```yml
version: '3.9'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8100:8000 # Remote Control VPN
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=openvpn
      - SERVER_COUNTRIES=Canada
      - OPENVPN_CIPHERS=AES-256-GCM
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - /data/openvpn:/gluetun # /data/openvpn contains client.crt and client.key
    restart: unless-stopped

**Comment by millionsofplayers** [comment] 2023-08-31 16:55
I had openvpn variables too so i switched it from wireguard to openvpn and it said:

 023-08-31T16:51:48Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com on 127.0.0.1:53: read udp 127.0.0.1:47670->127.0.0.1:53: read: connection refused

, restarted and now it says healthy. I can't get qbittorrent to connect though, i set it to use the same network as gluetun and the ports are open

**Comment by millionsofplayers** [comment] 2023-08-31 17:04
Yeah I don't know what's going on with the qbittorrent thing, i removed 8080, restarted (it worked fine) and added it again (tcp) and it's doing what i described earlier

**Comment by bnhf** [comment] 2023-08-31 17:26
@millionsofplayers 

> restarted and now it says healthy. I can't get qbittorrent to connect though, i set it to use the same network as gluetun and the ports are open

Any other containers you want to connect through Gluetun should use ```network_mode: 'service:gluetun'``` if they're in the same stack. Or, if they're separate stacks, you'd use ```network_mode: 'container:gluetun'```

**Comment by millionsofplayers** [comment] 2023-08-31 19:45
On portainer it says they're both connected to gluetun_default, I'll try that again as soon as I can though.

**Comment by qdm12** [comment] 2023-09-22 09:02
`connection refused` is usually a firewall blocking it, I guess the wireguard setup kind of failed (due to missing NET_ADMIN or /dev/net/tun bind mount) and so the firewall setup within gluetun is not allowing traffic outside the VPN (as expected).

> On portainer it says they're both connected to gluetun_default

Not the same. It means Gluetun and other containers are in the same network, what you want is for other containers to use the network stack of Gluetun, and you need to use what @bnhf described above using `network_mode: "service:gluetun"`. It's all documented in the Gluetun Wiki 😉 

Closing this since it's a configuration problem, not a bug. Also thanks Scott!!

**Closed by qdm12** 2023-09-22 09:02 UTC
