### ISSUE TITLE
Bug: Torguard port forwarding stops working

### ISSUE THREAD

**Issue by perry-mitchell** [qdm12/gluetun#1230] opened 2022-11-09 06:53 UTC
### Is this urgent?

Yes

### Host OS

Unraid / Docker

### CPU arch

x86_64

### VPN service provider

TorGuard

### What are you using to run the container

Other

### What is the version of Gluetun

(can't view all logs: running latest, and updated, however)

### What's the problem 🤔

After a while the healthcheck fails and then port forwarding ceases to function. Port forwarding works when I restart the container, but not after the intermittent healthcheck failure.

### Share your logs

```plain text
2022-11-09T07:21:22+02:00 INFO IPv6 is not supported
2022-11-09T07:21:22+02:00 INFO [routing] default route found: interface eth0, gateway 192.168.0.1 and assigned IP 192.168.0.176
2022-11-09T07:21:22+02:00 INFO [routing] adding route for 0.0.0.0/0
2022-11-09T07:21:22+02:00 INFO [firewall] setting allowed subnets...
2022-11-09T07:21:22+02:00 INFO [routing] default route found: interface eth0, gateway 192.168.0.1 and assigned IP 192.168.0.176
2022-11-09T07:21:22+02:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022-11-09T07:21:22+02:00 INFO [firewall] setting allowed input port 8112 through interface eth0...
2022-11-09T07:21:22+02:00 INFO [firewall] setting allowed input port 58846 through interface eth0...
2022-11-09T07:21:22+02:00 INFO [pprof] http server listening on [::]:6060
2022-11-09T07:21:22+02:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
2022-11-09T07:21:22+02:00 INFO [http server] http server listening on [::]:8000
2022-11-09T07:21:22+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
2022-11-09T07:21:22+02:00 INFO [firewall] allowing VPN connection...
2022-11-09T07:21:22+02:00 INFO [openvpn] OpenVPN 2.4.12 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Mar 24 2022
2022-11-09T07:21:22+02:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
2022-11-09T07:21:22+02:00 WARN [openvpn] --ping should normally be used with --ping-restart or --ping-exit
2022-11-09T07:21:22+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]195.206.105.52:1912
2022-11-09T07:21:22+02:00 INFO [openvpn] Attempting to establish TCP connection with [AF_INET]195.206.105.52:1912 [nonblock]
2022-11-09T07:21:23+02:00 INFO [openvpn] TCP connection established with [AF_INET]195.206.105.52:1912
2022-11-09T07:21:23+02:00 INFO [openvpn] TCP_CLIENT link local: (not bound)
2022-11-09T07:21:23+02:00 INFO [openvpn] TCP_CLIENT link remote: [AF_INET]195.206.105.52:1912
2022-11-09T07:21:23+02:00 WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1583', remote='link-mtu 1571'
2022-11-09T07:21:23+02:00 WARN [openvpn] 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
2022-11-09T07:21:23+02:00 WARN [openvpn] 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-128-CBC'
2022-11-09T07:21:23+02:00 WARN [openvpn] 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
2022-11-09T07:21:23+02:00 WARN [openvpn] 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
2022-11-09T07:21:23+02:00 INFO [openvpn] [server] Peer Connection Initiated with [AF_INET]195.206.105.52:1912
2022-11-09T07:21:25+02:00 INFO [openvpn] TUN/TAP device tun0 opened
2022-11-09T07:21:25+02:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2022-11-09T07:21:25+02:00 INFO [openvpn] /sbin/ip addr add dev tun0 local 10.34.0.97 peer 10.34.0.98
2022-11-09T07:21:25+02:00 INFO [openvpn] UID set to nonrootuser
2022-11-09T07:21:25+02:00 INFO [openvpn] Initialization Sequence Completed
2022-11-09T07:21:25+02:00 INFO [firewall] setting allowed input port 54321 through interface tun0...
2022-11-09T07:21:25+02:00 INFO [firewall] setting allowed input port 51234 through interface tun0...
2022-11-09T07:21:25+02:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
2022-11-09T07:21:25+02:00 INFO [healthcheck] healthy!
2022-11-09T07:21:26+02:00 INFO [dns over tls] downloading hostnames and IP block lists
2022-11-09T07:21:31+02:00 INFO [dns over tls] init module 0: validator
2022-11-09T07:21:31+02:00 INFO [dns over tls] init module 1: iterator
2022-11-09T07:21:31+02:00 INFO [dns over tls] start of service (unbound 1.15.0).
2022-11-09T07:21:31+02:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-11-09T07:21:31+02:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2022-11-09T07:21:32+02:00 INFO [dns over tls] ready
2022-11-09T07:21:32+02:00 INFO [vpn] You are running on the bleeding edge of latest!
2022-11-09T07:21:32+02:00 INFO [ip getter] Public IP address is 195.206.105.52 (Switzerland, Zurich, Zürich)
2022-11-09T07:26:01+02:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4 140.82.121.4:443: i/o timeout
2022-11-09T07:26:03+02:00 INFO [healthcheck] healthy!
2022-11-09T07:41:18+02:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4 140.82.121.4:443: i/o timeout
2022-11-09T07:41:26+02:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
2022-11-09T07:41:26+02:00 INFO [vpn] stopping
2022-11-09T07:41:26+02:00 INFO [firewall] removing allowed port 54321...
2022-11-09T07:41:26+02:00 INFO [firewall] removing allowed port 51234...
2022-11-09T07:41:26+02:00 INFO [vpn] starting
2022-11-09T07:41:26+02:00 INFO [firewall] allowing VPN connection...
2022-11-09T07:41:26+02:00 INFO [openvpn] OpenVPN 2.4.12 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Mar 24 2022
2022-11-09T07:41:26+02:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
2022-11-09T07:41:26+02:00 WARN [openvpn] --ping should normally be used with --ping-restart or --ping-exit
2022-11-09T07:41:26+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]195.206.105.52:1912
2022-11-09T07:41:26+02:00 INFO [openvpn] Attempting to establish TCP connection with [AF_INET]195.206.105.52:1912 [nonblock]
2022-11-09T07:41:27+02:00 INFO [openvpn] TCP connection established with [AF_INET]195.206.105.52:1912
2022-11-09T07:41:27+02:00 INFO [openvpn] TCP_CLIENT link local: (not bound)
2022-11-09T07:41:27+02:00 INFO [openvpn] TCP_CLIENT link remote: [AF_INET]195.206.105.52:1912
2022-11-09T07:41:28+02:00 WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1583', remote='link-mtu 1571'
2022-11-09T07:41:28+02:00 WARN [openvpn] 'tun-mtu' is used inconsistently, local='tun-mtu 1532', remote='tun-mtu 1500'
2022-11-09T07:41:28+02:00 WARN [openvpn] 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-128-CBC'
2022-11-09T07:41:28+02:00 WARN [openvpn] 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
2022-11-09T07:41:28+02:00 WARN [openvpn] 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
2022-11-09T07:41:28+02:00 INFO [openvpn] [server] Peer Connection Initiated with [AF_INET]195.206.105.52:1912
2022-11-09T07:41:29+02:00 INFO [openvpn] TUN/TAP device tun0 opened
2022-11-09T07:41:29+02:00 INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
2022-11-09T07:41:29+02:00 INFO [openvpn] /sbin/ip addr add dev tun0 local 10.34.0.97 peer 10.34.0.98
2022-11-09T07:41:29+02:00 ERROR [openvpn] RTNETLINK answers: File exists
2022-11-09T07:41:29+02:00 ERROR [openvpn] Linux route add command failed: external program exited with error status: 2
2022-11-09T07:41:29+02:00 INFO [openvpn] UID set to nonrootuser
2022-11-09T07:41:29+02:00 INFO [openvpn] Initialization Sequence Completed
2022-11-09T07:41:29+02:00 INFO [firewall] setting allowed input port 54321 through interface tun0...
2022-11-09T07:41:29+02:00 INFO [firewall] setting allowed input port 51234 through interface tun0...
2022-11-09T07:41:30+02:00 INFO [ip getter] Public IP address is 195.206.105.52 (Switzerland, Zurich, Zürich)
2022-11-09T07:41:31+02:00 INFO [healthcheck] healthy!
2022-11-09T08:09:35+02:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4 140.82.121.4:443: i/o timeout
2022-11-09T08:09:36+02:00 INFO [healthcheck] healthy!
```

**Comment by qdm12** [comment] 2022-11-10 20:46
Duplicate of #1233

**Closed by qdm12** 2022-11-10 20:46 UTC
