### ISSUE TITLE
Bug: Cannot open ports while using the VPN

### ISSUE THREAD

**Issue by RiversideRocks** [qdm12/gluetun#795] opened 2022-01-17 01:54 UTC
### Is this urgent?

Yes

### Host OS

Ubuntu Impish

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2022-01-14T16:20:48.798Z (commit 2ad23a0)

### What's the problem 🤔

I'm trying to run the VPN on a container that opens ports on my machine. I keep getting an error saying "docker: Error response from daemon: conflicting options: port publishing and the container type network mode.". How can I get around this issue?

### Share your logs

```log
docker: Error response from daemon: conflicting options: port publishing and the container type network mode.
```

**Comment by TomBursch** [comment] 2022-01-17 17:52
This error occurs when a container has ports specified as well as the network mode. The ports section has to be added to the gluetun container itself and not any dependent container.
See the relevant [Wiki](https://github.com/qdm12/gluetun/wiki/Port-mapping).

**Comment by qdm12** [comment] 2022-01-18 23:09
Awesome thanks @TomBursch for the help! Closing the issue as this is not a bug 😉

**Closed by qdm12** 2022-01-18 23:09 UTC
