### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by YunhaoJiang** [qdm12/gluetun#1104] opened 2022-08-12 06:11 UTC
### What's the feature 🧐

Hi,
I'm wondering that is it possible to add a feature to the private internet access to allow us to use the "dedicated IP"?
It requires an extra field of "token" to authorize.
Tried to fill the hostname with the dedicated IP assigned to me, but it is not working.

### Extra information and references

https://www.privateinternetaccess.com/vpn-features/dedicated-ip-vpn
https://helpdesk.privateinternetaccess.com/guides/account-changes/general-account-information/how-to-purchase-and-use-dedicated-ips#how-to-purchase-and-use-dedicated-ips_command-line-interface
https://helpdesk.privateinternetaccess.com/kb/articles/can-i-configure-the-vpn-connection-to-always-use-the-same-ip-address

**Comment by qdm12** [comment] 2022-08-12 22:04
Duplicate of #1003 please subscribe to that issue instead, thank you!

**Closed by qdm12** 2022-08-12 22:04 UTC
