### ISSUE TITLE
http server curl public ip?

### ISSUE THREAD

**Issue by BoW2EviL** [qdm12/gluetun#989] opened 2022-05-15 03:40 UTC
maybe its just me but i pulled the new docker image this morning and 
could not curl the public ip address.

specs:
rpi4, 8gb ram, 128gb sd running raspibian bullseye x64
Docker version 20.10.16, build aa7e414

Portion of docker-compose.yml

```yml
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:dev/net/tun
    networks:
      piratenet:
        ipv4_address: redacted
    ports:
     #PORT_FORWARDING blah blah
      - redacted
      - "8000:8000"     # gluetun api
    volumes:
      - /srv/configs/pirate/gluetun/config:/gluetun
      - /srv/configs/pirate/gluetun/foward:/tmp/forwarded_port_dir
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE=redacted
      - TZ=America/New_York
      - OPENVPN_USER=redacted
      - OPENVPN_PASSWORD=redacted
      - "SERVER_REGIONS=CA Toronto,CA Vancouver"
      # - REGION=Mexico
```

what i did to find issue:
after doing a PULL to get the current version of gluetun i noticed a script i was running was always returning a blank ip ie:{public_ip:""}. i figured it might be the token or the forward files so i deleted them and tried a fresh start with DOWN the UP. while watching the logs i didn't notice anything a miss. the log even contained the valid ip issued but it still didn't return a public ip from the http server(port 8000) ie:"curl -s localhost:8000/v1/publicip/ip". after several attempts i gave up.

to fix my issue:
 i changed docker-compose.yml to...

```yml
services:
  gluetun:
    image: qmcgaw/gluetun:v3.28.2   
    container_name: gluetun
```
after a docker PULL, DOWN, then UP everything went back to normal.

it could just be me. but i figured i should report it.

Thx so much for gluetun it has been a wonderful experience

**Comment by matt-laird** [comment] 2022-05-15 21:23
I'm having the same issue, seems with `DOT` enabled the public IP doesn't get fetched, which yields an empty string in the HTTP server request to get the public IP.

**Comment by BoW2EviL** [comment] 2022-05-16 00:47
i just had it happen again this morning i suffered a 6 hr power failure. 
i have not had a chance to look over anything tell now and one thing stuck out in the logs 

```
2022/05/15 19:20:00 INFO port forwarding: retrying in 5s
2022/05/15 19:20:05 INFO port forwarding: Found saved forwarded port data for port 21154
2022/05/15 19:20:05 INFO port forwarding: Forwarded port data expires in 61 days
2022/05/15 19:20:05 INFO port forwarding: Port forwarded data expires in 61 days
2022/05/15 19:20:05 ERROR port forwarding: cannot bind port: Get "https://REDACT:19999/bindPort?payload=<payload>&signature=REDACT: x509: certificate is valid for vancouver420, not vancouver412

```
this has looped like this all day long 

the first docker restart changed nothing 
  rm gluetun/config/piaportforward.json
docker restart -- it got a new token and port but nothing from curl
docker restart -- everything back to normal?

**Comment by qdm12** [comment] 2022-05-27 17:09
Regarding the initial issue reported, I cannot reproduce (with the latest image 1ba1ecbedae7cd4c964c96c6f3969c72df6b1d5c and DOT enabled).

@BoW2EviL they are fields to fill in to create an issue, it's not made for donkeys 🐴
For example I have no idea what latest image you are running (it could be any commit from any time). Also the logs are not there, so I can't really help. So please create another issue with these fields filled if it happens again.

Regarding the other issue (also here, please create another issue instead of continuing in this thread):

```
x509: certificate is valid for vancouver420, not vancouver412
```

That might just be a misconfiguration on PIA's end on some of their (Vancouver) servers. Or try updating your servers data for PIA (https://github.com/qdm12/gluetun/wiki/Updating-servers).

> random docker restarts cause this to appear in the log

These logs are expected, there is nothing wrong with them, it's just 'warnings' that PIA mutes on their openvpn configuration files.

Closing this for now, please create other properly formatted issues if this persists.

**Closed by qdm12** 2022-05-27 17:09 UTC
