### ISSUE TITLE
Feature request: Private Internet Access Dedicated IP Server Selection

### ISSUE THREAD

**Issue by phoenix1of1** [qdm12/gluetun#2402] opened 2024-08-07 19:51 UTC
### What's the feature 🧐

PIA supports the use of dedicated IPs which are restricted to one server location. For example, once I have purchased the necessary subscription addon, I am assigned a token which I can then redeem to gain a dedicated IP address on a single server location.

Is there any way in which Gluetun can support the use of the dedicated IP service so all traffic through a Docker Stack can be routed through that dedicated IP as opposed to being routed through one of their group shared IPs?

Thanks in advance!

**Comment by qdm12** [comment] 2024-08-08 07:26
Duplicate of #1003 please subscribe to that one instead 😉

**Closed by qdm12** 2024-08-08 07:26 UTC
Labels: Closed: 👥 Duplicate, ☁️ PIA
