### ISSUE TITLE
ERROR VPN settings

### ISSUE THREAD

**Issue by umbongodrink** [qdm12/gluetun#1615] opened 2023-05-27 09:29 UTC
I have used gluetun successfully in conjunction with deluge for over 2 years, periodically updating by pulling the latest image. The previous time I did this was 2 weeks ago. This morning I have pulled the latest image again, and now I am unable to start the service. 

I receive the error: 
ERROR VPN settings: provider settings: server selection: for VPN service provider [...] the region specified is not valid: value is not one of the possible choices:...

I get this same error if I use NordVPN or Private Internet Access.
The error messages includes a list of valid servers, which I can try in my docker-compose.yml file exactly as written, but still the same error. 

Is it possible to fix this error, or at least roll-back to using a previous image from 2 weeks ago? 
Thank you!

**Comment by frepke** [comment] 2023-05-27 09:45
I think it's solved a few minutes ago. Pull the :latest and try again.

**Comment by umbongodrink** [comment] 2023-05-27 10:03
Awesome! Thanks for the quick response! :) 

I've just reverted to the v3.33 tagged image, will pull the latest and try using that in a couple of hours and will report back asap!

**Comment by umbongodrink** [comment] 2023-05-27 12:09
Hi, I pulled the latest. 
Interestingly, I got a new error, warning me that:

ERROR VPN settings: provider settings: port forwarding: port forwarding cannot be enabled: value is not one of the possible choices: nordvpn must be one of private internet access

The docker-compose.yml file I'm using was originally created for PIA, but I've been using it with NordVPN for many years (with only certain login details amended). 

It seems like this new "latest" image of gluetun is more strict? 
I ask this because the exact same docker-compose.yml file works fine with tag v3.33 of the image. 

(I commented-out the port forwarding line in the docker-compose.yml file when using NordVPN and the "latest" image, and gluetun is working again)

**Comment by qdm12** [comment] 2023-05-27 12:28
@umbongodrink I don't think the logic changed. Note if you use `VPN_PORT_FORWARDING`, this is a new name since v3.34.0 so it's just ignored by < v3.34.0 images:

https://github.com/qdm12/gluetun/compare/v3.33.0...master#diff-6831aea2688be791b67b5c8c5143ac526e56e247bb377df73bd41001104af991R12-R13

Anyway, the error message is as intended, port forwarding is not supported by nordvpn..... YET!!!

If you want to help you test port forwarding for NordVPN, please read+comment on #1488 and you can try with image `qmcgaw/gluetun:pr-1543`.

Closing this for now since it seems resolved 👍

**Closed by qdm12** 2023-05-27 12:28 UTC
