### ISSUE TITLE
Bug: ERROR [vpn] stopping port forwarding: interface not set

### ISSUE THREAD

**Issue by madsbacha** [qdm12/gluetun#1901] opened 2023-10-06 18:54 UTC
### Is this urgent?

Yes

### Host OS

Raspbian

### CPU arch

armv7l

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-10-06T16:15:28.759Z (commit ee413f5)

### What's the problem 🤔

I have a container that uses "network_mode" to route traffic through the gluetun docker container. The torrent client cannot connect to anything. I can access the torrent web client through the opened port on the gluetun container. When I use the build-in port checker of the torrent client I get an error of "no response". I can specifically see the following error in the logs of the gluetun container: `ERROR [vpn] stopping port forwarding: interface not`.

I have two devices that suddenly have this behaviour.
**One is using this version:** `Running version latest built on 2023-09-28T14:05:11.407Z (commit d4df872)`
and `uname -a` produces: `Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux`
**The other is using this version**: `Running version latest built on 2023-10-06T16:15:28.759Z (commit ee413f5)`
and `uname -a` produces: `Linux pistorage 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`
They both receive the `ERROR [vpn] stopping port forwarding: interface not` error and generally the logs look the same.

### Share your logs (at least 10 lines)

```plain text
gluetun         | ========================================
gluetun         | ========================================
gluetun         | =============== gluetun ================
gluetun         | ========================================
gluetun         | =========== Made with ❤️ by ============
gluetun         | ======= https://github.com/qdm12 =======
gluetun         | ========================================
gluetun         | ========================================
gluetun         |
gluetun         | Running version latest built on 2023-10-06T16:15:28.759Z (commit ee413f5)
gluetun         |
gluetun         | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun         | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun         | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun         | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun         | 💻 Email? quentin.mcgaw@gmail.com
gluetun         | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun         | 2023-10-06T20:43:04+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
gluetun         | 2023-10-06T20:43:04+02:00 INFO [routing] local ethernet link found: eth0
gluetun         | 2023-10-06T20:43:04+02:00 INFO [routing] local ipnet found: 172.17.0.0/16
gluetun         | 2023-10-06T20:43:04+02:00 INFO [firewall] enabling...
gluetun         | 2023-10-06T20:43:04+02:00 INFO [firewall] enabled successfully
gluetun         | 2023-10-06T20:43:06+02:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
gluetun         | 2023-10-06T20:43:07+02:00 INFO Alpine version: 3.18.4
gluetun         | 2023-10-06T20:43:07+02:00 INFO OpenVPN 2.5 version: 2.5.8
gluetun         | 2023-10-06T20:43:07+02:00 INFO OpenVPN 2.6 version: 2.6.5
gluetun         | 2023-10-06T20:43:07+02:00 INFO Unbound version: 1.17.1
gluetun         | 2023-10-06T20:43:07+02:00 INFO IPtables version: v1.8.9
gluetun         | 2023-10-06T20:43:07+02:00 INFO Settings summary:
gluetun         | ├── VPN settings:
gluetun         | |   ├── VPN provider settings:
gluetun         | |   |   ├── Name: private internet access
gluetun         | |   |   ├── Server selection settings:
gluetun         | |   |   |   ├── VPN type: openvpn
gluetun         | |   |   |   ├── Regions: se stockholm
gluetun         | |   |   |   └── OpenVPN server selection settings:
gluetun         | |   |   |       ├── Protocol: UDP
gluetun         | |   |   |       └── Private Internet Access encryption preset: strong
gluetun         | |   |   └── Automatic port forwarding settings:
gluetun         | |   |       ├── Use port forwarding code for current provider
gluetun         | |   |       └── Forwarded port file path: /forwarded_port
gluetun         | |   └── OpenVPN settings:
gluetun         | |       ├── OpenVPN version: 2.5
gluetun         | |       ├── User: [set]
gluetun         | |       ├── Password: [set]
gluetun         | |       ├── Private Internet Access encryption preset: strong
gluetun         | |       ├── Network interface: tun0
gluetun         | |       ├── Run OpenVPN as: root
gluetun         | |       └── Verbosity level: 1
gluetun         | ├── DNS settings:
gluetun         | |   ├── Keep existing nameserver(s): no
gluetun         | |   ├── DNS server address to use: 127.0.0.1
gluetun         | |   └── DNS over TLS settings:
gluetun         | |       ├── Enabled: yes
gluetun         | |       ├── Update period: every 24h0m0s
gluetun         | |       ├── Unbound settings:
gluetun         | |       |   ├── Authoritative servers:
gluetun         | |       |   |   └── cloudflare
gluetun         | |       |   ├── Caching: yes
gluetun         | |       |   ├── IPv6: no
gluetun         | |       |   ├── Verbosity level: 1
gluetun         | |       |   ├── Verbosity details level: 0
gluetun         | |       |   ├── Validation log level: 0
gluetun         | |       |   ├── System user: root
gluetun         | |       |   └── Allowed networks:
gluetun         | |       |       ├── 0.0.0.0/0
gluetun         | |       |       └── ::/0
gluetun         | |       └── DNS filtering settings:
gluetun         | |           ├── Block malicious: yes
gluetun         | |           ├── Block ads: no
gluetun         | |           ├── Block surveillance: no
gluetun         | |           └── Blocked IP networks:
gluetun         | |               ├── 127.0.0.1/8
gluetun         | |               ├── 10.0.0.0/8
gluetun         | |               ├── 172.16.0.0/12
gluetun         | |               ├── 192.168.0.0/16
gluetun         | |               ├── 169.254.0.0/16
gluetun         | |               ├── ::1/128
gluetun         | |               ├── fc00::/7
gluetun         | |               ├── fe80::/10
gluetun         | |               ├── ::ffff:127.0.0.1/104
gluetun         | |               ├── ::ffff:10.0.0.0/104
gluetun         | |               ├── ::ffff:169.254.0.0/112
gluetun         | |               ├── ::ffff:172.16.0.0/108
gluetun         | |               └── ::ffff:192.168.0.0/112
gluetun         | ├── Firewall settings:
gluetun         | |   ├── Enabled: yes
gluetun         | |   └── Outbound subnets:
gluetun         | |       └── 192.168.0.0/24
gluetun         | ├── Log settings:
gluetun         | |   └── Log level: INFO
gluetun         | ├── Health settings:
gluetun         | |   ├── Server listening address: 127.0.0.1:9999
gluetun         | |   ├── Target address: cloudflare.com:443
gluetun         | |   ├── Duration to wait after success: 5s
gluetun         | |   ├── Read header timeout: 100ms
gluetun         | |   ├── Read timeout: 500ms
gluetun         | |   └── VPN wait durations:
gluetun         | |       ├── Initial duration: 6s
gluetun         | |       └── Additional duration: 5s
gluetun         | ├── Shadowsocks server settings:
gluetun         | |   └── Enabled: no
gluetun         | ├── HTTP proxy settings:
gluetun         | |   └── Enabled: no
gluetun         | ├── Control server settings:
gluetun         | |   ├── Listening address: :8000
gluetun         | |   └── Logging: yes
gluetun         | ├── OS Alpine settings:
gluetun         | |   ├── Process UID: 1000
gluetun         | |   ├── Process GID: 1000
gluetun         | |   └── Timezone: europe/copenhagen
gluetun         | ├── Public IP settings:
gluetun         | |   ├── Fetching: every 12h0m0s
gluetun         | |   └── IP file path: /tmp/gluetun/ip
gluetun         | └── Version settings:
gluetun         |     └── Enabled: yes
gluetun         | 2023-10-06T20:43:07+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
gluetun         | 2023-10-06T20:43:07+02:00 INFO [routing] adding route for 0.0.0.0/0
gluetun         | 2023-10-06T20:43:07+02:00 INFO [firewall] setting allowed subnets...
gluetun         | 2023-10-06T20:43:07+02:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1, assigned IP 172.17.0.2 and family v4
gluetun         | 2023-10-06T20:43:07+02:00 INFO [routing] adding route for 192.168.0.0/24
gluetun         | 2023-10-06T20:43:07+02:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun         | 2023-10-06T20:43:07+02:00 INFO [dns] using plaintext DNS at address 1.1.1.1
gluetun         | 2023-10-06T20:43:07+02:00 INFO [http server] http server listening on [::]:8000
gluetun         | 2023-10-06T20:43:07+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
gluetun         | 2023-10-06T20:43:07+02:00 INFO [firewall] allowing VPN connection...
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] OpenVPN 2.5.8 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] library versions: OpenSSL 3.1.3 19 Sep 2023, LZO 2.10
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] MIIDWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAwHgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRlaW50ZXJuZXRhY2Nlc3MuY29tFw0xNjA3MDgxOTAwNDZaFw0zNjA3MDMxOTAwNDZaMCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG9w0BAQ0FAAOCAgEAppFfEpGsasjB1QgJcosGpzbf2kfRhM84o2TlqY1ua+Gi5TMdKydA3LJcNTjlI9a0TYAJfeRX5IkpoglSUuHuJgXhP3nEvX10mjXDpcu/YvM8TdE5JV2+EGqZ80kFtBeOq94WcpiVKFTR4fO+VkOK9zwspFfb1cNs9rHvgJ1QMkRUF8PpLN6AkntHY0+6DnigtSaKqldqjKTDTv2OeH3nPoh80SGrt0oCOmYKfWTJGpggMGKvIdvU3vH9+EuILZKKIskt+1dwdfA5Bkz1GLmiQG7+9ZZBQUjBG9Dos4hfX/rwJ3eU8oUIm4WoTz9rb71SOEuUUjP5NPy9HNx2vx+cVvLsTF4ZDZaUztW9o9JmIURDtbeyqxuHN3prlPWB6aj73IIm2dsDQvs3XXwRIxs8NwLbJ6CyEuvEOVCskdM8rdADWx1J0lRNlOJ0Z8ieLLEmYAA834VN1SboB6wJIAPxQU3rcBhXqO9y8aa2oRMg8NxZ5gr+PnKVMqag1x0IxbIgLxtkXQvxXxQHEMSODzvcOfK/nBRBsqTj30P+R87sU8titOoxNeRnBDRNhdEy/QGAqGh62ShPpQUCJdnKRiRTjnil9hMQHevoSuFKeEMO30FQL7BZyo37GFU+q1WPCplVZgCP9hC8Rn5K2+f6KLFo5bhtowSmu+GY1yZtg+RTtsA=
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] -----END X509 CRL-----
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]195.246.120.132:1197
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] UDP link local: (not bound)
gluetun         | 2023-10-06T20:43:07+02:00 INFO [openvpn] UDP link remote: [AF_INET]195.246.120.132:1197
gluetun         | 2023-10-06T20:43:13+02:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
gluetun         | 2023-10-06T20:43:13+02:00 INFO [vpn] stopping
gluetun         | 2023-10-06T20:43:13+02:00 ERROR [vpn] stopping port forwarding: interface not set
gluetun         | 2023-10-06T20:43:13+02:00 INFO [vpn] starting
gluetun         | 2023-10-06T20:43:13+02:00 INFO [firewall] allowing VPN connection...
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] OpenVPN 2.5.8 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] library versions: OpenSSL 3.1.3 19 Sep 2023, LZO 2.10
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] MIIDWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTETMBEGA1UEBxMKTG9zQW5nZWxlczEgMB4GA1UEChMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxIDAeBgNVBAsTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSAwHgYDVQQDExdQcml2YXRlIEludGVybmV0IEFjY2VzczEgMB4GA1UEKRMXUHJpdmF0ZSBJbnRlcm5ldCBBY2Nlc3MxLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRlaW50ZXJuZXRhY2Nlc3MuY29tFw0xNjA3MDgxOTAwNDZaFw0zNjA3MDMxOTAwNDZaMCYwEQIBARcMMTYwNzA4MTkwMDQ2MBECAQYXDDE2MDcwODE5MDA0NjANBgkqhkiG9w0BAQ0FAAOCAgEAppFfEpGsasjB1QgJcosGpzbf2kfRhM84o2TlqY1ua+Gi5TMdKydA3LJcNTjlI9a0TYAJfeRX5IkpoglSUuHuJgXhP3nEvX10mjXDpcu/YvM8TdE5JV2+EGqZ80kFtBeOq94WcpiVKFTR4fO+VkOK9zwspFfb1cNs9rHvgJ1QMkRUF8PpLN6AkntHY0+6DnigtSaKqldqjKTDTv2OeH3nPoh80SGrt0oCOmYKfWTJGpggMGKvIdvU3vH9+EuILZKKIskt+1dwdfA5Bkz1GLmiQG7+9ZZBQUjBG9Dos4hfX/rwJ3eU8oUIm4WoTz9rb71SOEuUUjP5NPy9HNx2vx+cVvLsTF4ZDZaUztW9o9JmIURDtbeyqxuHN3prlPWB6aj73IIm2dsDQvs3XXwRIxs8NwLbJ6CyEuvEOVCskdM8rdADWx1J0lRNlOJ0Z8ieLLEmYAA834VN1SboB6wJIAPxQU3rcBhXqO9y8aa2oRMg8NxZ5gr+PnKVMqag1x0IxbIgLxtkXQvxXxQHEMSODzvcOfK/nBRBsqTj30P+R87sU8titOoxNeRnBDRNhdEy/QGAqGh62ShPpQUCJdnKRiRTjnil9hMQHevoSuFKeEMO30FQL7BZyo37GFU+q1WPCplVZgCP9hC8Rn5K2+f6KLFo5bhtowSmu+GY1yZtg+RTtsA=
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] -----END X509 CRL-----
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]195.246.120.123:1197
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] UDP link local: (not bound)
gluetun         | 2023-10-06T20:43:13+02:00 INFO [openvpn] UDP link remote: [AF_INET]195.246.120.123:1197
```

### Share your configuration

```yml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    dns: 1.1.1.1
    ports:
      - 9091:9091
    environment:
      - VPNSP=pia
      - TZ=Europe/Copenhagen
      - REGION=SE Stockholm
      - OPENVPN_USER=123
      - OPENVPN_PASSWORD=123
      - PIA_ENCRYPTION=strong
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/forwarded_port
      - FIREWALL=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/24
      - DNS_UPDATE_PERIOD=24h
    volumes:
      - $PWD/gluetun:/gluetun
      - type: bind
        source: ./forwarded_port
        target: /forwarded_port
    restart: always
  transmission:
    image: linuxserver/transmission:4.0.3
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
```

**Comment by qdm12** [comment] 2023-10-07 12:48
Your VPN connection is not working, not due to port forwarding at all. The error you see is a consequence of the VPN internally restarting because it did not work:

```
[healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
```

See the link attached on this log line.

On the other hand, ec1f252528cee308836b4656990ec81f47e4991c should remove that error log line `stopping port forwarding: interface not set`. This is a port forwarding settings validation executing when port forwarding is asked to be stopped (due to the VPN stopping before restarting); it was error-ing because port forwarding never completed once before so the 'vpn interface' was not set in the port forwarding code yet. Now it will handle settings validation differently when asked to start the port forwarding and asked to stop it, so it will no longer 'error' on this. Although in your situation, this won't change a thing at all. Again, see the healthcheck link, and maybe your subscription validity. Anyway, not a bug so closing this 😉

**Closed by qdm12** 2023-10-07 12:48 UTC
