### ISSUE TITLE
Doesn't connect other containers but von connects flawlessly 

### ISSUE THREAD

**Issue by bijfy** [qdm12/gluetun#406] opened 2021-03-15 20:59 UTC
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): Ubuntu 18

**CPU arch** or **device name**: amd64

**What VPN provider are you using**:

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem** 🤔

That feature doesn't work

**Share your logs... (careful to remove in example tokens)**

```log

PASTE YOUR LOGS
IN THERE

```
 Vpn is working great but it doesn't connect other containers like qbittorrent, deluge.  Deployment goes on but no connection to other containers

**Comment by qdm12** [comment] 2021-03-15 21:05
Duplicate of #281 please subscribe to that one instead. You can go around it by disabling DNS over TLS and setting `DNS_KEEPNAMESERVER` (from the top of my head, check the comments/wiki). Although that will leak your DNS queries out of the VPN which isn't great either.

This is in progress though, see the last comment on the issue.

**Closed by qdm12** 2021-03-15 21:05 UTC

**Comment by techie2000** [comment] 2021-08-07 18:53
> You can go around it by disabling DNS over TLS and setting `DNS_KEEPNAMESERVER` (from the top of my head, check the comments/wiki). Although that will leak your DNS queries out of the VPN which isn't great either.

For anyone reading this, be aware it is `DNS_KEEP_NAMESERVER` rather than `DNS_KEEPNAMESERVER` and takes a value of OFF|ON
