### ISSUE TITLE
Feature request: IPVanish VPN

### ISSUE THREAD

**Issue by neiliid** [qdm12/gluetun#416] opened 2021-04-07 15:38 UTC
Inclusion of IPVanish VPN service into Gluetun.

- IPVanish is a well supported, OpenVpn based VPN provider with a number points of presence globally and excellent throughput and should make a good addition to the Gluetun image.

IP Vanish utilises standard OpenVPN CRT and config files which means that the inclusion should be relatively straight forward.

The configs for IP Vanish are available from https://www.ipvanish.com/software/configs/configs.zip

I hope others support this inclusion. Thanks for a great package.

**Comment by qdm12** [comment] 2021-04-08 14:07
Thanks for the details. I'll get to it this weekend.

**Comment by qdm12** [comment] 2021-05-31 03:13
@neiliid sorry for the long delay. There should now be an image `qmcgaw/gluetun:ipvanish` that you can use with `-e VPNSP=ipvanish`. I'll add documentation tomorrow and ping back here once it's up, but feel free to try like so. You can probably spin it up by simply setting `OPENVPN_USER` and `OPENVPN_PASSWORD` (see the github wiki).

**Comment by neiliid** [comment] 2021-05-31 06:44
Thanks a stack, will test it out

**Comment by qdm12** [comment] 2021-05-31 19:07
Are you perhaps running on a Raspberry Pi? If so follow step 2. of the setup from the Github Readme, you need to update your host Kernel thing because Alpine 3.13 and Openvpn 2.5.x use a newer representation for time 😮

**Comment by qdm12** [comment] 2021-06-07 19:23
Hey there, did you have to try [that fix](https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-812287338)? Are you running on a ARM device (e.g. raspberry pis)?

**Comment by neiliid** [comment] 2021-06-08 14:24
Hi Quentin, I am running on a Pi4..will try the fix.

**Comment by qdm12** [comment] 2021-06-20 16:22
Fixed in #475

**Closed by qdm12** 2021-06-20 16:22 UTC
Labels: Feature request :bulb:, Needs more info :thinking:

**Comment by qdm12** [comment] 2021-07-02 03:20
Note the implementation got re-fixed in 92212fdd11be3904c63b07fb29354b62d0908fd0 (available in `:latest`), a user confirmed it's now working!
