### ISSUE TITLE
Feature request: Add "stable" tag to dockerhub

### ISSUE THREAD

**Issue by cruizba** [qdm12/gluetun#861] opened 2022-02-21 10:26 UTC
### What's the feature 🧐

Add a new tag in dockerhub for the latest stable relase. I am currently using the latest version on my deployment, but as latest builds comes from master branch, it would be nice to have an stable tag in dockerhub which refers to the current stable version.

### Extra information and references

Why? By using latest version from master branch there's always the possibility of minor bugs. Using latest is great because it is always working in my experience, but a stable tag referring to the latest release would be also nice and more secure in my opinion.

Congrats on such a nice project :).

**Comment by qdm12** [comment] 2022-02-22 09:33
Duplicate of #556 please subscribe to it instead.

I'm working on it right now.

**Closed by qdm12** 2022-02-22 09:33 UTC

**Comment by qdm12** [comment] 2022-02-26 16:38
Done see https://github.com/qdm12/gluetun/issues/556#issuecomment-1052288270

**Comment by cruizba** [comment] 2022-03-19 01:18
Thanks :)
