### ISSUE TITLE
Bug: Failed to handle request: readfrom tcp splice: connection reset by peer

### ISSUE THREAD

**Issue by Miku-programm** [qdm12/gluetun#2156] opened 2024-03-14 04:17 UTC
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04 

### CPU arch

x86_64

### VPN service provider

Windscribe

### What are you using to run the container

docker-compose

### What is the version of Gluetun

commit c826707

### What's the problem 🤔

Gluetun is running well and has also connected to the VPN, but when running socks5, my connection was reset, which is strange because I tried deleting the image and creating it again, but the same error occurred. However, this error did not occur on my other VPS.

### Share your logs (at least 10 lines)

```plain text
Attaching to cambodia-gluetun-1, cambodia-socks5-1
cambodia-gluetun-1  | ========================================
cambodia-gluetun-1  | ========================================
cambodia-gluetun-1  | =============== gluetun ================
cambodia-gluetun-1  | ========================================
cambodia-gluetun-1  | =========== Made with ❤️ by ============
cambodia-gluetun-1  | ======= https://github.com/qdm12 =======
cambodia-gluetun-1  | ========================================
cambodia-gluetun-1  | ========================================
cambodia-gluetun-1  | 
cambodia-gluetun-1  | Running version latest built on 2024-01-01T18:24:19.221Z (commit c826707)
cambodia-gluetun-1  | 
cambodia-gluetun-1  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
cambodia-gluetun-1  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
cambodia-gluetun-1  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
cambodia-gluetun-1  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
cambodia-gluetun-1  | 💻 Email? quentin.mcgaw@gmail.com
cambodia-gluetun-1  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
cambodia-gluetun-1  | 2024-03-14T03:52:52Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
cambodia-gluetun-1  | 2024-03-14T03:52:52Z INFO [routing] local ethernet link found: eth0
cambodia-gluetun-1  | 2024-03-14T03:52:52Z INFO [routing] local ipnet found: 172.19.0.0/16
cambodia-gluetun-1  | 2024-03-14T03:52:52Z INFO [firewall] enabling...
cambodia-gluetun-1  | 2024-03-14T03:52:52Z INFO [firewall] enabled successfully
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [storage] creating /gluetun/servers.json with 17743 hardcoded servers
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO Alpine version: 3.18.5
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO OpenVPN 2.5 version: 2.5.8
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO OpenVPN 2.6 version: 2.6.8
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO Unbound version: 1.17.1
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO IPtables version: v1.8.9
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO Settings summary:
cambodia-gluetun-1  | ├── VPN settings:
cambodia-gluetun-1  | |   ├── VPN provider settings:
cambodia-gluetun-1  | |   |   ├── Name: windscribe
cambodia-gluetun-1  | |   |   └── Server selection settings:
cambodia-gluetun-1  | |   |       ├── VPN type: wireguard
cambodia-gluetun-1  | |   |       ├── Regions: cambodia
cambodia-gluetun-1  | |   |       └── Wireguard selection settings:
cambodia-gluetun-1  | |   └── Wireguard settings:
cambodia-gluetun-1  | |       ├── Private key: UHY...lI=
cambodia-gluetun-1  | |       ├── Pre-shared key: kYd...wg=
cambodia-gluetun-1  | |       ├── Interface addresses:
cambodia-gluetun-1  | |       |   └── 100.126.116.88/32
cambodia-gluetun-1  | |       ├── Allowed IPs:
cambodia-gluetun-1  | |       |   ├── 0.0.0.0/0
cambodia-gluetun-1  | |       |   └── ::/0
cambodia-gluetun-1  | |       └── Network interface: tun0
cambodia-gluetun-1  | |           └── MTU: 1400
cambodia-gluetun-1  | ├── DNS settings:
cambodia-gluetun-1  | |   ├── Keep existing nameserver(s): no
cambodia-gluetun-1  | |   ├── DNS server address to use: 127.0.0.1
cambodia-gluetun-1  | |   └── DNS over TLS settings:
cambodia-gluetun-1  | |       ├── Enabled: yes
cambodia-gluetun-1  | |       ├── Update period: every 24h0m0s
cambodia-gluetun-1  | |       ├── Unbound settings:
cambodia-gluetun-1  | |       |   ├── Authoritative servers:
cambodia-gluetun-1  | |       |   |   └── cloudflare
cambodia-gluetun-1  | |       |   ├── Caching: yes
cambodia-gluetun-1  | |       |   ├── IPv6: no
cambodia-gluetun-1  | |       |   ├── Verbosity level: 1
cambodia-gluetun-1  | |       |   ├── Verbosity details level: 0
cambodia-gluetun-1  | |       |   ├── Validation log level: 0
cambodia-gluetun-1  | |       |   ├── System user: root
cambodia-gluetun-1  | |       |   └── Allowed networks:
cambodia-gluetun-1  | |       |       ├── 0.0.0.0/0
cambodia-gluetun-1  | |       |       └── ::/0
cambodia-gluetun-1  | |       └── DNS filtering settings:
cambodia-gluetun-1  | |           ├── Block malicious: yes
cambodia-gluetun-1  | |           ├── Block ads: no
cambodia-gluetun-1  | |           ├── Block surveillance: no
cambodia-gluetun-1  | |           └── Blocked IP networks:
cambodia-gluetun-1  | |               ├── 127.0.0.1/8
cambodia-gluetun-1  | |               ├── 10.0.0.0/8
cambodia-gluetun-1  | |               ├── 172.16.0.0/12
cambodia-gluetun-1  | |               ├── 192.168.0.0/16
cambodia-gluetun-1  | |               ├── 169.254.0.0/16
cambodia-gluetun-1  | |               ├── ::1/128
cambodia-gluetun-1  | |               ├── fc00::/7
cambodia-gluetun-1  | |               ├── fe80::/10
cambodia-gluetun-1  | |               ├── ::ffff:127.0.0.1/104
cambodia-gluetun-1  | |               ├── ::ffff:10.0.0.0/104
cambodia-gluetun-1  | |               ├── ::ffff:169.254.0.0/112
cambodia-gluetun-1  | |               ├── ::ffff:172.16.0.0/108
cambodia-gluetun-1  | |               └── ::ffff:192.168.0.0/112
cambodia-gluetun-1  | ├── Firewall settings:
cambodia-gluetun-1  | |   └── Enabled: yes
cambodia-gluetun-1  | ├── Log settings:
cambodia-gluetun-1  | |   └── Log level: INFO
cambodia-gluetun-1  | ├── Health settings:
cambodia-gluetun-1  | |   ├── Server listening address: 127.0.0.1:9999
cambodia-gluetun-1  | |   ├── Target address: cloudflare.com:443
cambodia-gluetun-1  | |   ├── Duration to wait after success: 5s
cambodia-gluetun-1  | |   ├── Read header timeout: 100ms
cambodia-gluetun-1  | |   ├── Read timeout: 500ms
cambodia-gluetun-1  | |   └── VPN wait durations:
cambodia-gluetun-1  | |       ├── Initial duration: 6s
cambodia-gluetun-1  | |       └── Additional duration: 5s
cambodia-gluetun-1  | ├── Shadowsocks server settings:
cambodia-gluetun-1  | |   └── Enabled: no
cambodia-gluetun-1  | ├── HTTP proxy settings:
cambodia-gluetun-1  | |   ├── Enabled: yes
cambodia-gluetun-1  | |   ├── Listening address: :8888
cambodia-gluetun-1  | |   ├── User: 
cambodia-gluetun-1  | |   ├── Password: [not set]
cambodia-gluetun-1  | |   ├── Stealth mode: no
cambodia-gluetun-1  | |   ├── Log: no
cambodia-gluetun-1  | |   ├── Read header timeout: 1s
cambodia-gluetun-1  | |   └── Read timeout: 3s
cambodia-gluetun-1  | ├── Control server settings:
cambodia-gluetun-1  | |   ├── Listening address: :8000
cambodia-gluetun-1  | |   └── Logging: yes
cambodia-gluetun-1  | ├── OS Alpine settings:
cambodia-gluetun-1  | |   ├── Process UID: 1000
cambodia-gluetun-1  | |   └── Process GID: 1000
cambodia-gluetun-1  | ├── Public IP settings:
cambodia-gluetun-1  | |   ├── Fetching: every 12h0m0s
cambodia-gluetun-1  | |   └── IP file path: /tmp/gluetun/ip
cambodia-gluetun-1  | └── Version settings:
cambodia-gluetun-1  |     └── Enabled: yes
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [routing] adding route for 0.0.0.0/0
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [firewall] setting allowed subnets...
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [routing] default route found: interface eth0, gateway 172.19.0.1, assigned IP 172.19.0.2 and family v4
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [dns] using plaintext DNS at address 1.1.1.1
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [http proxy] listening on :8888
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [http server] http server listening on [::]:8000
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [healthcheck] listening on 127.0.0.1:9999
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [firewall] allowing VPN connection...
cambodia-socks5-1   | 2024/03/14 03:52:53 Start listening proxy service on port 1080
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [wireguard] Using available kernelspace implementation
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [wireguard] Connecting to 195.80.149.244:1194
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
cambodia-gluetun-1  | 2024-03-14T03:52:53Z INFO [dns] downloading DNS over TLS cryptographic files
cambodia-gluetun-1  | 2024-03-14T03:52:54Z INFO [healthcheck] healthy!
cambodia-gluetun-1  | 2024-03-14T03:52:58Z INFO [dns] downloading hostnames and IP block lists
cambodia-gluetun-1  | 2024-03-14T03:53:05Z INFO [dns] init module 0: validator
cambodia-gluetun-1  | 2024-03-14T03:53:05Z INFO [dns] init module 1: iterator
cambodia-gluetun-1  | 2024-03-14T03:53:05Z INFO [dns] start of service (unbound 1.17.1).
cambodia-gluetun-1  | 2024-03-14T03:53:06Z INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
cambodia-gluetun-1  | 2024-03-14T03:53:06Z INFO [dns] ready
cambodia-gluetun-1  | 2024-03-14T03:53:07Z INFO [vpn] You are running 17 commits behind the most recent latest
cambodia-gluetun-1  | 2024-03-14T03:53:08Z INFO [ip getter] Public IP address is 195.80.149.244 (Cambodia, Phnom Penh, Phnom Penh)
cambodia-socks5-1   | 2024/03/14 03:53:22 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:53:29 [ERR] socks: Failed to handle request: readfrom tcp 172.19.0.2:1080->172.19.0.1:65350: splice: connection reset by peer
cambodia-socks5-1   | 2024/03/14 03:53:52 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:08 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:10 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:11 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:12 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:19 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:28 [INFO] socks: Connection from allowed IP address: 172.19.0.1
cambodia-socks5-1   | 2024/03/14 03:54:33 [ERR] socks: Failed to handle request: readfrom tcp 172.19.0.2:1080->172.19.0.1:43518: splice: connection reset by peer
^CGracefully stopping... (press Ctrl+C again to force)
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 29476:8888/tcp # HTTP proxy
      - 28454:1080 # 
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=100.126.116.88/32
      - WIREGUARD_PRESHARED_KEY=
      - SERVER_REGIONS=Cambodia
      - HTTPPROXY=on
  socks5:
    image: serjs/go-socks5-proxy
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
```

**Comment by Miku-programm** [comment] 2024-03-14 04:23
Running version latest built on 2024-03-07T12:32:25.391Z (commit 3254fc8)
I have the same problem with this version

**Comment by qdm12** [comment] 2024-03-20 07:15
If Gluetun is running fine and not unhealthy, then it's a problem with the socks docker image or socks client.

```
readfrom tcp 172.19.0.2:1080->172.19.0.1:65350: splice: connection reset by peer
```

https://github.com/armon/go-socks5/issues/34 seems similar. Perhaps try with another socks5 docker image? 🤔 

Closing this since I can't really help / this is a bit out of scope from Gluetun's standpoint. If it does the same problem with different socks5 programs, please re-create an issue (you can refer this one) and I'll look more into it. Thanks!

**Closed by qdm12** 2024-03-20 07:15 UTC

**Comment by qdm12** [comment] 2024-03-20 07:16
Actually, this looks like a duplicate of #2134 please subscribe to this issue instead. If this was broken with the latest image, I'll definitely look into it.
