### ISSUE TITLE
Bug: Control server returning empty public_ip

### ISSUE THREAD

**Issue by Davidmoffatt12** [qdm12/gluetun#1855] opened 2023-09-10 22:45 UTC
### Is this urgent?

No

### Host OS

Synology DSM 7.2

### CPU arch

None

### VPN service provider

Private Internet Access

### What are you using to run the container

Other

### What is the version of Gluetun

2023-08-24T09:29.123Z(commit 1ac031e)

### What's the problem 🤔

API is returning no data for a public IP.

API Error: Invalid data
URL: http://IP:8888/v1/publicip/ip
Response Data:
{"public_ip":""}

### Share your logs

```plain text
2023/09/10 19:43:03	stdout	2023-09-10T19:43:03-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55778 in 71.325µs
2023/09/10 19:42:49	stdout	2023-09-10T19:42:49-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55680 in 66.902µs
2023/09/10 19:42:29	stdout	2023-09-10T19:42:29-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55586 in 59.911µs
2023/09/10 19:41:22	stdout	2023-09-10T19:41:22-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55408 in 63.314µs
2023/09/10 19:40:51	stdout	2023-09-10T19:40:51-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55300 in 59.162µs
2023/09/10 19:39:50	stdout	2023-09-10T19:39:50-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55090 in 82.231µs
2023/09/10 19:39:39	stdout	2023-09-10T19:39:39-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:55022 in 73.738µs
2023/09/10 19:34:19	stdout	2023-09-10T19:34:19-03:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023/09/10 19:28:28	stdout	2023-09-10T19:28:28-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:53460 in 124.194µs
2023/09/10 19:27:26	stdout	2023-09-10T19:27:26-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:53226 in 69.957µs
2023/09/10 19:21:47	stdout	2023-09-10T19:21:47-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52134 in 83.835µs
2023/09/10 19:20:30	stdout	2023-09-10T19:20:30-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:51938 in 67.912µs
2023/09/10 19:15:21	stdout	2023-09-10T19:15:21-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:51346 in 70.721µs
2023/09/10 19:00:58	stdout	2023-09-10T19:00:58-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:49776 in 122.829µs
2023/09/10 19:00:30	stdout	2023-09-10T19:00:30-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:49654 in 595.409µs
2023/09/10 18:45:49	stdout	2023-09-10T18:45:49-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:48106 in 66.243µs
2023/09/10 18:45:32	stdout	2023-09-10T18:45:32-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:48008 in 63.066µs
2023/09/10 18:45:25	stdout	2023-09-10T18:45:25-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:47964 in 78.201µs
2023/09/10 18:41:46	stdout	2023-09-10T18:41:46-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:47536 in 78.588µs
2023/09/10 18:23:39	stdout	2023-09-10T18:23:39-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45614 in 65.485µs
2023/09/10 18:23:33	stdout	2023-09-10T18:23:33-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45556 in 67.743µs
2023/09/10 18:23:29	stdout	2023-09-10T18:23:29-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45510 in 59.932µs
2023/09/10 18:23:17	stdout	2023-09-10T18:23:17-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45436 in 59.2µs
2023/09/10 18:22:25	stdout	2023-09-10T18:22:25-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45274 in 81.294µs
2023/09/10 18:21:58	stdout	2023-09-10T18:21:58-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45174 in 63.575µs
2023/09/10 18:21:49	stdout	2023-09-10T18:21:49-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:45102 in 63.119µs
2023/09/10 18:20:31	stdout	2023-09-10T18:20:31-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44898 in 66.347µs
2023/09/10 18:20:26	stdout	2023-09-10T18:20:26-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44844 in 66.411µs
2023/09/10 18:20:15	stdout	2023-09-10T18:20:15-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44778 in 60.936µs
2023/09/10 18:20:15	stdout	2023-09-10T18:20:15-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44738 in 63.381µs
2023/09/10 18:17:46	stdout	2023-09-10T18:17:46-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44408 in 68.059µs
2023/09/10 18:17:42	stdout	2023-09-10T18:17:42-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:44356 in 71.145µs
2023/09/10 18:12:36	stdout	2023-09-10T18:12:36-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:43758 in 91.511µs
2023/09/10 18:12:32	stdout	2023-09-10T18:12:32-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:43704 in 108.639µs
2023/09/10 18:09:16	stdout	2023-09-10T18:09:16-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:43270 in 64.897µs
2023/09/10 18:08:54	stdout	2023-09-10T18:08:54-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:43178 in 102.803µs
2023/09/10 18:08:43	stdout	2023-09-10T18:08:43-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:43106 in 67.862µs
2023/09/10 18:00:13	stdout	2023-09-10T18:00:13-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:42140 in 67.097µs
2023/09/10 18:00:11	stdout	2023-09-10T18:00:11-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:42096 in 63.1µs
2023/09/10 17:58:51	stdout	2023-09-10T17:58:51-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:40860 in 64.739µs
2023/09/10 17:58:31	stdout	2023-09-10T17:58:31-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:40488 in 71.812µs
2023/09/10 17:57:00	stdout	2023-09-10T17:57:00-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:39396 in 70.201µs
2023/09/10 17:55:52	stdout	2023-09-10T17:55:52-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:39222 in 76.693µs
2023/09/10 17:53:53	stdout	2023-09-10T17:53:53-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:38952 in 70.472µs
2023/09/10 17:53:09	stdout	2023-09-10T17:53:09-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:38820 in 60.876µs
2023/09/10 17:52:59	stdout	2023-09-10T17:52:59-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:38748 in 64.958µs
2023/09/10 17:52:46	stdout	2023-09-10T17:52:46-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:38672 in 68.099µs
2023/09/10 17:48:56	stdout	2023-09-10T17:48:56-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:38180 in 67.997µs
2023/09/10 17:44:32	stdout	2023-09-10T17:44:32-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:37666 in 63.956µs
2023/09/10 17:44:21	stdout	2023-09-10T17:44:21-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:37576 in 73.655µs
2023/09/10 17:36:35	stdout	2023-09-10T17:36:35-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:36710 in 159.621µs
2023/09/10 17:35:41	stdout	2023-09-10T17:35:41-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:36510 in 62.687µs
2023/09/10 17:35:40	stdout	2023-09-10T17:35:40-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:36476 in 64.945µs
2023/09/10 17:34:55	stdout	2023-09-10T17:34:55-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:36286 in 68.233µs
2023/09/10 17:28:45	stdout	2023-09-10T17:28:45-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:34688 in 67.504µs
2023/09/10 17:14:02	stdout	2023-09-10T17:14:02-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:60484 in 68.025µs
2023/09/10 17:12:44	stdout	2023-09-10T17:12:44-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:60066 in 73.015µs
2023/09/10 17:12:05	stdout	2023-09-10T17:12:05-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:59934 in 67.881µs
2023/09/10 17:04:52	stdout	2023-09-10T17:04:52-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:53780 in 82.645µs
2023/09/10 17:00:49	stdout	2023-09-10T17:00:49-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:53202 in 253.097µs
2023/09/10 16:58:25	stdout	2023-09-10T16:58:25-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52784 in 67.891µs
2023/09/10 16:58:18	stdout	2023-09-10T16:58:18-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52726 in 64.057µs
2023/09/10 16:56:52	stdout	2023-09-10T16:56:52-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52446 in 64.415µs
2023/09/10 16:56:51	stdout	2023-09-10T16:56:51-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52416 in 61.864µs
2023/09/10 16:56:45	stdout	2023-09-10T16:56:45-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52352 in 83.625µs
2023/09/10 16:56:24	stdout	2023-09-10T16:56:24-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:52254 in 70.348µs
2023/09/10 16:50:33	stdout	2023-09-10T16:50:33-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:51442 in 67.852µs
2023/09/10 16:50:06	stdout	2023-09-10T16:50:06-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:51324 in 62.893µs
2023/09/10 16:49:51	stdout	2023-09-10T16:49:51-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:51234 in 70.918µs
2023/09/10 16:48:06	stdout	2023-09-10T16:48:06-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:50954 in 61.176µs
2023/09/10 16:47:58	stdout	2023-09-10T16:47:58-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:50876 in 69.652µs
2023/09/10 16:47:48	stdout	2023-09-10T16:47:48-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:50804 in 65.246µs
2023/09/10 16:47:17	stdout	2023-09-10T16:47:17-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:50682 in 59.55µs
2023/09/10 16:47:16	stdout	2023-09-10T16:47:16-03:00 INFO [http server] 200 GET /ip wrote 17B to 172.20.0.1:50618 in 72.094µs
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8090:8090 # port for qbittorrent
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1028
      - PGID=100
      - VPN_SERVICE_PROVIDER=private internet access
      - VPN_TYPE=openvpn
      - OPENVPN_USER=x
      - OPENVPN_PASSWORD=x
      - SERVER_REGIONS=x
      - TZ=x
      - VPN_PORT_FORWARDING=on
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16,x/24 #change this in line with your subnet see note on guide.
      - FIREWALL_VPN_INPUT_PORTS=38864 #uncomment this line and change the port as per the note on the guide
      - HTTP_CONTROL_SERVER_ADDRESS=:8888
      - HTTP_CONTROL_SERVER_LOG=on
    network_mode: synobridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
```

**Comment by madkatz01** [comment] 2023-09-15 16:14
I am also having the exact same issue, although the VPN is running perfectly. If I check ...8000/v1/openvpn/status I get the appropriate response {"status":"running"}. Hoping there is a fix!

**Comment by MikaelElkiaer** [comment] 2023-09-17 16:46
Duplicate of https://github.com/qdm12/gluetun/issues/1243

**Comment by elisimpson** [comment] 2023-09-19 12:17
Same here, NordVPN

**Comment by qdm12** [comment] 2023-09-24 14:56
This might be fixed with commit f96448947f4b335875cc4024102508378b80110f which is available on the latest image (built 2023-09-24 and onwards) and will be part of release v3.36.0

**Comment by Aiakio** [comment] 2023-09-26 12:49
Works now! Thank you!

**Comment by qdm12** [comment] 2023-09-26 13:56
Awesome thanks @Aiakio for confirming. Closing the issue 😉

**Closed by qdm12** 2023-09-26 13:56 UTC
Labels: 🚨 Urgent, 🗯️ Waiting for feedback

**Comment by Aiakio** [comment] 2023-10-08 15:29
@qdm12 After update `Running version latest built on 2023-10-07T13:26:08.155Z (commit 1c43a1d)` and getting an empty response again: `{"public_ip":""}`

**Comment by elisimpson** [comment] 2023-10-08 17:43
Any ETA for v3.36.0?

**Comment by Aiakio** [comment] 2023-10-18 18:53
> @qdm12 After update `Running version latest built on 2023-10-07T13:26:08.155Z (commit 1c43a1d)` getting an empty response again: `{"public_ip":""}`
> 
> Edit: Nevermind. After another restart and waiting for a couple of minutes, its working again.^^

@qdm12 Sorry to bother you again with this. I noticed, that sometimes it works and sometimes it doesn't.

Whenever it doesnt work, i get this in the logs: `WARN [ip getter] too many requests sent for this month from https://ipinfo.io/: 403 403 Forbidden; not retrying.`.

**Comment by HadryXx** [comment] 2023-11-06 11:29
In my case it's not working either, always try to send the query [400 POST] to the ip X.X.X.2 and my ip is an X.X.X.51

**Comment by crispybegs** [comment] 2024-06-30 18:36
I'm having this issue after never having it before:

Homepage widget reads:

```
API Error: Invalid data
URL: http://192.168.1.63:8009/v1/publicip/ip
Response Data:
{"public_ip":""}
```

My Gluetun compose is:

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /home/crispy/docker/gluetun2/config:/config
    ports:
      - "8009:8000/tcp"
      - "6081:6881"
      - "6081:6881/udp"
      - "6011:6011"
      
    environment:
      # Wireguard
     _etc etc_
```
My homepage config is:

```
    - Gluetun:
         icon: gluetun.png
         widget:
          type: gluetun
          fields: ["public_ip", "region", "country"]
          url: http://192.168.1.63:8009
```
Any ideas I can try?

**Comment by rdmch** [comment] 2024-11-12 07:43
Same issue here... Once I have 
2024-11-11T23:59:53+01:00 ERROR [vpn] getting public IP address information: fetching information: Get "[https://ipinfo.io/":](https://%3Cmark%3Eipinfo%3C/mark%3E.io/%22:) dial tcp: lookup ipinfo.io on 1.1.1.1:53: read udp 10.2.0.2:51596->1.1.1.1:53: i/o timeout
Then I cannot get any new public_ip filled in the API.
I have to reboot the VPN

**Comment by ShaddyDC** [comment] 2025-01-24 23:39
I also ran into the issue although without any such errors. What solved it for me was updating from the latest release 3.40.0 to master

Edit: Still seems to happen sometimes. Might be https://github.com/qdm12/gluetun/issues/2848
