### ISSUE TITLE
Bug: PIA No Server Found

### ISSUE THREAD

**Issue by stumpylog** [qdm12/gluetun#322] opened 2020-12-29 17:23 UTC
**Host OS** (approximate answer is fine too): Ubuntu 20.04.1

**Is this urgent?**: No

**What VPN provider are you using**: PIA

**What are you using to run your container?**: Docker Compose

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2020-12-29T02:56:32Z (commit 8d5f2fe)
```

**What's the problem** 🤔

The container is reporting OpenVPN errors for every PIA region I have tried (4 at current count).  Using the v3.8.1 tag does not exhibit this issue.

**Share your logs...**

```log
2020-12-29T09:22:18.766-0800	INFO	openvpn configurator: checking for device /dev/net/tun,
2020-12-29T09:22:18.788-0800	ERROR	openvpn: no server found for region ca vancouver,
2020-12-29T09:22:18.788-0800	WARN	openvpn: loop exited

or 


2020-12-29T09:24:45.527-0800	ERROR	openvpn: no server found for region de frankfurt

```

**Comment by stumpylog** [comment] 2020-12-29 17:27
I forcibly removed `servers.json` and the region is working again.  Maybe this is a user error.

**Comment by qdm12** [comment] 2020-12-29 17:53
Unlikely a user error, more of a MY FAULT error haha!

This is a duplicate of #321

I am still investigating, thanks for creating the issue! I'll close this one for easier tracking.

**Closed by qdm12** 2020-12-29 17:53 UTC

**Comment by qdm12** [comment] 2020-12-29 17:54
Also is this happening to you on v3.9.0? Or is this just on `:latest`? I'd expect it to be on `:latest` 🤔

**Comment by stumpylog** [comment] 2020-12-29 17:58
This was on :latest. I live dangerously on it.

**Comment by qdm12** [comment] 2020-12-29 17:59
That's the spirit 😄
