### ISSUE TITLE
Port forwarding question/issue

### ISSUE THREAD

**Issue by wfg** [qdm12/gluetun#53] opened 2019-10-10 02:53 UTC
When I set the `PORT_FORWARDING` flag to `on`, I get a forwarded port as I would expect to. However, it seems that I'm not able to hit that port from outside the network. My steps are below:

1. Spin up the container `pia` with port forwarding enabled.
2. Grab the forwarded port (36507 in this case).
3. Spin up another container that uses `--network=container:pia`, and run `curl -sd port="36507" https://canyouseeme.org | grep -o 'Success\|Error'` in that container.
4. See "Error".

Am I missing something here? It seems like the port would also have to be exposed on the `pia` container after creating the container and running the script to actually _get_ the port. I hope this isn't the case, and I'm just overlooking or oversimplifying something.

Thanks!

**Comment by qdm12** [comment] 2019-10-15 01:36
Hi there, thanks for the detailed explanation.

Disclaimer, I don't really use port forwarding so this might not be 100% exact :smile:

The firewall of the container is actually changed when port forwarding is on, see these [2 lines](https://github.com/qdm12/private-internet-access-docker/blob/master/portforward.sh#L53).

What you could do, is:
1. Get your VPN public IP address

    ```sh
    docker exec -it pia wget -qO- https://ipinfo.io
    ```

1. Spin this port checker container I made, replacing the `9999` by your forwarded port

    ```sh
    docker run -it --rm --network=container:pia -e PORT=9999 qmcgaw/port-checker
    ```

1. In your browser, check at http://<pia vpn ip>:<forwarded port>

I think a few people are using port forwarding (even some made PRs) so it must be working :)

**Comment by yacht7** [comment] 2019-11-09 15:24
Right, I was referring to not being able to `-p <forwarded_port>:<forwarded_port>` when running the pia container as that is determined after container start. Without that, wouldn't the container be unreachable on the forwarded port from outside of the local network?

This is definitely not your problem as there's no way, to my knowledge, to get a forwarded port without an existing connection (which requires a container to have already been created).

Any thoughts on this? Am I just being thick?

**Comment by qdm12** [comment] 2019-11-12 10:59
You could technically redirect a port to another I think using iptables once you receive the port forwarded, I'll look into that.

**Comment by yacht7** [comment] 2019-11-12 14:47
Now that would be fancy. Have a port published on container startup (like `-p 35350:35350` for example) that shouldn't ever have to change, and then after grabbing a forwarded port from PIA, redirect the "dynamic" port from PIA to the published "static" port. Is this what you're thinking?

**Comment by qdm12** [comment] 2019-11-12 19:47
Yep. It seems like a one liner iptables too, so I'll do that soon :)

**Comment by groenator** [comment] 2019-11-13 18:35
I hope I understood correctly, if iptables will somehow redirect the traffic from the dynamic port to the static port that would great. This is need it for tools like deluge etc where you have to manually update the configuration with the new port.

Please share the instructions after implementing this small change.

Thank you!

**Comment by qdm12** [comment] 2019-11-14 00:41
Hi @groenator and @yacht7  and others,

I have found what to do, but would you mind trying it out in the current container you have to see if it works?

Run the following (i assume your container is named `pia`)

```sh
docker exec -it pia /bin/sh
# get your forwarded port, say 6901 for example
port=`cat $PORT_FORWARDING_STATUS_FILE`
iptables -t nat -I PREROUTING -d 127.0.0.1 -p tcp --dport 8000 -j REDIRECT --to-ports $port
iptables -t nat -I PREROUTING -d 127.0.0.1 -p udp --dport 8000 -j REDIRECT --to-ports $port
exit
```

That basically redirects port `6901` ($port) to port 8000 with protocols TCP and UDP.
Please then try it is accessible through port 8000 and report back? 😃 

Sorry I haven't used port forwarding really, and I don't want to change all my infrastructure to test 😆

**Comment by yacht7** [comment] 2019-11-14 01:35
I did a little reading myself, and I believe your ports are backwards. I read that rule as "packets coming from any address to local on port $static_port should be sent to $forwarded_port", when I think we want $forwarded_port to go to $static_port.

Either way, I tried both ways, and neither work in my setup. I'm not sure if it's an issue on my end or we're missing something with the iptables rule.

**However**, I was able to resolve my issue for myself. With no extra iptables rules in place (restarted `pia`), I waited for the `pia` container to come up completely. I captured the forwarded port, then stuck that port in as my torrent client peer port and started my torrent client container. This caused me to be connectable on `$pia_ip:$forwarded_port`. This solution definitely isn't as clean as an iptables rule would be, but there's some complicated routing going on here, and I think I cut some of it out.

**Comment by qdm12** [comment] 2019-11-14 01:51
Yes -silly me-, you indeed want the outside world (so on the VPN side) to connect to you on the same port i.e. `8000` right? That's probably impossible 😢 

Or are you only interested in receiving data coming from PIA's random port on the another port `8000`? Sorry for being confused, the more I write the more I confuse myself haha.

In the second case, it's likely possible, we may have to specify the tun interface IP address in the iptables for it to work.

**Comment by yacht7** [comment] 2019-11-14 02:05
I definitely understand the confusion. Just as I thought I was wrapping my head around it, I got it working by accident and have no idea why it works.

I guess it would be helpful for everyone if I elaborated on my use case. Basically I'm looking to:
- use `pia` to get a VPN IP and port forwarded to that IP, and then
- use `transmission` as a torrent client that is [connectable](https://superuser.com/a/1053429) via the IP:port combination from `pia`.

My docker-compose file is set up properly so `transmission` uses `pia` for networking, and it's all fine there. I *thought* I would have to have a published port for the connectivity requirement in bullet 2, but after working on it a little bit, that doesn't actually seem to be the case. At this point, I'm not entirely sure my initial ask is possible (iptables rules stuff). Anyway, is the situation clearer? Let me know if I should go into more detail on any part.

**Comment by qdm12** [comment] 2019-11-14 13:37
So when you configure the port on Transmission, I think that is for outside peers so there is no way around that I believe as PIA server is the inbound traffic entrypoint. Or am I wrong?

If so, what you could do is write a small shell script with `sed` to read the forwarded port file and replace the port at startup in your transmission config. I can help with that if you want.

**Comment by yacht7** [comment] 2019-11-14 13:55
I believe that is correct. I guess my ignorance is showing because I didn't transmission running in container using another container as a VPN connection would be able to *just work* by setting the port in the transmission config.

Using `sed` to change the port would work if it's done in the proper spot in the chain of startup events. Transmission is very picky with it's config file, so you aren't able to change the config file and have those changes persist while the container is running (or at least `transmission-daemon`). I have the linuxserver/docker-transmission repo cloned. I'm going to poke around to see where that sort of modification should go.

**Comment by qdm12** [comment] 2019-11-15 03:07
You can probably change the entrypoint to run your custom script with `sed` and then the normal entrypoint. Definitely not the cleanest but it should work. I'll have a look this weekend.

**Comment by yacht7** [comment] 2019-11-16 16:08
I think I've it figured out. Linuxserver's Transmission image makes it simple to run custom scripts on container start. I've come up with this:
```bash
# update forwarded port using port from pia container
while [ ! -f '/config/forwarded_port' ]; do
    sleep 5
done;

sed -i "/\"peer-port\"/c\    \"peer-port\": $(cat /config/forwarded_port)," /config/settings.json
```
I haven't tested it entirely, only the `sed` bit, but I'm confident it will work. If not, it can't be far off.

**Comment by Raph521** [comment] 2019-12-07 20:18
Interesting @yacht7!

I gave that a shot and it works pretty well, thanks for that!

One thing I noticed is that if the Transmission container starts up and finds that forwarded_port file from a previous run of the PIA container, it'll use that old port.  Would be nice if there was a way to clean up the forwarded_port file when the PIA container exits?

**Comment by qdm12** [comment] 2019-12-07 22:25
Out of curiosity, why is your PIA exiting? Disconnections?

The PIA forwarded port file can be deleted once PIA exits but I don't think it would help as it's overwritten by another port anyway when PIA restarts.

There would need to have a shell as a subprocess watch forwarded_port and sed on change in the transmission container. Check with something like

```sh
./watch_forwarded_port.sh &
```

to run it as another background process where watch_forwarded_port.sh would be like (typing from mobile) 

```sh
while [ 1]; do
   inotifywait -m /config/forwarded_port
   sed -i "/\"peer-port\"/c\    \"peer-port\": $(cat /config/forwarded_port)," /config/settings.json
    # then reload the config with transmission somehow
done
```

**Comment by yacht7** [comment] 2019-12-08 00:54
@Raph521 When I came up with that, I faced the same dilemma whenever PIA went down or wasn't started with Transmission. I realized that would be a pretty uncommon scenario and there's no obvious way to handle that, so I just left it alone.

**Comment by Raph521** [comment] 2019-12-08 21:40
I rarely, if ever, have issues with PIA exiting on its own.

The only time the container goes down is when I bring it down myself for some reason or another.  I was just curious for the sake of automating things for those cases, but obviously not urgent.

Once again, thanks for all the hard work you've put into this @qdm12 - much appreciated!

**Comment by dantidote** [comment] 2019-12-17 19:46
Am I doing something wrong?  I get connection timeouts when trying to access services running on the forwarded port.  Any idea?

I'm starting the pia container with:
```
docker run -d -i --device=/dev/net/tun \
--cap-add=NET_ADMIN \
-e REGION="CA Toronto" \ 
-e PASSWORD=<pwd> \
-e USER=<user>  \
-e PORT_FORWARDING=on \
--name pia \
qmcgaw/private-internet-access
```

Log output showing successful port forward:
```
[INFO] Reading forwarded port
 * Generating client ID...
 * Obtaining forward port from PIA server...
 * Parsing JSON response...
 * Writing forwarded port to file...
 * Detecting current VPN IP address...
 * Forwarded port accessible at 172.98.67.81:21889
 * Detecting target VPN interface...
 * Accepting input traffic through tun0 to port 21889...
[INFO] Port forwarded successfully
```

I try running a service on this port:
```
docker run -it --rm --network=container:pia -e PORT=21889 qmcgaw/port-checker
#################################
######### Port Checker ##########
######## by Quentin McGaw #######
######## Give some ❤ at #########
# github.com/qdm12/port-checker #
#################################

{"level":"Info","message":"Server listening on 0.0.0.0:21889","time":"2019-12-17T19:33:03.579629327Z","node":0}
```

But attempts to connect to it timeout:
```
telnet 172.98.67.81 21889
Trying 172.98.67.81...
telnet: Unable to connect to remote host: Connection timed out
```

**Comment by qdm12** [comment] 2019-12-17 20:50
Well to be honest, I also tried port forwarding the exact same way you did and it doesn't work for me either. I don't really have a use for port forwarding so it's not a big deal for me. Apparently others have it working at least for their torrenting containers. If anyone could enlighten us that would be great!

**Comment by yacht7** [comment] 2019-12-18 14:55
@dantidote That looks like it should be working. The only thing I'm not sure about is the port-checker (no offense to @qdm12, I just don't know what all that Go is doing 😄). Can you try this:

1. Run `docker run --network=container:pia alpine nc -vv -l -p $FORWARDED_PORT 0.0.0.0`. This will look like it's hanging. That's how it should be--it's listening for connections on the port you specified.
2. In another terminal, run `nc -vv $PIA_IP $FORWARDED_PORT`. You should see it succeed an "open" somewhere in the output.

**Comment by qdm12** [comment] 2019-12-18 15:01
Thanks so much @yacht7 I will try that out;

my go thingy runs a simple HTTP server on a port. It seems to work with/without docker port mapping but I am deeply curious why it would not with PIA :laughing:

**Comment by yacht7** [comment] 2019-12-18 15:23
The only thing I can think of is it's not binding to the correct IP. I had to specify `0.0.0.0` in my `nc` example for it to work.

**Comment by qdm12** [comment] 2019-12-18 17:33
It does bind to `0.0.0.0`; anyway that's out of the topic :disappointed: I'll test it with nc and add it to the doc for now. Anyway I'm still rewriting the shell scripting in Go so I'll have to figure it out to implement a port forwarding Docker healthcheck :+1: (check it's reachable)

**Comment by groenator** [comment] 2019-12-22 19:58
I configured rutorrent with the PIA image and works as expected. I no longer have to assign the port manually and restart rutorrent.

**Comment by qdm12** [comment] 2020-02-04 02:14
The Go rewrite Docker image is now out in 'beta' at `qmcgaw/private-internet-access:go`.

- The documentation is [here](https://github.com/qdm12/private-internet-access-docker/tree/go#private-internet-access-client)
- It should work with the same settings as before
- Feel free to comment here or on the [Slack channel](https://join.slack.com/t/qdm12/shared_invite/enQtOTE0NjcxNTM1ODc5LTYyZmVlOTM3MGI4ZWU0YmJkMjUxNmQ4ODQ2OTAwYzMxMTlhY2Q1MWQyOWUyNjc2ODliNjFjMDUxNWNmNzk5MDk)
- Note that it's lacking port forwarding for now, I will do it in the coming few days
- It might have bugs as it's not totally unit tested yet

**Comment by Stonedestroyer** [comment] 2020-04-12 17:04
I see I have to assign port definitions when I boot PIA but that's impossible as I haven't been assigned the port yet, I can replace the port on the other container with the port PIA assigns me but I can't change the port rules later on PIA container, how do I solve this?

**Comment by qdm12** [comment] 2020-04-12 20:09
I'm not entirely sure what you mean. You can't specify the port you want to be forwarded to you. Please elaborate? Feel free also to create another issue if it's another problem.

By the way, there is a recent update now writing your VPN ip address to `/ip` if that can help for automating port forwarding with linked containers.

**Comment by yacht7** [comment] 2020-04-12 20:30
@Stonedestroyer you shouldn't need to publish the PIA-forwarded port on your container.

**Comment by Stonedestroyer** [comment] 2020-04-12 21:15
If I don't I can't join externally and joining through VPN IP and port doesn't work locally for me, only if I'm using a VPN.

**Comment by qdm12** [comment] 2020-05-26 23:16
Hello all,

Except for groenator, does port forwarding still work for you on the latest image?

Also, I'd like to close this issue but before doing so, can we agree on a way to test port forwarding? I was thinking:

```sh
# With your vpn container running and named as 'pia', with port forwarding enabled
PORT=$(docker exec pia cat /forwarded_port)
IP=$(docker exec pia cat /ip)
docker run -d --name listener --network=container:pia alpine:3.11 nc -l $PORT 0.0.0.0
docker run -it --rm alpine:3.11 wget -O- http://$IP:$PORT 
docker rm -f listener
```

You should get as last line:

```
wget: error getting response: Invalid argument
```

Didn't test yet, feel free to try it 😉

**Comment by groenator** [comment] 2020-05-27 10:24
Hi,

I will test it out tonight!

Thank you

**Comment by groenator** [comment] 2020-05-27 10:33
Hi,

I created a small screenshot and explained exactly what the issue is. As
you can see from the screenshot, rutorrent is complaining that the status
of the port is unknown, even though the port is configured to be used by
rutorrent.

**Comment by groenator** [comment] 2020-05-27 10:38
I forgot to mention that the port configured in rutorrent is the same port
that was forward by the PIA image on boot.  I have a small shell script
that reads the port from /forwarded_port path and updates the rtorrent.rc
config with the new port. Every time I restart the rutorrent + pia
containers it gets a new port and a new configuration.

I am using this setup for a while and it worked well until a few weeks ago
when I started to see this new message about unknown status. My assumption
(I might be wrong) it has to do something with the iptables configuration.

Thank you!

**Comment by qdm12** [comment] 2020-05-27 10:45
Please try the commands above first to rule out an eventual problem with rutorrent.

**Comment by qdm12** [comment] 2020-05-27 11:19
I tried the commands above (with region romania), oddly listening with `nc` still shows the port closed on [yougetsignal.com/tools/open-ports/](https://www.yougetsignal.com/tools/open-ports/).

Using `docker run -it --rm -e LISTENING_PORT=57666 --network=container:pia qmcgaw/port-checker` however shows the port as opened on [yougetsignal.com/tools/open-ports/](https://www.yougetsignal.com/tools/open-ports/). I however can't access the http server with my browser at http://<ip>:<port>, very odd.

Does anyone has  a reliable method to test port forwarding? I'm running out of ideas 😢

**Comment by Stonedestroyer** [comment] 2020-05-27 11:22
Portforwarding works for me but only if I am on a different network. Can't seem to connect local > PIA port. Rather I need to be on PIA on my client so I think it's a NAT question.

**Comment by qdm12** [comment] 2020-05-27 11:35
@Stonedestroyer  I'm not sure if we're talking about the same port forwarding, what are you trying to achieve? The issue is about port forwarding on the vpn server side to allow outside machines to connect to the pia container through the vpn ip address.

For the others, that seems reliable to test port forwarding works, although http seems filtered out still:

1. We assume your container is running and named `pia`, with port forwarding enabled.
1. Run the following lines

    ```
    PORT=$(docker exec pia cat /forwarded_port)
    echo "Forwarded port: $PORT"
    IP=$(docker exec pia cat /ip)
    echo "VPN ip address: $IP"
    docker run -it --rm --network=container:pia alpine:3.11 /bin/sh -c "apk add nmap-ncat && ncat -l $PORT && echo success"
    ```

1. Now go with your browser to [yougetsignal.com/tools/open-ports](https://www.yougetsignal.com/tools/open-ports/) and check using the ip address and forwarded port mentioned above.
1. Your terminal should stop blocking and show `success`

If someone has  a better way to check, feel free to comment 😉

**Comment by averri** [comment] 2020-12-07 09:16
I have tried the following procedure:

> @Stonedestroyer I'm not sure if we're talking about the same port forwarding, what are you trying to achieve? The issue is about port forwarding on the vpn server side to allow outside machines to connect to the pia container through the vpn ip address.
> 
> For the others, that seems reliable to test port forwarding works, although http seems filtered out still:
> 
> 1. We assume your container is running and named `pia`, with port forwarding enabled.
> 2. Run the following lines
>    ```
>    PORT=$(docker exec pia cat /forwarded_port)
>    echo "Forwarded port: $PORT"
>    IP=$(docker exec pia cat /ip)
>    echo "VPN ip address: $IP"
>    docker run -it --rm --network=container:pia alpine:3.11 /bin/sh -c "apk add nmap-ncat && ncat -l $PORT && echo success"
>    ```
> 3. Now go with your browser to [yougetsignal.com/tools/open-ports](https://www.yougetsignal.com/tools/open-ports/) and check using the ip address and forwarded port mentioned above.
> 4. Your terminal should stop blocking and show `success`
> 
> If someone has a better way to check, feel free to comment

... but it didn't work. The forwarded port remains closed in the VPN server.

**Comment by qdm12** [comment] 2021-02-26 00:39
You can now reliably test your port forwarding following the [Wiki documentation](https://github.com/qdm12/gluetun/wiki/Port-forwarding#test-it) (I tested it with Mullvad). If that can help anyone trying to figure out if the port is forwarding or not 😉

**Closed** 2021-02-26 00:40 UTC

**Comment by qdm12** [comment] 2023-11-10 17:23
Hello all, just so you know, you can now configure a static port to redirect the data sent through the VPN forwarded port from commit 61229118653185e6d94a7d2ca6d3aafff9c92bdf (latest image and future release v3.37). Under the hood it uses iptables' `PREROUTING` + `REDIRECT` instructions. Just set to `VPN_PORT_FORWARDING_LISTENING_PORT` to the static port you want. Not really tested, so please open an issue if it doesn't work as expected 😉

**Comment by qdm12** [comment] 2023-11-23 08:14
Just FYI, the previous commit didn't build (linting error prevented it), commit 7c98f54cc1608de89da0b4131c4d4b1b49ab9ebd should now build 😉
