### ISSUE TITLE
Bug: panic: unaligned 64-bit atomic operation on Raspberry pi 4 and debian

### ISSUE THREAD

**Issue by lucassardois** [qdm12/gluetun#1520] opened 2023-04-15 10:39 UTC
### Is this urgent?

None

### Host OS

Raspberry Pi OS (based on debian bullseye)

### CPU arch

None

### VPN service provider

AirVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2023-04-12T12:34:51.538Z (commit d4f8eea)

### What's the problem 🤔

When following the wiki and running with `docker compose up` I get the error `panic: unaligned 64-bit atomic operation`. Note that if I follow the same guide for OpenVPN it works correctly.

### Share your logs

```plain text
gluetun  | ========================================
gluetun  | ========================================
gluetun  | =============== gluetun ================
gluetun  | ========================================
gluetun  | =========== Made with ❤️ by ============
gluetun  | ======= https://github.com/qdm12 =======
gluetun  | ========================================
gluetun  | ========================================
gluetun  |
gluetun  | Running version latest built on 2023-04-12T12:34:51.538Z (commit d4f8eea)
gluetun  |
gluetun  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun  | 💻 Email? quentin.mcgaw@gmail.com
gluetun  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun  | 2023-04-15T10:25:11Z INFO [routing] default route found: interface eth0, gateway 172.27.0.1 and assigned IP 172.27.0.2
gluetun  | 2023-04-15T10:25:11Z INFO [routing] local ethernet link found: eth0
gluetun  | 2023-04-15T10:25:11Z INFO [routing] local ipnet found: 172.27.0.0/16
gluetun  | 2023-04-15T10:25:11Z INFO [firewall] enabling...
gluetun  | 2023-04-15T10:25:11Z INFO [firewall] enabled successfully
gluetun  | 2023-04-15T10:25:12Z INFO [storage] merging by most recent 13064 hardcoded servers and 13064 servers read from /gluetun/servers.json
gluetun  | 2023-04-15T10:25:12Z INFO Alpine version: 3.17.3
gluetun  | 2023-04-15T10:25:12Z INFO OpenVPN 2.4 version: 2.4.12
gluetun  | 2023-04-15T10:25:12Z INFO OpenVPN 2.5 version: 2.5.8
gluetun  | 2023-04-15T10:25:12Z INFO Unbound version: 1.17.1
gluetun  | 2023-04-15T10:25:12Z INFO IPtables version: v1.8.8
gluetun  | 2023-04-15T10:25:12Z INFO Settings summary:
gluetun  | ├── VPN settings:
gluetun  | |   ├── VPN provider settings:
gluetun  | |   |   ├── Name: mullvad
gluetun  | |   |   └── Server selection settings:
gluetun  | |   |       ├── VPN type: wireguard
gluetun  | |   |       └── Wireguard selection settings:
gluetun  | |   └── Wireguard settings:
gluetun  | |       ├── Private key: eP...kE=
gluetun  | |       ├── Interface addresses:
gluetun  | |       |   └── 10.64.156.152/32
gluetun  | |       └── Network interface: tun0
gluetun  | ├── DNS settings:
gluetun  | |   ├── DNS server address to use: 127.0.0.1
gluetun  | |   ├── Keep existing nameserver(s): no
gluetun  | |   └── DNS over TLS settings:
gluetun  | |       ├── Enabled: yes
gluetun  | |       ├── Update period: every 24h0m0s
gluetun  | |       ├── Unbound settings:
gluetun  | |       |   ├── Authoritative servers:
gluetun  | |       |   |   └── cloudflare
gluetun  | |       |   ├── Caching: yes
gluetun  | |       |   ├── IPv6: no
gluetun  | |       |   ├── Verbosity level: 1
gluetun  | |       |   ├── Verbosity details level: 0
gluetun  | |       |   ├── Validation log level: 0
gluetun  | |       |   ├── System user: root
gluetun  | |       |   └── Allowed networks:
gluetun  | |       |       ├── 0.0.0.0/0
gluetun  | |       |       └── ::/0
gluetun  | |       └── DNS filtering settings:
gluetun  | |           ├── Block malicious: yes
gluetun  | |           ├── Block ads: no
gluetun  | |           ├── Block surveillance: no
gluetun  | |           └── Blocked IP networks:
gluetun  | |               ├── 127.0.0.1/8
gluetun  | |               ├── 10.0.0.0/8
gluetun  | |               ├── 172.16.0.0/12
gluetun  | |               ├── 192.168.0.0/16
gluetun  | |               ├── 169.254.0.0/16
gluetun  | |               ├── ::1/128
gluetun  | |               ├── fc00::/7
gluetun  | |               ├── fe80::/10
gluetun  | |               ├── ::ffff:7f00:1/104
gluetun  | |               ├── ::ffff:a00:0/104
gluetun  | |               ├── ::ffff:a9fe:0/112
gluetun  | |               ├── ::ffff:ac10:0/108
gluetun  | |               └── ::ffff:c0a8:0/112
gluetun  | ├── Firewall settings:
gluetun  | |   ├── Enabled: yes
gluetun  | |   └── VPN input ports:
gluetun  | |       └── 55265
gluetun  | ├── Log settings:
gluetun  | |   └── Log level: INFO
gluetun  | ├── Health settings:
gluetun  | |   ├── Server listening address: 127.0.0.1:9999
gluetun  | |   ├── Target address: cloudflare.com:443
gluetun  | |   ├── Read header timeout: 100ms
gluetun  | |   ├── Read timeout: 500ms
gluetun  | |   └── VPN wait durations:
gluetun  | |       ├── Initial duration: 6s
gluetun  | |       └── Additional duration: 5s
gluetun  | ├── Shadowsocks server settings:
gluetun  | |   └── Enabled: no
gluetun  | ├── HTTP proxy settings:
gluetun  | |   └── Enabled: no
gluetun  | ├── Control server settings:
gluetun  | |   ├── Listening address: :8000
gluetun  | |   └── Logging: yes
gluetun  | ├── OS Alpine settings:
gluetun  | |   ├── Process UID: 1000
gluetun  | |   └── Process GID: 1000
gluetun  | ├── Public IP settings:
gluetun  | |   ├── Fetching: every 12h0m0s
gluetun  | |   └── IP file path: /tmp/gluetun/ip
gluetun  | └── Version settings:
gluetun  |     └── Enabled: yes
gluetun  | 2023-04-15T10:25:12Z INFO [routing] default route found: interface eth0, gateway 172.27.0.1 and assigned IP 172.27.0.2
gluetun  | 2023-04-15T10:25:12Z INFO [routing] adding route for 0.0.0.0/0
gluetun  | 2023-04-15T10:25:12Z INFO [firewall] setting allowed subnets...
gluetun  | 2023-04-15T10:25:12Z INFO [routing] default route found: interface eth0, gateway 172.27.0.1 and assigned IP 172.27.0.2
gluetun  | 2023-04-15T10:25:12Z INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun  | 2023-04-15T10:25:12Z INFO [dns over tls] using plaintext DNS at address 1.1.1.1
gluetun  | 2023-04-15T10:25:12Z INFO [http server] http server listening on [::]:8000
gluetun  | 2023-04-15T10:25:12Z INFO [healthcheck] listening on 127.0.0.1:9999
gluetun  | 2023-04-15T10:25:13Z INFO [firewall] allowing VPN connection...
gluetun  | 2023-04-15T10:25:13Z INFO [wireguard] Using userspace implementation since Kernel support does not exist
gluetun  | 2023-04-15T10:25:13Z INFO [wireguard] Connecting to 82.103.140.213:51820
gluetun  | 2023-04-15T10:25:13Z INFO [wireguard] Wireguard is up
gluetun  | 2023-04-15T10:25:13Z INFO [firewall] setting allowed input port 55265 through interface tun0...
gluetun  | 2023-04-15T10:25:13Z INFO [dns over tls] downloading DNS over TLS cryptographic files
gluetun  | panic: unaligned 64-bit atomic operation
gluetun  |
gluetun  | goroutine 60 [running]:
gluetun  | runtime/internal/atomic.panicUnaligned()
gluetun  |      runtime/internal/atomic/unaligned.go:8 +0x24
gluetun  | runtime/internal/atomic.Load64(0x1c80c14)
gluetun  |      runtime/internal/atomic/atomic_arm.s:280 +0x14
gluetun  | golang.zx2c4.com/wireguard/device.(*Device).IsUnderLoad(0x1c80b40)
gluetun  |      golang.zx2c4.com/wireguard@v0.0.0-20220703234212-c31a7b1ab478/device/device.go:226 +0x118
gluetun  | golang.zx2c4.com/wireguard/device.(*Device).RoutineHandshake(0x1c80b40, 0x1)
gluetun  |      golang.zx2c4.com/wireguard@v0.0.0-20220703234212-c31a7b1ab478/device/receive.go:291 +0x44c
gluetun  | created by golang.zx2c4.com/wireguard/device.NewDevice
gluetun  |      golang.zx2c4.com/wireguard@v0.0.0-20220703234212-c31a7b1ab478/device/device.go:316 +0x2e0
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<private_key>
      - WIREGUARD_ADDRESSES=<adress>
```

**Comment by bnhf** [comment] 2023-04-15 14:04
@lucassardois 

Is it possible you're running a 32-bit version of the Raspberry Pi OS? I have an RPi4 test rig very similar to yours and just tried the latest Gluetun using Wireguard and Mullvad -- with no such error:

```
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================
Running version latest built on 2023-04-12T12:34:51.538Z (commit d4f8eea)
🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-04-15T07:49:07-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1 and assigned IP 172.20.0.2
2023-04-15T07:49:07-06:00 INFO [routing] local ethernet link found: eth0
2023-04-15T07:49:07-06:00 INFO [routing] local ipnet found: 172.20.0.0/16
2023-04-15T07:49:07-06:00 INFO [firewall] enabling...
2023-04-15T07:49:07-06:00 INFO [firewall] enabled successfully
2023-04-15T07:49:07-06:00 INFO [storage] creating /gluetun/servers.json with 13064 hardcoded servers
2023-04-15T07:49:08-06:00 INFO Alpine version: 3.17.3
2023-04-15T07:49:08-06:00 INFO OpenVPN 2.4 version: 2.4.12
2023-04-15T07:49:08-06:00 INFO OpenVPN 2.5 version: 2.5.8
2023-04-15T07:49:08-06:00 INFO Unbound version: 1.17.1
2023-04-15T07:49:08-06:00 INFO IPtables version: v1.8.8
2023-04-15T07:49:08-06:00 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: mullvad
|   |   └── Server selection settings:
|   |       ├── VPN type: wireguard
|   |       ├── Countries: canada
|   |       └── Wireguard selection settings:
|   └── Wireguard settings:
|       ├── Private key: 8H...lM=
|       ├── Interface addresses:
|       |   └── 10.65.100.105/32
|       └── Network interface: tun0
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: US/Mountain
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2023-04-15T07:49:08-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1 and assigned IP 172.20.0.2
2023-04-15T07:49:08-06:00 INFO [routing] adding route for 0.0.0.0/0
2023-04-15T07:49:08-06:00 INFO [firewall] setting allowed subnets...
2023-04-15T07:49:08-06:00 INFO [routing] default route found: interface eth0, gateway 172.20.0.1 and assigned IP 172.20.0.2
2023-04-15T07:49:08-06:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2023-04-15T07:49:08-06:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
2023-04-15T07:49:08-06:00 INFO [http server] http server listening on [::]:8000
2023-04-15T07:49:08-06:00 INFO [healthcheck] listening on 127.0.0.1:9999
2023-04-15T07:49:08-06:00 INFO [firewall] allowing VPN connection...
2023-04-15T07:49:08-06:00 INFO [wireguard] Using userspace implementation since Kernel support does not exist
2023-04-15T07:49:08-06:00 INFO [wireguard] Connecting to 188.241.176.194:51820
2023-04-15T07:49:08-06:00 INFO [wireguard] Wireguard is up
2023-04-15T07:49:08-06:00 INFO [dns over tls] downloading DNS over TLS cryptographic files
2023-04-15T07:49:09-06:00 INFO [healthcheck] healthy!
2023-04-15T07:49:09-06:00 INFO [dns over tls] downloading hostnames and IP block lists
2023-04-15T07:49:17-06:00 INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
2023-04-15T07:49:23-06:00 INFO [dns over tls] init module 0: validator
2023-04-15T07:49:23-06:00 INFO [dns over tls] init module 1: iterator
2023-04-15T07:49:23-06:00 INFO [dns over tls] start of service (unbound 1.17.1).
2023-04-15T07:49:23-06:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2023-04-15T07:49:23-06:00 INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
2023-04-15T07:49:24-06:00 INFO [healthcheck] healthy!
2023-04-15T07:49:24-06:00 INFO [dns over tls] ready
2023-04-15T07:49:24-06:00 INFO [vpn] You are running 2 commits behind the most recent latest
2023-04-15T07:49:24-06:00 INFO [ip getter] Public IP address is 188.241.176.233 (Canada, Quebec, Montréal)
```

Pretty much the same docker-compose as well:

```yml
version: '3.7'
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8100:8000 # Remote Control VPN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=[redacted]
      - WIREGUARD_ADDRESSES=[redacted]
      - SERVER_COUNTRIES=Canada
      - PUID=1000
      - PGID=1000
      - TZ=US/Mountain
    volumes:
      - /data/wireguard:/gluetun
```

```uname -a``` should tell you whether you're running a 32-bit OS or 64-bit. Here's mine:

```console
pi@raspberrypi10:~ $ uname -a
Linux raspberrypi10 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by lucassardois** [comment] 2023-04-15 14:46
Ah yes sorry I had to repost the message and I forgot to repost my architecture, `uname -a` return this:
`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

**Comment by lucassardois** [comment] 2023-04-15 14:57
Ok that's very strange I regenerated a new key on Mullvad and now it works fine. No idea what is happening.

**Comment by bnhf** [comment] 2023-04-15 15:05
@lucassardois 

> Ok that's very strange I regenerated a new key on Mullvad and now it works fine. No idea what is happening.

Do the old key and new key have a similar appearance/structure? I've had it happen on my project, where the value for a variable is totally out-of-range or of a different type and causes a Go Panic as an unhandled error.

**Comment by lucassardois** [comment] 2023-04-15 15:07
Don't know if it help but the first non working key had a `+` symbol in it, the second only contains letters with a slash.

**Comment by bnhf** [comment] 2023-04-15 15:17
@lucassardois 

> Don't know if it help but the first non working key had a `+` symbol in it, the second only contains letters with a slash.

My key has a ```+``` in it, so that's not it. Since it's working now, and nobody else is reporting this so far -- it could be difficult to reproduce. I'd be tempted to close this issue out for now.

**Comment by lucassardois** [comment] 2023-04-20 21:49
Sadly I removed the key from my computer I don't think I can get it back...

**Comment by qdm12** [comment] 2023-04-20 22:49
But does it fail as soon as you put a `+` in your key? (haven't tried it yet)

**Comment by bnhf** [comment] 2023-04-20 23:00
@qdm12

> But does it fail as soon as you put a `+` in your key? (haven't tried it yet on an emulated arm64)

I have a Mullvad Wireguard key with a plus sign in it, which I've used on an RPi4 running the 64bit version of the Raspberry Pi OS (Debian 11) -- with no such panic.

**Comment by qdm12** [comment] 2023-04-20 23:26
Ok fine! 😄 
51f830cfc1f8240763dfaa6ce61b8257e497e694 bumped wireguard dependencies up, just in case ™️ (hopefully won't break everything either!)

**Closed by qdm12** 2023-04-20 23:26 UTC
