### ISSUE TITLE
Bug:  ERROR cannot read servers from file: cannot decode versions: invalid character '"' after top-level value

### ISSUE THREAD

**Issue by leo15dev** [qdm12/gluetun#922] opened 2022-03-31 23:30 UTC
### Is this urgent?

Yes

### Host OS

Ubuntu 20.04.4

### CPU arch

aarch64

### VPN service provider

Custom

### What are you using to run the container

docker-compose

### What is the version of Gluetun

 v3.28.2 built on 2022-03-31T20:59:07.284Z (commit c04cd62) and latest built on 2022-03-31T20:53:20.240Z (commit c33fb8b)

### What's the problem 🤔

 v3.28.2 built on 2022-03-31T20:59:07.284Z (commit c04cd62) and latest built on 2022-03-31T20:53:20.240Z (commit c33fb8b) had same problem after v3.28.2 release updated. The problem is ` ERROR cannot read servers from file: cannot decode versions: invalid character '"' after top-level value` . Thank you!

### Share your logs

```log
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2022-03-31T20:53:20.240Z (commit c33fb8b)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022-04-01T07:26:17+08:00 WARN DNS_ADDRESS is set to 45.90.28.81 so the DNS over TLS (DoT) server will not be used. The default value changed to 127.0.0.1 so it uses the internal DoT server. If the DoT server fails to start, the IPv4 address of the first plaintext DNS server corresponding to the first DoT provider chosen is used.
2022-04-01T07:26:17+08:00 INFO [routing] default route found: interface eth0, gateway 172.15.0.1 and assigned IP 172.15.0.17
2022-04-01T07:26:17+08:00 INFO [routing] default route found: interface eth0, gateway fc00::1 and assigned IP 172.15.0.17
2022-04-01T07:26:17+08:00 INFO [routing] local ethernet link found: eth0
2022-04-01T07:26:17+08:00 INFO [routing] local ipnet found: 172.15.0.0/24
2022-04-01T07:26:17+08:00 INFO [firewall] enabling...
2022-04-01T07:26:17+08:00 INFO [firewall] enabled successfully
2022-04-01T07:26:20+08:00 ERROR cannot read servers from file: cannot decode versions: invalid character '"' after top-level value
2022-04-01T07:26:20+08:00 INFO Shutdown successful
```

**Comment by qdm12** [comment] 2022-04-01 06:25
Can you attach your servers.json file? Maybe you added a double quote at the top?

**Comment by leo15dev** [comment] 2022-04-01 06:31
> Can you attach your servers.json file? Maybe you added a double quote at the top?
[servers.zip](https://github.com/qdm12/gluetun/files/8395213/servers.zip)
No, I never modify it.

**Comment by leo15dev** [comment] 2022-04-01 06:45
I tried to delete the servers.json which I provided in the above post, and restart container. Awesome! The gluetun re-download the server.json and both of the two container work again. So the issue was fixed by unknown reason.

**Comment by qdm12** [comment] 2022-04-01 08:39
Let's keep it opened, I'll investigate why it happened. But yeah removing the file makes gluetun create it again. Note it doesn't download it, it's built-in the program 😉

**Comment by qdm12** [comment] 2022-04-01 18:35
On line `104479`, it looks completely messed up:

```json
}
": [
```

More surrounding context:

```json
        // ...
        "hostname": "wf-us-015.whiskergalaxy.com",
        "wgpubkey": "GxEk9eSOUsTVzoE07pe4YZRaROCQwW96cQokD38Pgkk=",
        "ips": [
          "38.132.101.212"
        ]
      }
    ]
  }
}
": [
          "185.64.104.114"
        ]
      },
      {
        "vpn": "openvpn",
        "region": "Lithuania",
        "city": "Vilnius",
        "hostname": "lt-004.whiskergalaxy.com",
        // ...
```

I'm not really sure what happened, but it looks like some windscribe servers data (the end of the data) was extra-written to the whole valid json data. I don't think Gluetun would be able to do such thing, it could stop writing the data in the middle but not add extra data to the existing full valid data.

So not sure what happened, but you might want to check your drives perhaps :wink: Closing this for now since I have no clue what could be the cause, there is no fix to do, and the workaround is to delete the json file which is relatively easy!

**Closed by qdm12** 2022-04-01 18:35 UTC
