### ISSUE TITLE
Socks V5 ( not shadowsocks ) feature will be great as a proxy

### ISSUE THREAD

**Issue by saifalbadi** [qdm12/gluetun#2409] opened 2024-08-12 23:49 UTC
### What's the feature 🧐

Socks V5 ( not shadowsocks ) feature will be great as a proxy

### Extra information and references

it will be great feature, so Telegram can use it and torrent client like Bigly

**Comment by qdm12** [comment] 2024-08-14 14:16
Duplicate of #234

**Closed by qdm12** 2024-08-14 14:16 UTC
Labels: Closed: 👥 Duplicate
