### ISSUE TITLE
VPN provider support: OVPN

### ISSUE THREAD

**Issue by nomadism19** [qdm12/gluetun#1165] opened 2022-09-25 19:31 UTC
https://www.ovpn.com/en/configurations

[Archive.zip](https://github.com/qdm12/gluetun/files/9641630/Archive.zip)

**Comment by qdm12** [comment] 2022-09-25 21:07
Thanks! Closed as duplicate of #495 please subscribe to that one instead. I should implement it rather soon too.

**Closed by qdm12** 2022-09-25 21:07 UTC
