### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Kha-kis** [qdm12/gluetun#838] opened 2022-02-06 23:40 UTC
### Is this urgent?

No

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

Portainer

### What is the version of Gluetun

openvpn: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:17: data-ciphers-fallback (2.5.4)

### What's the problem 🤔

When running the latest version  Ovpn is unable to start correctly and constanty is restarting
The following error is presented:

`openvpn: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:17: data-ciphers-fallback (2.5.4)`

Reverting back to gluetun:v3.27.0 has remediated the issue for now.

### Share your logs

```log
`openvpn: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/target.ovpn:17: data-ciphers-fallback (2.5.4)`
```

**Comment by qdm12** [comment] 2022-02-07 00:07
duplicate of #837 and fixed in https://github.com/qdm12/gluetun/commit/ff3f84f9fd1c6ee7de3deed5883e7fd6ca645c09

Thanks for reporting the issue!

**Closed by qdm12** 2022-02-07 00:07 UTC
