### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by blixten85** [qdm12/gluetun#2245] opened 2024-04-30 04:32 UTC
### What's the feature 🧐

I really want to be able to use a hostname in my config file. I don't care if my IP gets leaked for a sneaky bit off a second. 
It should make a nslookup towards google or whatever services out there for my hostname to my VPN provider. It has to do this one time, what is the issue here? Really?

ERROR VPN settings: OpenVPN settings: custom configuration file: extracting information from custom configuration file: extracting connection from file: on line 7: extracting from remote line: host is not an IP address: openvpn.integrity.st

This host changes ip from time to time.

**Comment by qdm12** [comment] 2024-05-01 19:42
Duplicate of #788 

See https://github.com/qdm12/gluetun-wiki/blob/main/faq/others.md#server-information why it's like that

**Closed by qdm12** 2024-05-01 19:42 UTC
