### ISSUE TITLE
Bug: servers.json wrong ip

### ISSUE THREAD

**Issue by clpir3s** [qdm12/gluetun#2059] opened 2024-01-20 23:11 UTC
### Is this urgent?

None

### CPU arch

aarch64

### VPN service provider

Surfshark

### What are you using to run the container

docker-compose

### What is the version of Gluetun

v3.36.0

### What's the problem 🤔

Hello,

(I'm not sure if is a bug)

I'm not sure if I'm correct to interpreted the servers.json file, but the IP info not macth.

this ip **178.239.173.42** , is label as service: "NordVPN" in https://ipinfo.io/

btw, this IP is not listed
Strange is that the container up

https://raw.githubusercontent.com/qdm12/gluetun/master/internal/storage/servers.json
{
        "vpn": "openvpn",
        "country": "Netherlands",
        "region": "Europe",
        "city": "Amsterdam",
        "hostname": "nl-ams.prod.surfshark.com",
        "tcp": true,
        "udp": true,
        "retroloc": "Netherlands Amsterdam",
        "ips": [
          "81.19.216.253",
          "89.46.223.54",
          "89.46.223.58",
          "89.46.223.181",
          "89.46.223.183",
          "143.244.42.66",
          "143.244.42.69",
          "143.244.42.71",
          "143.244.42.89",
          "143.244.42.94",
          "146.70.175.11",
          "146.70.175.43",
          "146.70.175.61",
          "146.70.175.69",
          "146.70.175.75",
          **"178.239.173.41",
          "178.239.173.43"**
        ]
      },
      {
        "vpn": "wireguard",
        "country": "Netherlands",
        "region": "Europe",
        "city": "Amsterdam",
        "hostname": "nl-ams.prod.surfshark.com",
        "retroloc": "Netherlands Amsterdam",
        "wgpubkey": "Lxg3jAOKcBA9tGBtB6vEWMFl5LUEB6AwOpuniYn1cig=",
        "ips": [
          "81.19.216.253",
          "89.46.223.54",
          "89.46.223.58",
          "89.46.223.181",
          "89.46.223.183",
          "143.244.42.66",
          "143.244.42.69",
          "143.244.42.71",
          "143.244.42.89",
          "143.244.42.94",
          "146.70.175.11",
          "146.70.175.43",
          "146.70.175.61",
          "146.70.175.69",
          "146.70.175.75",
          **"178.239.173.41",
          "178.239.173.43"**
        ]
      },

### Share your logs (at least 10 lines)

```plain text
nl-proxyserver-1  | 2024-01-20T22:26:50Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [vpn] stopping
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [vpn] starting
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [firewall] allowing VPN connection...
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [wireguard] Using available kernelspace implementation
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [wireguard] Connecting to 178.239.173.41:51820
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [healthcheck] healthy!
nl-proxyserver-1  | 2024-01-20T22:26:58Z INFO [ip getter] Public IP address is 178.239.173.42 (Netherlands, North Holland, Amsterdam)
```

**Comment by qdm12** [comment] 2024-02-05 12:53
Checking https://ipinfo.io/178.239.173.41  it's hydra communications, not NordVPN right? Anyway ipinfo.io data may be outdated, especially when it comes to details like the service behind it.

The DNS server responding to queries for nl-ams.prod.surfshark.com does respond different IP addresses for each query (do split the traffic on their end). I just checked, resolving it a few times gives me 178.239.173.41 so it's working as intended.

**Closed by qdm12** 2024-02-05 12:53 UTC
