### ISSUE TITLE
Bug: static server in SERVER_HOSTNAMES causes error: no server found

### ISSUE THREAD

**Issue by themw123** [qdm12/gluetun#1382] opened 2023-02-02 16:47 UTC
### Is this urgent?

None

### Host OS

Ubuntu

### CPU arch

x86_64

### VPN service provider

Surfshark

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2022-12-31T17:50:58.654Z (commit ea40b84)

### What's the problem 🤔

I am using Surfshark with Wireguard. When using a static german surfshark server i am getting error.
When using normal instead of static Surfshark german server it is working like for example with: de-ber.prod.surfshark.com. 

### Share your logs

```plain text
ERROR [vpn] failed finding a VPN server: cannot filter servers: no server found: for VPN wireguard; protocol udp; hostname de-fra-st005.prod.surfshark.com
```

### Share your configuration

```yml
docker run -d \
  --name=gluetun \
  -e VPN_SERVICE_PROVIDER=surfshark \
  -e VPN_TYPE=wireguard \
  -e WIREGUARD_PRIVATE_KEY=XXX \
  -e WIREGUARD_ADDRESSES="10.14.0.2/16" \
  -e SERVER_HOSTNAMES=de-fra-st005.prod.surfshark.com \
  -e TZ=CET \
  -v /stuff/gluetun:/gluetun \
  --cap-add=NET_ADMIN \
  -devices=/dev/net/tun:/dev/net/tun \
  -p 8888:8888/tcp \
  -p 8388:8388/tcp \
  -p 8388:8388/udp \
  --restart=unless-stopped \
  qmcgaw/gluetun:latest
```

**Comment by le0m** [comment] 2023-02-03 18:17
Looking at the [included server list](https://github.com/qdm12/gluetun/blob/master/internal/storage/servers.json), the problem is that the server you're trying to use is for OpenVPN and not for Wireguard, so it's filtered out.

You should choose another server that supports Wireguard, or switch to OpenVPN configuration.

**Comment by qdm12** [comment] 2023-03-23 15:42
Thank you @le0m you're exactly on point 🎖️ Closing this.

**Closed by qdm12** 2023-03-23 15:42 UTC
