### ISSUE TITLE
Unhealthy gluetun container when using Private Internet Access

### ISSUE THREAD

**Issue by umbongodrink** [qdm12/gluetun#500] opened 2021-06-20 22:42 UTC
Hello, I am trying to get gluetun working in a very basic configuration using a Raspberry Pi 4B (4GB model) and Raspbian 10 Buster. 

I am testing using the basic command given as an example given at https://github.com/qdm12/gluetun:

```sh
docker run -d --name gluetun --cap-add=NET_ADMIN \
-e VPNSP="private internet access" -e REGION="CA Montreal" \
-e OPENVPN_USER=js89ds7 -e OPENVPN_PASSWORD=8fd9s239G \
-v /yourpath:/gluetun \
qmcgaw/gluetun
```

When I run the above code (substituting my Username and Password combination as appropriate) the container starts but shortly I see it as "unhealthy" and the following messages (I remove the -d flag to show them):

```
2021/06/20 22:29:03 INFO Alpine version: 3.13.5
2021/06/20 22:29:03 INFO OpenVPN 2.4 version: 2.4.11
2021/06/20 22:29:03 INFO OpenVPN 2.5 version: 2.5.2
2021/06/20 22:29:03 INFO Unbound version: 1.13.0
2021/06/20 22:29:03 INFO IPtables version: v1.8.6
2021/06/20 22:29:03 INFO Settings summary below:
|--OpenVPN:
   |--Version: 2.5
   |--Verbosity level: 1
   |--Run as root: enabled
   |--Provider:
      |--Private Internet Access settings:
         |--Network protocol: udp
         |--Regions: ca montreal
         |--Encryption preset: strong
|--DNS:
   |--Plaintext address: 1.1.1.1
   |--DNS over TLS:
      |--Unbound:
          |--DNS over TLS providers:
              |--Cloudflare
          |--Listening port: 53
          |--Access control:
              |--Allowed:
                  |--0.0.0.0/0
                  |--::/0
          |--Caching: enabled
          |--IPv4 resolution: enabled
          |--IPv6 resolution: disabled
          |--Verbosity level: 1/5
          |--Verbosity details level: 0/4
          |--Validation log level: 0/2
          |--Username:
      |--Blacklist:
         |--Blocked categories: malicious
         |--Additional IP networks blocked: 13
      |--Update: every 24h0m0s
|--Firewall:
|--System:
   |--Process user ID: 1000
   |--Process group ID: 1000
   |--Timezone: NOT SET ⚠️ - it can cause time related issues
|--HTTP control server:
   |--Listening port: 8000
   |--Logging: enabled
|--Public IP getter:
   |--Fetch period: 12h0m0s
   |--IP file: /tmp/gluetun/ip
|--Github version information: enabled
2021/06/20 22:29:04 INFO storage: merging by most recent 9142 hardcoded servers and 9142 servers read from /gluetun/servers.json
2021/06/20 22:29:04 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/06/20 22:29:04 INFO routing: local ethernet link found: eth0
2021/06/20 22:29:04 INFO routing: local ipnet found: 172.17.0.0/16
2021/06/20 22:29:04 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/06/20 22:29:04 INFO routing: adding route for 0.0.0.0/0
2021/06/20 22:29:04 INFO firewall: firewall disabled, only updating allowed subnets internal list
2021/06/20 22:29:04 INFO routing: default route found: interface eth0, gateway 172.17.0.1
2021/06/20 22:29:04 INFO openvpn configurator: checking for device /dev/net/tun
2021/06/20 22:29:04 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021/06/20 22:29:04 INFO openvpn configurator: creating /dev/net/tun
2021/06/20 22:29:04 INFO firewall: enabling...
2021/06/20 22:29:05 INFO firewall: enabled successfully
2021/06/20 22:29:05 INFO dns over tls: using plaintext DNS at address 1.1.1.1
2021/06/20 22:29:05 INFO healthcheck: listening on 127.0.0.1:9999
2021/06/20 22:29:05 INFO http server: listening on :8000
2021/06/20 22:29:05 INFO firewall: setting VPN connection through firewall...
2021/06/20 22:29:05 INFO openvpn configurator: starting OpenVPN 2.5
2021/06/20 22:29:05 INFO openvpn: 2071-06-27 23:35:12 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/06/20 22:29:05 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/06/20 22:29:05 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/06/20 22:29:05 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
2021/06/20 22:29:05 INFO openvpn: MIIDWDCCAUAwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTETMBEGA1UEBxMKTG9zQW EDITED
6/20 22:29:05 INFO openvpn: -----END X509 CRL-----
2021/06/20 22:29:05 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]172.98.71.93:1197
2021/06/20 22:29:05 INFO openvpn: UDP link local: (not bound)
2021/06/20 22:29:05 INFO openvpn: UDP link remote: [AF_INET]172.98.71.93:1197
2021/06/20 22:29:05 INFO openvpn: VERIFY ERROR: depth=0, error=format error in CRL's lastUpdate field: C=US, ST=CA, L=LosAngeles, O=Private Internet Access, OU=Private Internet Access, CN=montreal402, name=montreal402, serial=94916666378
2021/06/20 22:29:05 INFO openvpn: OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2021/06/20 22:29:05 INFO openvpn: TLS_ERROR: BIO read tls_read_plaintext error
2021/06/20 22:29:05 INFO openvpn: TLS Error: TLS object -> incoming plaintext read error
2021/06/20 22:29:05 INFO openvpn: TLS Error: TLS handshake failed
2021/06/20 22:29:05 INFO openvpn: SIGUSR1[soft,tls-error] received, process restarting
2021/06/20 22:29:06 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
2021/06/20 22:29:12 WARN openvpn: unhealthy program: restarting openvpn
2021/06/20 22:29:12 INFO firewall: setting VPN connection through firewall...
2021/06/20 22:29:12 INFO openvpn configurator: starting OpenVPN 2.5
2021/06/20 22:29:12 INFO openvpn: 2071-07-17 02:06:40 DEPRECATED OPTION: ncp-disable. Disabling cipher negotiation is a deprecated debug feature that will be removed in OpenVPN 2.6
2021/06/20 22:29:12 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
2021/06/20 22:29:12 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
2021/06/20 22:29:12 INFO openvpn: CRL: loaded 1 CRLs from file -----BEGIN X509 CRL-----
...
```

Can you please help?

**Comment by umbongodrink** [comment] 2021-06-20 22:51
Also, sorry, what does this mean?: 
" Raspberry Pi users running 32 bit systems: from image v3.16.0 you need to do this on your host to run the container."

How do you implement this in your basic command?

**Comment by qdm12** [comment] 2021-06-21 20:14
Yes that looks to very likely the cause. The problem is you need libseccomp 2.5.1-1 on your host (as your linux kernel needs it, since containers use the same linux kernel).

Can you quickly help me so I can clarify the documentation please:

1. Can you try running

    ```sh
    sudo apt list libseccomp2
    ```

     What do you get?

2. If you then do

    ```sh
    sudo apt-get update -y
    sudo apt list libseccomp2
    ```

    What do you have then?

Finally, the solution (to do after the two above please):

```sh
wget -qO libseccomp2.deb https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2.deb
```

If you don't have `wget` install it with `sudo apt-get install -y wget`

**Comment by umbongodrink** [comment] 2021-06-22 09:48
Hello, thank you very much for your response! Answers as follows:

1) when I run that command I receive:
`libseccomp2/stable,now 2.3.3-4 armhf [installed]`

2) I have the same, 
`libseccomp2/stable,now 2.3.3-4 armhf [installed]`

3) Again, I receive the same output,
`libseccomp2/stable,now 2.3.3-4 armhf [installed]`

4) I used the wget command and dpkg command to install the .deb. Now when I run the command 
`sudo apt list libseccomp2`
I receive
`libseccomp2/now 2.5.1-1 armhf [installed,local]
N: There is 1 additional version. Please use the '-a' switch to see it`

Now I am running your basic `docker run` example command, and I see the status now as healthy (which I wasn't before). Thank you!!

I will continue testing as part of my docker-compose setup (instead of the run command) and report back a bit later.

**Comment by umbongodrink** [comment] 2021-06-22 12:26
Ok I'm now attempting to use the gluetun container via docker-compose. I get status unhealthy every time I attempt it, even with very vanilla settings, as follows.

(Obviously I put in my User/Pass combination, and I've had to remove the code markup as it's not formatting the yml properly, and hence the below is not indented properly).

version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun:latest   
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
    volumes:
      - /home/pi/Documents/docker/gluetun/volume:/gluetun
    environment:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - VPNSP=private internet access
      - TZ=Europe/London
    restart: always

Any thoughts on how to make it work now? Do you think docker-compose is not using somehow the 2.5.1-1 version of libseccomp2? 

Thanks for your help.

**Comment by qdm12** [comment] 2021-06-22 13:34
- Thanks for the replies, I'll update the readme/wiki accordingly
- You can highlight code with [this](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlight) using the `yml` language, it's mega useful everywhere for me 😉  I'll update the issue template with it!
- Gluetun should be using that libseccomp, since it's in the kernel of your system (kernel = code bridging the hardware and software, in this case about time representation)
- Share your logs 😉 I can't really tell otherwise, the Docker-compose.yml you shared looks fine.

**Comment by qdm12** [comment] 2021-06-22 15:21
I wrote a Wiki page on this: https://github.com/qdm12/gluetun/wiki/32-bit-setup

Can you try

```sh
scmp_sys_resolver -a arm clock_gettime64
```

Does it return 403? Do you need to prefix it with `sudo`?

**Comment by umbongodrink** [comment] 2021-06-22 17:20
Hi, the docker-compose issue was absolutely my mistake - my old PIA password had a "!" character in it. It was clearly causing issues of interpretation in the docker-compose yml document, so I changed the password and didn't update my docker-compose.yml accordingly. Once updated gluetun was healthy. Sorry about that, my fault. 
Gluetun is working in a standalone way now, using docker-compose.

To answer your question re that command scmp_sys_resolver, I get the output:
`-bash: scmp_sys_resolver: command not found`
I get this whether or not sudo is used. 

I have now been trying to get gluetun to work in conjunction with syncthing, so that my syncthing traffic goes through my PIA vpn connection. My new docker-compose.yml file is this:

```
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun:latest   
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server

      - 8384:8384 # Syncthing Port web access
      - 22000:22000/tcp # Syncthing 
      - 22000:22000/udp # Syncthing
      - 21027:21027/udp # Syncthing
      
    volumes:
      - /home/pi/Documents/docker/gluetun/volume:/gluetun
    environment:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - VPNSP=private internet access
      - REGION=Netherlands
      - PORT_FORWARDING=on
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
      - OPENVPN_CIPHER=aes-256-gcm
      - OPENVPN_AUTH=sha256
      - TZ=Europe/London
    restart: always

  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/Documents/docker/syncthing/config:/config
      - /home/pi/Documents/tempmovies:/data1
#      - /path/to/data2:/data2s
#    ports:
#      - 8384:8384
#      - 22000:22000/tcp
#      - 22000:22000/udp
#      - 21027:21027/udp
    restart: unless-stopped
    network_mode: "service:gluetun"
```

When I bring this yml up, both come up healthy. 

However, when I try to reach the syncthing web UI on port 8384, I am prompted for authentication which I give, but then I am never admitted to the UI, the webpage is constantly loading (or never fully loads). Furthermore, when I try to issue a `docker ps`, I don't receive anything in return apart from the generic docker category headers, and my tty crashes. Any thoughts on this? (I appreciate that syncthing isn't your application and if you don't want to assist, no problem at all.:-) )

Just a question if you don't mind please? Can you recommend a docker bittorrent client that will work in conjunction with gluetun? Having done all this work I would like to take advantage of gluetun. Or should I look for a container that has a bittorrent client and vpn combined into it as an all-in-one? 

Many thanks for the triple backticks for use in formatting the yml correctly here, as well as the explanations in your answers, super helpful!!

**Comment by qdm12** [comment] 2021-06-22 18:32
> To answer your question re that command scmp_sys_resolver, I get the output

Can you try:

```sh
apt-get install -y seccomp
scmp_sys_resolver -a arm clock_gettime64
```

> I have now been trying to get gluetun to work in conjunction with syncthing...

I created a Github discussion with your content at #503 let's continue the discussion there to avoid polluting the issue too much.

**Comment by umbongodrink** [comment] 2021-06-22 19:52
Hi, sure, after issuing those two commands I receive the following:

`$ scmp_sys_resolver -a arm clock_gettime64`

`-1`

Is that helpful in giving more info?

Thank you for your 503 answer, will pick it up there.

**Comment by qdm12** [comment] 2021-06-22 21:23
Uh strange, it's meant to give you `403` to indicate `clock_gettime64` is supported.

When I run on my machine an emulated arm v7 machine:

```sh
docker run -it --rm --platform=linux/arm/v7 alpine:3.13 apk add libseccomp && scmp_sys_resolver -a arm clock_gettime64
```

It does give me `403` as expected 🤔

Can you try this command on your raspberry pi:

```sh
docker run -it --rm alpine:3.13 apk add libseccomp && scmp_sys_resolver -a arm clock_gettime64
```

Does it give `-1` as well?

**Comment by umbongodrink** [comment] 2021-06-22 21:55
Sure, absolutely no problem. 

The answer is yes it does, here's the full output:

```
$ docker run -it --rm alpine:3.13 apk add libseccomp && scmp_sys_resolver -a arm clock_gettime64
Unable to find image 'alpine:3.13' locally
3.13: Pulling from library/alpine
e160e00eb35d: Already exists
Digest: sha256:f51ff2d96627690d62fee79e6eecd9fa87429a38142b5df8a3bfbb26061df7fc
Status: Downloaded newer image for alpine:3.13
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
(1/1) Installing libseccomp (2.5.1-r1)
Executing busybox-1.32.1-r6.trigger
OK: 4 MiB in 15 packages
-1
```

**Comment by qdm12** [comment] 2021-06-22 21:58
Ugh this is frustrating. Last question, what's the output of `sudo apt list -a libseccomp2` ? I guess I'll just remove that command since your gluetun now works 🤔

**Comment by umbongodrink** [comment] 2021-06-22 22:24
No problem at all, it's:

```
$ sudo apt list -a libseccomp2
[sudo] password for pi:
Listing... Done
libseccomp2/now 2.5.1-1 armhf [installed,local]
libseccomp2/stable 2.3.3-4 armhf
```

If you need me to run any more commands, I'm very happy to do that. 👍🏽

Yes gluetun works, it was 
```
wget -qO libseccomp2.deb https://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2.deb
```
that did the magic with respect to getting it to work on my Raspbian Buster 32bit OS.

**Comment by qdm12** [comment] 2021-06-23 01:15
Alright cool, I removed the `scmp_sys_resolver` check as it doesn't seem to work for whatever reason. Closing! 👍

**Closed by qdm12** 2021-06-23 01:15 UTC
Labels: Documentation :memo:, Needs more info :thinking:

**Comment by qdm12** [comment] 2021-06-25 19:02
Quick extra question.... how about `scmp_sys_resolver faccessat2`? Does it give 439 or -1?

**Comment by umbongodrink** [comment] 2021-06-25 19:15
Hi, sure absolutely no problem. 

Still -1 I'm afraid:

```
$ scmp_sys_resolver faccessat2
-1
```
