### ISSUE TITLE
Bug: No DNS resolution for containers going through gluetun

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun#1229] opened 2022-11-09 00:40 UTC
### Is this urgent?

Yes

### Host OS

MacOS

### CPU arch

x86_64

### VPN service provider

Privado

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-10-31T11:25:29.199Z (commit 192a7a5)

### What's the problem 🤔

I don't appear to be getting any DNS resolution through gluetun.  From looking at the log this looks to be the same issue as the issue before this one that was reported.

### Share your logs

```plain text
gluetun_vpn  | ========================================
gluetun_vpn  | ========================================
gluetun_vpn  | =============== gluetun ================
gluetun_vpn  | ========================================
gluetun_vpn  | =========== Made with ❤️ by ============
gluetun_vpn  | ======= https://github.com/qdm12 =======
gluetun_vpn  | ========================================
gluetun_vpn  | ========================================
gluetun_vpn  | 
gluetun_vpn  | Running version latest built on 2022-10-31T11:25:29.199Z (commit 192a7a5)
gluetun_vpn  | 
gluetun_vpn  | 🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
gluetun_vpn  | 🐛 Bug? https://github.com/qdm12/gluetun/issues/new
gluetun_vpn  | ✨ New feature? https://github.com/qdm12/gluetun/issues/new
gluetun_vpn  | ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
gluetun_vpn  | 💻 Email? quentin.mcgaw@gmail.com
gluetun_vpn  | 💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
gluetun_vpn  | 2022-11-08T19:31:34-05:00 WARN You are using the old environment variable VPNSP, please consider changing it to VPN_SERVICE_PROVIDER
gluetun_vpn  | 2022-11-08T19:31:34-05:00 WARN You are using the old environment variable SERVER_HOSTNAME, please consider changing it to SERVER_HOSTNAMES
gluetun_vpn  | 2022-11-08T19:31:34-05:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.3
gluetun_vpn  | 2022-11-08T19:31:34-05:00 INFO [routing] local ethernet link found: eth0
gluetun_vpn  | 2022-11-08T19:31:34-05:00 INFO [routing] local ipnet found: 172.17.0.0/16
gluetun_vpn  | 2022-11-08T19:31:34-05:00 INFO [firewall] enabling...
gluetun_vpn  | 2022-11-08T19:31:34-05:00 INFO [firewall] enabled successfully
gluetun_vpn  | 2022-11-08T19:31:35-05:00 INFO [storage] merging by most recent 13220 hardcoded servers and 13220 servers read from /gluetun/servers.json
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO Alpine version: 3.16.2
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO OpenVPN 2.4 version: 2.4.12
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO OpenVPN 2.5 version: 2.5.6
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO Unbound version: 1.15.0
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO IPtables version: v1.8.8
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO Settings summary:
gluetun_vpn  | ├── VPN settings:
gluetun_vpn  | |   ├── VPN provider settings:
gluetun_vpn  | |   |   ├── Name: privado
gluetun_vpn  | |   |   └── Server selection settings:
gluetun_vpn  | |   |       ├── VPN type: openvpn
gluetun_vpn  | |   |       ├── Hostnames: jfk-002.vpn.privado.io, jfk-001.vpn.privado.io, jfk-005.vpn.privado.io, jfk-010.vpn.privado.io, jfk-011.vpn.privado.io, jfk-038.vpn.privado.io, jfk-039.vpn.privado.io
gluetun_vpn  | |   |       └── OpenVPN server selection settings:
gluetun_vpn  | |   |           └── Protocol: UDP
gluetun_vpn  | |   └── OpenVPN settings:
gluetun_vpn  | |       ├── OpenVPN version: 2.5
gluetun_vpn  | |       ├── User: [set]
gluetun_vpn  | |       ├── Password: [set]
gluetun_vpn  | |       ├── Network interface: tun0
gluetun_vpn  | |       ├── Run OpenVPN as: root
gluetun_vpn  | |       └── Verbosity level: 1
gluetun_vpn  | ├── DNS settings:
gluetun_vpn  | |   ├── DNS server address to use: 127.0.0.1
gluetun_vpn  | |   ├── Keep existing nameserver(s): no
gluetun_vpn  | |   └── DNS over TLS settings:
gluetun_vpn  | |       ├── Enabled: yes
gluetun_vpn  | |       ├── Update period: every 24h0m0s
gluetun_vpn  | |       ├── Unbound settings:
gluetun_vpn  | |       |   ├── Authoritative servers:
gluetun_vpn  | |       |   |   └── cloudflare
gluetun_vpn  | |       |   ├── Caching: yes
gluetun_vpn  | |       |   ├── IPv6: no
gluetun_vpn  | |       |   ├── Verbosity level: 1
gluetun_vpn  | |       |   ├── Verbosity details level: 0
gluetun_vpn  | |       |   ├── Validation log level: 0
gluetun_vpn  | |       |   ├── System user: root
gluetun_vpn  | |       |   └── Allowed networks:
gluetun_vpn  | |       |       ├── 0.0.0.0/0
gluetun_vpn  | |       |       └── ::/0
gluetun_vpn  | |       └── DNS filtering settings:
gluetun_vpn  | |           ├── Block malicious: yes
gluetun_vpn  | |           ├── Block ads: no
gluetun_vpn  | |           ├── Block surveillance: no
gluetun_vpn  | |           └── Blocked IP networks:
gluetun_vpn  | |               ├── 127.0.0.1/8
gluetun_vpn  | |               ├── 10.0.0.0/8
gluetun_vpn  | |               ├── 172.16.0.0/12
gluetun_vpn  | |               ├── 192.168.0.0/16
gluetun_vpn  | |               ├── 169.254.0.0/16
gluetun_vpn  | |               ├── ::1/128
gluetun_vpn  | |               ├── fc00::/7
gluetun_vpn  | |               ├── fe80::/10
gluetun_vpn  | |               ├── ::ffff:7f00:1/104
gluetun_vpn  | |               ├── ::ffff:a00:0/104
gluetun_vpn  | |               ├── ::ffff:a9fe:0/112
gluetun_vpn  | |               ├── ::ffff:ac10:0/108
gluetun_vpn  | |               └── ::ffff:c0a8:0/112
gluetun_vpn  | ├── Firewall settings:
gluetun_vpn  | |   ├── Enabled: yes
gluetun_vpn  | |   └── Outbound subnets:
gluetun_vpn  | |       └── {192.168.0.182 ffffffff}
gluetun_vpn  | ├── Log settings:
gluetun_vpn  | |   └── Log level: INFO
gluetun_vpn  | ├── Health settings:
gluetun_vpn  | |   ├── Server listening address: 127.0.0.1:9999
gluetun_vpn  | |   ├── Target address: cloudflare.com:443
gluetun_vpn  | |   ├── Read header timeout: 100ms
gluetun_vpn  | |   ├── Read timeout: 500ms
gluetun_vpn  | |   └── VPN wait durations:
gluetun_vpn  | |       ├── Initial duration: 6s
gluetun_vpn  | |       └── Additional duration: 5s
gluetun_vpn  | ├── Shadowsocks server settings:
gluetun_vpn  | |   ├── Enabled: yes
gluetun_vpn  | |   ├── Listening address: :8388
gluetun_vpn  | |   ├── Cipher: chacha20-ietf-poly1305
gluetun_vpn  | |   ├── Password: [set]
gluetun_vpn  | |   └── Log addresses: yes
gluetun_vpn  | ├── HTTP proxy settings:
gluetun_vpn  | |   └── Enabled: no
gluetun_vpn  | ├── Control server settings:
gluetun_vpn  | |   ├── Listening address: :8000
gluetun_vpn  | |   └── Logging: yes
gluetun_vpn  | ├── OS Alpine settings:
gluetun_vpn  | |   ├── Process UID: 1000
gluetun_vpn  | |   ├── Process GID: 1000
gluetun_vpn  | |   └── Timezone: America/New_York
gluetun_vpn  | ├── Public IP settings:
gluetun_vpn  | |   ├── Fetching: every 12h0m0s
gluetun_vpn  | |   └── IP file path: /tmp/gluetun/ip
gluetun_vpn  | └── Version settings:
gluetun_vpn  |     └── Enabled: yes
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO IPv6 is not supported
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.3
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [routing] adding route for 0.0.0.0/0
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [firewall] setting allowed subnets...
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [routing] default route found: interface eth0, gateway 172.17.0.1 and assigned IP 172.17.0.3
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [routing] adding route for 192.168.0.182/32
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [pprof] http server listening on [::]:6060
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [http server] http server listening on [::]:8000
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [healthcheck] listening on 127.0.0.1:9999
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [shadowsocks] listening TCP on :8388
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [shadowsocks] listening UDP on :8388
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]23.19.225.69:1194
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] UDP link remote: [AF_INET]23.19.225.69:1194
gluetun_vpn  | 2022-11-08T19:31:36-05:00 INFO [openvpn] read UDP [EHOSTUNREACH]: Host is unreachable (code=113)
gluetun_vpn  | 2022-11-08T19:31:39-05:00 INFO [openvpn] read UDP [EHOSTUNREACH]: Host is unreachable (code=113)
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.240.97.72:1194
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:31:42-05:00 INFO [openvpn] UDP link remote: [AF_INET]209.240.97.72:1194
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [healthcheck] program has been unhealthy for 11s: restarting VPN
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:31:53-05:00 INFO [openvpn] UDP link remote: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [healthcheck] program has been unhealthy for 16s: restarting VPN
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.240.97.72:1194
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:32:09-05:00 INFO [openvpn] UDP link remote: [AF_INET]209.240.97.72:1194
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [healthcheck] program has been unhealthy for 21s: restarting VPN
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]217.138.208.106:1194
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:32:30-05:00 INFO [openvpn] UDP link remote: [AF_INET]217.138.208.106:1194
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [healthcheck] program has been unhealthy for 26s: restarting VPN
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:32:56-05:00 INFO [openvpn] UDP link remote: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [healthcheck] program has been unhealthy for 31s: restarting VPN
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:33:27-05:00 INFO [openvpn] UDP link remote: [AF_INET]209.240.97.67:1194
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [healthcheck] program has been unhealthy for 36s: restarting VPN
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.244.3:1194
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:34:03-05:00 INFO [openvpn] UDP link remote: [AF_INET]37.120.244.3:1194
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [healthcheck] program has been unhealthy for 41s: restarting VPN
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [vpn] stopping
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [vpn] starting
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [firewall] allowing VPN connection...
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1q  5 Jul 2022, LZO 2.10
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.244.3:1194
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [openvpn] UDP link local: (not bound)
gluetun_vpn  | 2022-11-08T19:34:44-05:00 INFO [openvpn] UDP link remote: [AF_INET]37.120.244.3:1194
```

**Comment by branrollins** [comment] 2022-11-12 22:09
I can confirm.  I just updated gluetun container and it appeared I was having dns issues so came here to see if it was a known thing.

**Comment by qdm12** [comment] 2022-11-12 22:14
`program has been unhealthy for 41s` is probably just an outdated vpn server, see the wiki on how to update servers data. DNS has nothing to do with it, it's just the vpn connection not working at all. You also didn't share your configuration, but you might want to try changing server filters to see if it works with another server.

@branrollins you're probably facing the same issue (outdated servers) or a config issue (create a github discussion with your config).

Closing this for now since it's not a bug as far as I can tell, but feel free to comment back.

**Closed by qdm12** 2022-11-12 22:14 UTC

**Comment by branrollins** [comment] 2022-11-13 00:31
@qdm12 you were right in my case.  I ended up exporting the docker config and simply changed which nordvpn server to use and recreated my docker container and it worked..so maybe the server I was using went down (it was on the list but may have just been an outage).  Thanks for the hint.

**Comment by shuntera** [comment] 2022-11-14 04:50
Hmm, have changed the VPN hostnames a number of times but am still seeing this in the logs:

2022-11-13T23:44:24-05:00 INFO [vpn] starting
2022-11-13T23:44:24-05:00 INFO [firewall] allowing VPN connection...
2022-11-13T23:44:24-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
2022-11-13T23:44:24-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1s  1 Nov 2022, LZO 2.10
2022-11-13T23:44:24-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]23.19.225.69:1194
2022-11-13T23:44:24-05:00 INFO [openvpn] UDP link local: (not bound)
2022-11-13T23:44:24-05:00 INFO [openvpn] UDP link remote: [AF_INET]23.19.225.69:1194
2022-11-13T23:44:27-05:00 INFO [openvpn] read UDP [EHOSTUNREACH|EHOSTUNREACH]: Host is unreachable (code=113)
2022-11-13T23:44:33-05:00 INFO [openvpn] read UDP [EHOSTUNREACH]: Host is unreachable (code=113)
2022-11-13T23:44:41-05:00 INFO [openvpn] read UDP [EHOSTUNREACH]: Host is unreachable (code=113)
2022-11-13T23:44:56-05:00 INFO [openvpn] read UDP [EHOSTUNREACH]: Host is unreachable (code=113)
2022-11-13T23:45:15-05:00 INFO [healthcheck] program has been unhealthy for 51s: restarting VPN
2022-11-13T23:45:15-05:00 INFO [vpn] stopping
2022-11-13T23:45:15-05:00 INFO [vpn] starting
2022-11-13T23:45:15-05:00 INFO [firewall] allowing VPN connection...
2022-11-13T23:45:15-05:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 17 2022
2022-11-13T23:45:15-05:00 INFO [openvpn] library versions: OpenSSL 1.1.1s  1 Nov 2022, LZO 2.10
2022-11-13T23:45:15-05:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]37.120.244.17:1194
2022-11-13T23:45:15-05:00 INFO [openvpn] UDP link local: (not bound)
2022-11-13T23:45:15-05:00 INFO [openvpn] UDP link remote: [AF_INET]37.120.244.17:1194
2022-11-13T23:45:15-05:00 INFO [openvpn] read UDP [ECONNREFUSED]: Connection refused (code=111)
2022-11-13T23:45:17-05:00 INFO [openvpn] read UDP [ECONNREFUSED]: Connection refused (code=111)
2022-11-13T23:45:21-05:00 INFO [openvpn] read UDP [ECONNREFUSED]: Connection refused (code=111)

Here is my gluetun config from docker-compose, I don't get any unrecognized server errors with this selection:

environment:
      - VPN_SERVICE_PROVIDER=privado
      - SHADOWSOCKS=on
      - SHADOWSOCKS_PASSWORD=********
      - SHADOWSOCKS_LOG=on
      - TZ=America/New_York
      - OPENVPN_USER=********
      - OPENVPN_PASSWORD=********
      - SERVER_HOSTNAMES=jfk-001.vpn.privado.io,jfk-007.vpn.privado.io,jfk-008.vpn.privado.io,jfk-009.vpn.privado.io,jfk-010.vpn.privado.io,jfk-011.vpn.privado.io,jfk-038.vpn.privado.io,jfk-039.vpn.privado.io
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.182/32
