### ISSUE TITLE
Bug: NordVPN Credentials Wrong 

### ISSUE THREAD

**Issue by ingsocdev** [qdm12/gluetun#964] opened 2022-04-25 23:01 UTC
### Is this urgent?

Yes

### Host OS

Ubuntu 20.04.4 LTS

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2022-04-23T12:58:11.855Z (commit a1d70f7)

### What's the problem 🤔

Haven't changed credentials, can still log into NordVPN app. Gluetun sporadically works with these creds.

### Share your logs

```log
2022-04-25T22:57:43Z INFO [openvpn] SIGUSR1[soft,auth-failure] received, process restarting
2022-04-25T22:57:53Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]213.232.87.204:1194
2022-04-25T22:57:53Z INFO [openvpn] UDP link local: (not bound)
2022-04-25T22:57:53Z INFO [openvpn] UDP link remote: [AF_INET]213.232.87.204:1194
2022-04-25T22:57:55Z WARN [openvpn] 'link-mtu' is used inconsistently, local='link-mtu 1582', remote='link-mtu 1634'
2022-04-25T22:57:55Z WARN [openvpn] 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA512'
2022-04-25T22:57:55Z INFO [openvpn] [nl729.nordvpn.com] Peer Connection Initiated with [AF_INET]213.232.87.204:1194
2022-04-25T22:57:56Z ERROR [openvpn] AUTH: Received control message: AUTH_FAILED

Your credentials might be wrong 🤨
```

**Comment by qdm12** [comment] 2022-04-26 11:20
52c8bc075f87c8a3e845bb5b14ba01d03189ef75 updates the Nordvpn server information, maybe that would remove strange non working servers. Note you can update the servers data yourself see the wiki page on Updating servers.

Other than that, it might just be a problem on Nordvpn's side, so please contact their support if this continues.

**Comment by Mereks** [comment] 2022-04-26 11:55
I am having the same issues though I cannot connect to any server. I have updated my servers.json as well today. Credentials haven't changed and gluetun has worked fine for months until the update a couple days ago.

**Comment by qdm12** [comment] 2022-04-26 13:33
Actually I remember #944 got added recently. Does qmcgaw/gluetun:v3.28.2 work?

**Comment by oenu** [comment] 2022-04-26 13:40
Also having this issue, wondering if 

`WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.8.2.2:37172->1.1.1.1:53: i/o timeout`

Has anything to do with it 🤔

**Comment by oenu** [comment] 2022-04-26 13:46
Another possibility is that the client reconnecting is triggering a failed auth after multiple attempts, triggered by healthcheck. After logging into their site with my credentials it seemed to allow further connection attempts before again blocking

**Comment by qdm12** [comment] 2022-04-26 13:47
Please try with v3.28.2 and let me know if it works first 😉 If it does work, it might be due to the compression option that changed on the latest image.

**Comment by qdm12** [comment] 2022-04-26 13:49
> Another possibility is that the client reconnecting is triggering a failed auth after multiple attempts, triggered by healthcheck

That could be. Although this means gluetun failed 5 times (1 per second) to dial Cloudflare.com so the connection was probably down 🤔 You could increase the wait time before reconnecting (see the wiki health options page) if that can help?

**Comment by oenu** [comment] 2022-04-26 13:59
> Please try with v3.28.2 and let me know if it works first 😉 If it does work, it might be due to the compression option that changed on the latest image.

Sorry is that the Alpine version or the version of your image?

**Comment by qdm12** [comment] 2022-04-26 15:12
Are you sure? Please try on different servers to make sure it's fully working on v3.28.2 and not just a random success. If it works, then I'll revert back the compression option that was changed a few days ago.

**Comment by oenu** [comment] 2022-04-26 16:02
Wanted to be extra sure, just switched back again to V3.28.2 and its good, I cant say what the issue is but that version works with my setup!

**Comment by eXunit** [comment] 2022-04-27 00:20
> Just switched to a server in the US on V3.28.2 and its working just fine, switched to `latest` and im getting the same
> 
> ```
> gluetun        | 2022-04-26T11:54:01-04:00 WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.8.3.3:48375->1.1.1.1:53: i/o timeout
> gluetun        | 2022-04-26T11:54:01-04:00 INFO [dns over tls] attempting restart in 20s
> ```
> 
> as before

Yes, I had to recreate the docker as:
sudo docker run -d --name gluetun --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=nordvpn \
-e OPENVPN_USER=Ume3637mRagdUeeSioBdhvL8 -e OPENVPN_PASSWORD=8wXWquHAXwawwKXYCBpErdsn \
-e SERVER_REGIONS=Netherlands qmcgaw/gluetun:v3.28.2

**Comment by eXunit** [comment] 2022-04-27 00:22
> Just switched to a server in the US on V3.28.2 and its working just fine, switched to `latest` and im getting the same
> 
> ```
> gluetun        | 2022-04-26T11:54:01-04:00 WARN [dns over tls] cannot update files: Get "https://www.internic.net/domain/named.root": dial tcp: lookup www.internic.net on 1.1.1.1:53: read udp 10.8.3.3:48375->1.1.1.1:53: i/o timeout
> gluetun        | 2022-04-26T11:54:01-04:00 INFO [dns over tls] attempting restart in 20s
> ```
> 
> as before

Yes I had to recreate the docker:

NORDVPN-version 3.28.2
sudo docker run -d --name gluetun --cap-add=NET_ADMIN -e VPN_SERVICE_PROVIDER=nordvpn \
-e OPENVPN_USER=XXX -e OPENVPN_PASSWORD=XXX \
-e SERVER_REGIONS=Netherlands qmcgaw/gluetun:v3.28.2

**Comment by qdm12** [comment] 2022-04-27 09:23
Can you guys try `qmcgaw/gluetun:964`? It's the same as the latest image with `comp-lzo no` removed (so it defaults to whatever the server proposes). Note I only built it for amd64. If it works, I'll revert that for the latest image.

**Comment by qdm12** [comment] 2022-04-27 10:05
@Sturlen If v3.28.2 is failing as well, then it's likely a problem on Nordvpn servers. Note the dns over tls errors are just consequences of the VPN not working, and not causes.

 @oenu can you please try a few servers on `:964` and `v3.28.2` to make it works consistently compared to the latest image?

**Comment by Sturlen** [comment] 2022-04-27 10:43
NordVPN seems to be having issues with their OpenVPN servers. Tried on multiple machines with the same result until I switched to another provider. After that everything worked as normal.

**Comment by starlord998** [comment] 2022-04-27 11:58
I was having the same issue starting yesterday. I did move to v3.28.2 and it seems to have fixed the issue for now.

**Comment by Mereks** [comment] 2022-04-27 12:15
I switched to v3.28.2 and it is working for me as well.

**Comment by oenu** [comment] 2022-04-27 17:39
@qdm12 Just at work rn, have seen this, will report back

**Comment by qdm12** [comment] 2022-04-27 18:44
@urwrstkn8mare please `docker pull qmcgaw/gluetun:964` and try again? I restored `comp-lzo` in there (previously I just changed from `comp-lzo no` to no `comp-lzo` option at all), let's see if it works.

**Comment by Mereks** [comment] 2022-04-27 19:01
Same problem as before with 964 =(

**Comment by Mereks** [comment] 2022-04-27 19:32
964 still not working for me. Could it have something to do with [a1d70f7](https://github.com/qdm12/gluetun/commit/a1d70f740a1104808ea910c1c32e543eadbffd16)? I'd say that's about the time it stopped working for me. Thanks in advance for all the help regardless!

**Comment by urwrstkn8mare** [comment] 2022-04-27 20:55
> Another possibility is that the client reconnecting is triggering a failed auth after multiple attempts, triggered by healthcheck. After logging into their site with my credentials it seemed to allow further connection attempts before again blocking

I think this may have also caused problems. Is there a way to disable retries at least for testing?

**Comment by urwrstkn8mare** [comment] 2022-04-27 20:56
> @urwrstkn8mare please `docker pull qmcgaw/gluetun:964` and try again? I restored `comp-lzo` in there (previously I just changed from `comp-lzo no` to no `comp-lzo` option at all), let's see if it works.

Will do.

**Comment by qdm12** [comment] 2022-04-27 20:58
I re-pushed it, this time removing the aes-256-gcm as an option. Otherwise feel free to try setting i.e. `OPENVPN_CIPHERS=aes-256-cbc`, `OPENVPN_FLAGS=--comp-lzo` to override the defaults set.

Also sorry this change(s) affected so many of you!

**Comment by Mereks** [comment] 2022-04-27 21:16
964 worked as is this time!

**Comment by qdm12** [comment] 2022-04-28 08:21
Awesome, thanks.

1. Please pull `:964` again (digest `sha256:2af979f02176dbc0d619840968a3892e422a3a962489e9e508b868433b2804ce`), does it work? I re-added `comp-lzo no` but flipped the order of ciphers around from `aes-256-gcm aes-256-cbc` to `aes-256-cbc aes-256-gcm`.
2. If it doesn't work, does that image work with `-e OPENVPN_CIPHERS=aes-256-cbc` (to remove the gcm variant)?
3. If that doesn't work as well, does it work with `-e OPENVPN_FLAGS="--comp-lzo"`?

And that should finally nail down what's the required settings for Nordvpn. Thanks in advance

**Comment by 5haamu** [comment] 2022-04-28 08:50
:964 is working for me too, thanks heaps :)

**Comment by qdm12** [comment] 2022-04-28 10:38
@5haamu Which 964 😄 You can find it with `docker images --digests`

**Comment by Mereks** [comment] 2022-04-28 11:16
My docker-fu is weak but I can confirm I am on `3b2804ce` and it still works. Glad that got sorted out! Thanks again!

**Comment by qdm12** [comment] 2022-04-28 13:48
Awesome b6de6035f644402dae7fd2bfe12ab70edff132ce should fix for the latest image. Please let me know if it works/doesn't. I'll wait 1-2 days and then finally make that v3.29.0 release. Closing the issue for now! Thank you again everyone!

**Comment by aprate** [comment] 2022-04-28 13:49
qmcgaw/gluetun                      964                       sha256:2af979f02176dbc0d619840968a3892e422a3a962489e9e508b868433b2804ce   e351f67da710   6 hours ago     29.8MB

Works out of the box. Latest did not. Thanks!

**Closed by qdm12** 2022-04-28 13:48 UTC

**Comment by qdm12** [comment] 2022-04-28 14:09
Latest maybe wasn't built by the Github build pipeline already.
I just tried and got:

```
docker pull qmcgaw/gluetun                                                                                                                                                                                                                    ✔ 
Using default tag: latest
latest: Pulling from qmcgaw/gluetun
df9b9388f04a: Already exists 
4fe34d2c8a41: Pull complete 
a02ae07ffd46: Pull complete 
Digest: sha256:907b35d16629a38b0b1dbe537fa44ac6154363c1dd75cf4246b1c19f113a51c6
Status: Downloaded newer image for qmcgaw/gluetun:latest
docker.io/qmcgaw/gluetun:latest
```

So maybe try re-pulling it?

**Comment by qdm12** [comment] 2022-04-29 09:40
So this is fixed on `qmcgaw/gluetun:latest` right?

**Comment by aprate** [comment] 2022-04-29 10:32
Sorry, for the late response. 
Latest: a51c6 works great now!

**Comment by oenu** [comment] 2022-05-02 22:24
Sorry for delay, tried this on latest and im getting auth failed again

**Comment by qdm12** [comment] 2022-05-03 01:05
@oenu

1. Try with `-e OPENVPN_CIPHERS=aes-256-cbc` (to remove the gcm variant)?
2. If that doesn't work as well, does it work with `-e OPENVPN_FLAGS="--comp-lzo"`?

You can mix and matching these two to see what combo works?

**Comment by urwrstkn8mare** [comment] 2022-05-03 13:28
> Sorry for delay, tried this on latest and im getting auth failed again

also i think it should be noted sometimes you should wait a while after disconnecting from nordvpn to reconnect from my experience (i don't actually know for sure)

**Comment by ornic** [comment] 2023-01-13 13:03
@qdm12 
> You can mix and matching these two to see what combo works?

This solved AUTH_FAIL for ProtonVPN (yesss, offtopic) for me! :)

**Comment by DieSchoeneWolke** [comment] 2023-01-23 09:38
I get the issue when my connection drops after the daily disconnect coming from my ISP. 
Restarting the container won't help only a rebuild in which my connected containers need to be rebuild again as well, since they lose the container name for the network.
