### ISSUE TITLE
Bug: Stuck in Unhealthy status, requires manual container restart

### ISSUE THREAD

**Issue by ansred** [qdm12/gluetun#518] opened 2021-07-09 10:30 UTC
**Is this urgent?**: No

**Host OS** (approximate answer is fine too): piOS

**CPU arch** or **device name**: arm Raspberry PI 4 - 8 GB

**What VPN provider are you using**: Mullvad

**What are you using to run your container?**: Docker Compose - Portainer

**What is the version of the program** (See the line at the top of your logs)

```
R2021-07-03T11:01:50.738468377Z Running version latest built on 2021-07-01T18:34:18Z (commit 92212fd)
```

**What's the problem** 🤔

Randomly gets stuck in Unhealthy status

2021/07/08 12:18:22 INFO healthcheck: unhealthy: lookup github.com on 127.0.0.1:53: server misbehaving
2021/07/08 12:18:22 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
2021/07/08 12:18:28 WARN openvpn: unhealthy program: restarting openvpn

And requires manual restart

**Share your logs... (careful to remove in example tokens)**

```log

2021/07/08 12:18:22 INFO healthcheck: unhealthy: lookup github.com on 127.0.0.1:53: server misbehaving
2021/07/08 12:18:22 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
2021/07/08 12:18:28 WARN openvpn: unhealthy program: restarting openvpn

```

Complete log file attached
>> 6d386d6c6160.log.gz
[6d386d6c6160.log.gz](https://github.com/qdm12/gluetun/files/6790625/6d386d6c6160.log.gz)

After manual restart, everything is healthy and running normal

```
today at 6:26:53 AM Container stopped
today at 6:26:57 AM Container started
today at 6:26:53 AM 	github.com/qdm12/gluetun/internal/openvpn/loop.go:171 +0x58c
today at 6:26:57 AM =========================================
today at 6:26:57 AM ================ Gluetun ================
today at 6:26:57 AM =========================================
today at 6:26:57 AM ==== A mix of OpenVPN, DNS over TLS, ====
today at 6:26:57 AM ======= Shadowsocks and HTTP proxy ======
today at 6:26:57 AM ========= all glued up with Go ==========
today at 6:26:57 AM =========================================
today at 6:26:57 AM =========== For tunneling to ============
today at 6:26:57 AM ======== your favorite VPN server =======
today at 6:26:57 AM =========================================
today at 6:26:57 AM === Made with ❤️ by github.com/qdm12 ====
today at 6:26:57 AM =========================================
today at 6:26:57 AM
today at 6:26:57 AM Running version latest built on 2021-07-01T18:34:18Z (commit 92212fd)
today at 6:26:57 AM
today at 6:26:57 AM
today at 6:26:57 AM 🔧 Need help? https://github.com/qdm12/gluetun/issues/new
today at 6:26:57 AM 💻 Email? quentin.mcgaw@gmail.com
today at 6:26:57 AM ☕ Slack? Join from the Slack button on Github
today at 6:26:57 AM 💰 Help me? https://github.com/sponsors/qdm12
today at 6:26:57 AM 2021/07/09 06:26:57 INFO Alpine version: 3.14.0
today at 6:26:57 AM 2021/07/09 06:26:57 INFO OpenVPN 2.4 version: 2.4.11
today at 6:26:57 AM 2021/07/09 06:26:57 INFO OpenVPN 2.5 version: 2.5.2
today at 6:26:57 AM 2021/07/09 06:26:57 INFO Unbound version: 1.13.1
today at 6:26:57 AM 2021/07/09 06:26:57 INFO IPtables version: v1.8.7
today at 6:26:57 AM 2021/07/09 06:26:57 INFO Settings summary below:
today at 6:26:57 AM |--OpenVPN:
today at 6:26:57 AM    |--Version: 2.5
today at 6:26:57 AM    |--Verbosity level: 1
today at 6:26:57 AM    |--Run as root: enabled
today at 6:26:57 AM    |--Provider:
today at 6:26:57 AM       |--Mullvad settings:
today at 6:26:57 AM          |--Network protocol: tcp
today at 6:26:57 AM          |--Countries: spain
today at 6:26:57 AM          |--Cities: madrid
today at 6:26:57 AM          |--Custom port: 443
today at 6:26:57 AM |--DNS:
today at 6:26:57 AM    |--Plaintext address: 1.1.1.1
today at 6:26:57 AM    |--DNS over TLS:
today at 6:26:57 AM       |--Unbound:
today at 6:26:57 AM           |--DNS over TLS providers:
today at 6:26:57 AM               |--Cloudflare
today at 6:26:57 AM           |--Listening port: 53
today at 6:26:57 AM           |--Access control:
today at 6:26:57 AM               |--Allowed:
today at 6:26:57 AM                   |--0.0.0.0/0
today at 6:26:57 AM                   |--::/0
today at 6:26:57 AM           |--Caching: enabled
today at 6:26:57 AM           |--IPv4 resolution: enabled
today at 6:26:57 AM           |--IPv6 resolution: disabled
today at 6:26:57 AM           |--Verbosity level: 1/5
today at 6:26:57 AM           |--Verbosity details level: 0/4
today at 6:26:57 AM           |--Validation log level: 0/2
today at 6:26:57 AM           |--Username: 
today at 6:26:57 AM       |--Blacklist:
today at 6:26:57 AM          |--Blocked categories: malicious
today at 6:26:57 AM          |--Additional IP networks blocked: 13
today at 6:26:57 AM       |--Update: every 24h0m0s
today at 6:26:57 AM |--Firewall:
today at 6:26:57 AM    |--VPN input ports: 54823
today at 6:26:57 AM |--System:
today at 6:26:57 AM    |--Process user ID: 1000
today at 6:26:57 AM    |--Process group ID: 1000
today at 6:26:57 AM    |--Timezone: america/toronto
today at 6:26:57 AM |--HTTP control server:
today at 6:26:57 AM    |--Listening port: 8000
today at 6:26:57 AM    |--Logging: enabled
today at 6:26:57 AM |--Public IP getter:
today at 6:26:57 AM    |--Fetch period: 12h0m0s
today at 6:26:57 AM    |--IP file: /tmp/gluetun/ip
today at 6:26:57 AM |--Github version information: enabled
today at 6:26:57 AM 2021/07/09 06:26:57 INFO storage: merging by most recent 11186 hardcoded servers and 11186 servers read from /gluetun/servers.json
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: default route found: interface eth0, gateway 172.21.0.1
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: local ethernet link found: eth0
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: local ipnet found: 172.21.0.0/16
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: default route found: interface eth0, gateway 172.21.0.1
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: adding route for 0.0.0.0/0
today at 6:26:58 AM 2021/07/09 06:26:58 INFO firewall: firewall disabled, only updating allowed subnets internal list
today at 6:26:58 AM 2021/07/09 06:26:58 INFO routing: default route found: interface eth0, gateway 172.21.0.1
today at 6:26:58 AM 2021/07/09 06:26:58 INFO openvpn configurator: checking for device /dev/net/tun
today at 6:26:58 AM 2021/07/09 06:26:58 WARN TUN device is not available: open /dev/net/tun: no such file or directory
today at 6:26:58 AM 2021/07/09 06:26:58 INFO openvpn configurator: creating /dev/net/tun
today at 6:26:58 AM 2021/07/09 06:26:58 INFO firewall: enabling...
today at 6:26:58 AM 2021/07/09 06:26:58 INFO firewall: enabled successfully
today at 6:26:58 AM 2021/07/09 06:26:58 INFO firewall: setting allowed input port 54823 through interface tun0...
today at 6:26:58 AM 2021/07/09 06:26:58 INFO dns over tls: using plaintext DNS at address 1.1.1.1
today at 6:26:58 AM 2021/07/09 06:26:58 INFO healthcheck: listening on 127.0.0.1:9999
today at 6:26:58 AM 2021/07/09 06:26:58 INFO http server: listening on :8000
today at 6:26:58 AM 2021/07/09 06:26:58 INFO firewall: setting VPN connection through firewall...
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn configurator: starting OpenVPN 2.5
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: OpenVPN 2.5.2 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: library versions: OpenSSL 1.1.1k  25 Mar 2021, LZO 2.10
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]45.152.183.42:443
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: Attempting to establish TCP connection with [AF_INET]45.152.183.42:443 [nonblock]
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: TCP connection established with [AF_INET]45.152.183.42:443
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: TCP_CLIENT link local: (not bound)
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: TCP_CLIENT link remote: [AF_INET]45.152.183.42:443
today at 6:26:59 AM 2021/07/09 06:26:59 WARN openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1559', remote='link-mtu 1560'
today at 6:26:59 AM 2021/07/09 06:26:59 WARN openvpn: 'comp-lzo' is present in remote config but missing in local config, remote='comp-lzo'
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: [es-mad-005.mullvad.net] Peer Connection Initiated with [AF_INET]45.152.183.42:443
today at 6:26:59 AM 2021/07/09 06:26:59 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
today at 6:27:02 AM 2021/07/09 06:27:02 INFO openvpn: TUN/TAP device tun0 opened
today at 6:27:02 AM 2021/07/09 06:27:02 INFO openvpn: /sbin/ip link set dev tun0 up mtu 1500
today at 6:27:02 AM 2021/07/09 06:27:02 INFO openvpn: /sbin/ip link set dev tun0 up
today at 6:27:02 AM 2021/07/09 06:27:02 INFO openvpn: /sbin/ip addr add dev tun0 10.5.0.2/16
today at 6:27:02 AM 2021/07/09 06:27:02 INFO openvpn: Initialization Sequence Completed
today at 6:27:02 AM 2021/07/09 06:27:02 INFO VPN routing IP address: 45.152.183.42
today at 6:27:02 AM 2021/07/09 06:27:02 INFO dns over tls: downloading DNS over TLS cryptographic files
today at 6:27:03 AM 2021/07/09 06:27:03 INFO healthcheck: healthy!
today at 6:27:06 AM 2021/07/09 06:27:06 INFO dns over tls: downloading hostnames and IP block lists
today at 6:27:09 AM 2021/07/09 06:27:09 INFO dns over tls: init module 0: validator
today at 6:27:09 AM 2021/07/09 06:27:09 INFO dns over tls: init module 1: iterator
today at 6:27:09 AM 2021/07/09 06:27:09 INFO dns over tls: start of service (unbound 1.13.1).
today at 6:27:10 AM 2021/07/09 06:27:10 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
today at 6:27:10 AM 2021/07/09 06:27:10 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
today at 6:27:13 AM 2021/07/09 06:27:13 INFO dns over tls: ready
today at 6:27:15 AM 2021/07/09 06:27:15 INFO You are running 1 commit behind the most recent latest
today at 6:27:22 AM 2021/07/09 06:27:22 INFO ip getter: Public IP address is 45.152.183.46 (Spain, Madrid, Madrid)

```

![image](https://user-images.githubusercontent.com/5244872/125064807-09834b80-e07f-11eb-9b8c-12f3d0d26fd8.png)

**Comment by qdm12** [comment] 2021-07-09 15:44
Duplicate of #389 please subscribe to it instead. But fear not, I'll use your logs and information as well!

I need to address this soon, it's most likely due to a deadlock/race condition in the code.

It's quite heavily asynchronous with locks everywhere such that it can really be tweaked on demand and without data races, but that adds also a lot of complexity sadly...

**Closed by qdm12** 2021-07-09 15:44 UTC

**Comment by qdm12** [comment] 2021-07-16 21:31
Try pulling `:latest` it should now have all this fixed (see https://github.com/qdm12/gluetun/issues/389#issuecomment-881726792)

**Comment by ansred** [comment] 2021-07-24 19:51
@qdm12 

So it has been a week running smooth, until today it happened again

![image](https://user-images.githubusercontent.com/5244872/126879581-ad769122-81ff-453b-ad14-dddae1b3c793.png)

Stuck at

```
yesterday at 8:04:37 AM 2021/07/23 08:04:37 INFO http server: 200 GET /ip wrote 32B to 10.0.12.16:34624 in 29.037µs
yesterday at 9:20:12 AM 2021/07/23 09:20:12 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 11:08:16 AM 2021/07/23 11:08:16 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 12:50:15 PM 2021/07/23 12:50:15 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 2:44:25 PM 2021/07/23 14:44:25 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 4:32:29 PM 2021/07/23 16:32:29 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 6:20:38 PM 2021/07/23 18:20:38 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 8:08:47 PM 2021/07/23 20:08:47 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
yesterday at 10:00:14 PM 2021/07/23 22:00:14 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
today at 12:39:07 AM 2021/07/24 00:39:07 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
today at 12:39:07 AM 2021/07/24 00:39:07 INFO dns over tls: generate keytag query _ta-4a5c-4f66. NULL IN
today at 2:33:25 AM 2021/07/24 02:33:25 INFO healthcheck: unhealthy: lookup github.com on 127.0.0.1:53: read udp 127.0.0.1:38654->127.0.0.1:53: i/o timeout
today at 2:33:25 AM 2021/07/24 02:33:25 INFO openvpn: unhealthy program: waiting 6s for it to change to healthy
today at 2:33:31 AM 2021/07/24 02:33:31 WARN openvpn: unhealthy program: restarting openvpn
today at 8:04:35 AM 2021/07/24 08:04:35 INFO http server: 200 GET /ip wrote 32B to 10.0.12.16:39870 in 31.388µs
```



Version:
`07/16/2021, 11:42 PM Running version latest built on 2021-07-16T21:27:00Z (commit 7e50c95)`



Pulled the latest image just now, which I thought I did, and will test again

`today at 3:50:50 PM Running version latest built on 2021-07-23T20:51:51Z (commit 7e343d7)`

**Comment by qdm12** [comment] 2021-07-24 20:47
I reworked a lot of the asynchronous logic for openvpn yesterday (again), hopefully it's no longer bugged.

I also re-tested latest by restarting a mocked openvpn (`echo "Initialization Sequence Completed" && sleep 100`) every 100ms:

- in a user triggered ticker fashion with `-e FIREWALL=off` such that it's never unhealthy
- in a health restart fashion with `-e HEALTH_OPENVPN_DURATION_INITIAL=100ms -e HEALTH_OPENVPN_DURATION_ADDITION=0`

And it's working so far (ran it for 1 minute, should be enough).

**Comment by ansred** [comment] 2021-07-24 21:58
Thanks I will testing and monitoring!

**Comment by nearcatch** [comment] 2021-07-25 17:31
> I reworked a lot of the asynchronous logic for openvpn yesterday (again), hopefully it's no longer bugged.
> 
> I also re-tested latest by restarting a mocked openvpn (`echo "Initialization Sequence Completed" && sleep 100`) every 100ms:
> 
>     * in a user triggered ticker fashion with `-e FIREWALL=off` such that it's never unhealthy
> 
>     * in a health restart fashion with `-e HEALTH_OPENVPN_DURATION_INITIAL=100ms -e HEALTH_OPENVPN_DURATION_ADDITION=0`
> 
> 
> And it's working so far (ran it for 1 minute, should be enough).

fwiw, I was about to open an issue that Windscribe gluetun containers were unhealthy, but using :latest instead of :v3.20.0 solves the issue. Hoping for a :v3.21.0 tag soon.
