### ISSUE TITLE
Bug: Torguard OpenVPN is not working

### ISSUE THREAD

**Issue by bartje885** [qdm12/gluetun#712] opened 2021-11-17 07:24 UTC
### Is this urgent?

No

### Host OS

Debian

### CPU arch

x86_64

### VPN service provider

TorGuard

### What are you using to run the container

Portainer

### What is the version of Gluetun

Latest version

### What's the problem 🤔

I have a Torguard VPN subscription, but when I create the container using docker compose, it gets unhealthy and keeps reconnecting to the vpn service without any luck.

When I use my friend's Private internet access credentials it works like a charm. 

Last output from Portainer: 2021/11/17 07:12:20 ERROR HTTP response status is not OK: 500 Internal Server Error: lookup github.com on 1.1.1.1:53: write udp 172.23.0.2:57854->1.1.1.1:53: write: operation not permitted 2021/11/17 07:12:20 INFO Shutdown successful

### Share your logs

```log
3. Your Internet connection is not working 🤯, ensure it works


4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose

2021/11/17 07:19:46 INFO openvpn: TLS Error: TLS handshake failed

2021/11/17 07:19:46 INFO openvpn: SIGTERM received, sending exit notification to peer

2021/11/17 07:19:46 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting

2021/11/17 07:19:46 INFO vpn: retrying in 15s

2021/11/17 07:19:52 INFO healthcheck: program has been unhealthy for 1m6s: restarting VPN

2021/11/17 07:20:01 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:20:01 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:20:01 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:20:01 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.13:1912

2021/11/17 07:20:01 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:20:01 INFO openvpn: UDP link remote: [AF_INET]206.217.216.13:1912

2021/11/17 07:21:01 WARN openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒

That error usually happens because either:


1. The VPN server IP address you are trying to connect to is no longer valid 🔌

   Update your server information using https://github.com/qdm12/gluetun/wiki/Updating-Servers


2. The VPN server crashed 💥, try changing your VPN servers filtering options such as REGION


3. Your Internet connection is not working 🤯, ensure it works


4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose

2021/11/17 07:21:01 INFO openvpn: TLS Error: TLS handshake failed

2021/11/17 07:21:01 INFO openvpn: SIGTERM received, sending exit notification to peer

2021/11/17 07:21:01 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting

2021/11/17 07:21:01 INFO vpn: retrying in 15s

2021/11/17 07:21:12 INFO healthcheck: program has been unhealthy for 1m11s: restarting VPN

2021/11/17 07:21:16 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:21:16 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:21:16 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:21:16 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.4:1912

2021/11/17 07:21:16 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:21:16 INFO openvpn: UDP link remote: [AF_INET]206.217.216.4:1912

2021/11/17 07:22:17 WARN openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒

That error usually happens because either:


1. The VPN server IP address you are trying to connect to is no longer valid 🔌

   Update your server information using https://github.com/qdm12/gluetun/wiki/Updating-Servers


2. The VPN server crashed 💥, try changing your VPN servers filtering options such as REGION


3. Your Internet connection is not working 🤯, ensure it works


4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose

2021/11/17 07:22:17 INFO openvpn: TLS Error: TLS handshake failed

2021/11/17 07:22:17 INFO openvpn: SIGTERM received, sending exit notification to peer

2021/11/17 07:22:17 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting

2021/11/17 07:22:17 INFO vpn: retrying in 15s

2021/11/17 07:22:32 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:22:32 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:22:32 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:22:32 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.17:1912

2021/11/17 07:22:32 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:22:32 INFO openvpn: UDP link remote: [AF_INET]206.217.216.17:1912

2021/11/17 07:22:32 INFO healthcheck: program has been unhealthy for 1m16s: restarting VPN

2021/11/17 07:22:32 INFO vpn: stopping

2021/11/17 07:22:32 INFO vpn: starting

2021/11/17 07:22:32 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:22:32 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:22:32 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:22:32 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.9:1912

2021/11/17 07:22:32 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:22:32 INFO openvpn: UDP link remote: [AF_INET]206.217.216.9:1912

2021/11/17 07:23:32 WARN openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)

🚒🚒🚒🚒🚒🚨🚨🚨🚨🚨🚨🚒🚒🚒🚒🚒

That error usually happens because either:


1. The VPN server IP address you are trying to connect to is no longer valid 🔌

   Update your server information using https://github.com/qdm12/gluetun/wiki/Updating-Servers


2. The VPN server crashed 💥, try changing your VPN servers filtering options such as REGION


3. Your Internet connection is not working 🤯, ensure it works


4. Something else ➡️ https://github.com/qdm12/gluetun/issues/new/choose

2021/11/17 07:23:32 INFO openvpn: TLS Error: TLS handshake failed

2021/11/17 07:23:32 INFO openvpn: SIGTERM received, sending exit notification to peer

2021/11/17 07:23:32 INFO openvpn: SIGTERM[soft,tls-error] received, process exiting

2021/11/17 07:23:32 INFO vpn: retrying in 15s

2021/11/17 07:23:47 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:23:47 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:23:47 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:23:47 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.15:1912

2021/11/17 07:23:47 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:23:47 INFO openvpn: UDP link remote: [AF_INET]206.217.216.15:1912

2021/11/17 07:23:53 INFO healthcheck: program has been unhealthy for 1m21s: restarting VPN

2021/11/17 07:23:53 INFO vpn: stopping

2021/11/17 07:23:53 INFO vpn: starting

2021/11/17 07:23:53 INFO firewall: setting VPN connection through firewall...

2021/11/17 07:23:53 INFO openvpn: OpenVPN 2.5.2 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  4 2021

2021/11/17 07:23:53 INFO openvpn: library versions: OpenSSL 1.1.1l  24 Aug 2021, LZO 2.10

2021/11/17 07:23:53 INFO openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]206.217.216.13:1912

2021/11/17 07:23:53 INFO openvpn: UDP link local: (not bound)

2021/11/17 07:23:53 INFO openvpn: UDP link remote: [AF_INET]206.217.216.13:1912
```

### Share your configuration

```yml
Docker-compose script for torguard: https://jpst.it/2GdGM
Docker-compose script for pia: https://jpst.it/2GdHo
```

**Comment by qdm12** [comment] 2021-11-17 09:14
Did you try different server regions?

If they all (more or less) error similarly, that might be because they changed their configuration.
Can you share one openvpn configuration to check the values I have in the program? (remove your username+password if they're inside)

Alternatively I think you can use Wireguard until this gets resolved, see the custom provider in the wiki

**Comment by bartje885** [comment] 2021-11-17 11:47
Hi, thanks for your fast comment, I will try the wireguard setup next week when I have some more time. How can I provide the openvpn config? Should I download those from Torguard website?

**Comment by qdm12** [comment] 2021-11-18 09:33
Where do you get those openvpn configuration files from? Maybe try to find a public link you could download a zip of all servers from. Gluetun gets them from `https://torguard.net/downloads/new/OpenVPN-UDP-Linux.zip` and `https://torguard.net/downloads/new/OpenVPN-TCP-Linux.zip` for now and I'd like to keep the update mechanism automated.

**Comment by bartje885** [comment] 2021-11-18 12:16
I generated those conf files in my Torguard portal. So I think the links that you provided are outdated and not yet updated by Torguard. I tried the Wireguard config and it works like a charm.

**Comment by qdm12** [comment] 2021-11-18 21:28
Re-opening since OpenVPN is also meant to be working for it.

I updated the server data replacing `torguardvpnaccess` with `torguard`. Some servers are no longer there using this replacement, but `nl.torguardvpnaccess.com` and `nl.torguard.com` resolve to the same IP addresses, so I doubt the hostname is the cause. The files are also identical concerning options, except perhaps `setenv CLIENT_CERT 0` which is not in the gluetun generated config.

Can you try again with OpenVPN and using `OPENVPN_VERBOSITY=3`? Also please share your full logs from the top so I can see what settings you have (your credentials are not logged).

**Comment by bartje885** [comment] 2021-11-19 07:54
See attachement for the logfile. In the servers.json I still found:

        "country": "Netherlands",
        "city": "",
        "hostname": "nl.torguardvp
[_vpnserver2_logs.txt](https://github.com/qdm12/gluetun/files/7568634/_vpnserver2_logs.txt)
naccess.com",

But like you said, that won't probably the issue.

**Comment by MidgetBrony** [comment] 2021-11-21 20:45
Actually I was having a few issues myself in the latest update, I actually had to change the CIPHER to get it to work properly,

     - OPENVPN_CIPHER=aes-128-cbc
 
IDK if that could be the problem, but its what I had to do to get it to work properly again.

**Comment by bartje885** [comment] 2021-11-21 21:03
> Actually I was having a few issues myself in the latest update, I actually had to change the CIPHER to get it to work properly,
> 
> ```
>  - OPENVPN_CIPHER=aes-128-cbc
> ```
> 
> IDK if that could be the problem, but its what I had to do to get it to work properly again.

Can you share your config, I added your suggetion but it's still not working

**Comment by bartje885** [comment] 2021-11-21 21:07
I tried with UK as server and it works.. Netherlands doesn't work. So my config is:

version: "3"
services:
  vpnserver2:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN  
    volumes:
      - /srv/dev-disk-by-label-Share7TB/Docker/vpnserver2:/gluetun
    environment:
      - VPNSP=torguard
      - OPENVPN_USER=abc
      - OPENVPN_PASSWORD=def
      - COUNTRY=UK
      - OPENVPN_VERBOSITY=3
      - OPENVPN_CIPHER=aes-128-cbc

**Comment by MidgetBrony** [comment] 2021-11-21 21:17
Yeah sure I can show my config:

version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8998:8000 
      - 9117:9117 
      - 8112:8112 
      - 58846:58846
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
      - 1028:8080
      - 1029:9090
    environment:
      - VPNSP=torguard
      - OPENVPN_USER=<NULL>
      - OPENVPN_PASSWORD=<NULL>
      - TZ=Europe/Oslo
      - UID=1000
      - GID=1000
      - OPENVPN_CIPHER=aes-128-cbc
      - COUNTRY:Norway,Denmark,Sweden,Iceland,Finland
    volumes:
      - ~/vpn-setup:/gluetun
    dns:
      - 104.223.91.194
      - 104.223.91.210
    restart: always

**Comment by qdm12** [comment] 2021-11-22 21:14
Time to contact their support :smile_cat: I'll close the issue for now, but feel free to comment back here once it's working or if I should do anything on my side to fix it. Cheers!

**Closed by qdm12** 2021-11-22 21:14 UTC

**Comment by JermellB** [comment] 2023-10-14 21:15
> I tried with UK as server and it works.. Netherlands doesn't work. So my config is:
> 
> ```yaml
> version: "3"
> services:
>   vpnserver2:
>     image: qmcgaw/gluetun:latest
>     cap_add:
>       - NET_ADMIN  
>     volumes:
>       - /srv/dev-disk-by-label-Share7TB/Docker/vpnserver2:/gluetun
>     environment:
>       - VPNSP=torguard
>       - OPENVPN_USER=abc
>       - OPENVPN_PASSWORD=def
>       - COUNTRY=UK
>       - OPENVPN_VERBOSITY=3
>       - OPENVPN_CIPHER=aes-128-cbc
> ```

Thanks, this got it working for me after a few hours of digging.
