### ISSUE TITLE
Bug: OpenVPN no client-side authentication method is specified.

### ISSUE THREAD

**Issue by ezekieldas** [qdm12/gluetun#2217] opened 2024-04-08 21:37 UTC
### Is this urgent?

Yes

### Host OS

Ubuntu 22.04.4

### CPU arch

x86_64

### VPN service provider

Mullvad

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2024-04-08T07:43:05.096Z (commit 7b4befc)

### What's the problem 🤔

I'm near certain this is a new bug. I have no openvpn configuration. I can't spot it exactly (go weakling here) but there are references to openvpn here: [7b4befc](https://github.com/qdm12/gluetun/commit/7b4befce61a56d945c3558188d79a856ba22880a) 

qmcgaw/gluetun:latest (note digest match):

```
docker image inspect `docker images -q qmcgaw/gluetun:latest`  | jq '.[].RepoDigests[]'
"qmcgaw/gluetun@sha256:b0d2bc4af64934b68a8479bf66f5dba12143ede03beeb17740f634728ee3ce80"
```

https://hub.docker.com/layers/qmcgaw/gluetun/latest/images/sha256-bfcf38ffbfbb2f5668e9f718e461b013ca6917129df34ae7a76ad5343fcf35fe?context=explore

I just turned on `LOG_LEVEL=debug` to get more details. Will update when available. 

Also, will determine if there's a tag to use to avoid this. Could be `qmcgaw/gluetun:v3`

### Share your logs (at least 10 lines)

```plain text
2024-04-08T21:07:02Z INFO [http server] 200 GET /ip wrote 17B to 10.10.10.1:55170 in 50.643µs
2024-04-08T21:07:03Z INFO [firewall] allowing VPN connection...
2024-04-08T21:07:03Z ERROR [openvpn] No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass
2024-04-08T21:07:03Z INFO [openvpn] Use --help for more information.
2024-04-08T21:07:03Z ERROR [vpn] exit status 1
2024-04-08T21:07:03Z INFO [vpn] retrying in 30s
2024-04-08T21:07:03Z INFO [http server] 200 GET /ip wrote 17B to 10.10.10.1:55180 in 36.99µs
2024-04-08T21:07:04Z INFO [http server] 200 GET /ip wrote 17B to 10.10.10.1:55184 in 37.82µs
2024-04-08T21:07:05Z INFO [http server] 200 GET /ip wrote 17B to 10.10.10.1:55198 in 55.216µs
2024-04-08T21:07:09Z INFO [healthcheck] program has been unhealthy for 10s: restarting VPN
2024-04-08T21:07:09Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-04-08T21:07:09Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-04-08T21:07:28Z INFO [healthcheck] program has been unhealthy for 17s: restarting VPN
2024-04-08T21:07:28Z INFO [healthcheck] 👉 See https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
2024-04-08T21:07:28Z INFO [healthcheck] DO NOT OPEN AN ISSUE UNLESS YOU READ AND TRIED EACH POSSIBLE SOLUTION
2024-04-08T21:07:33Z INFO [firewall] allowing VPN connection...
2024-04-08T21:07:33Z ERROR [openvpn] No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass
2024-04-08T21:07:33Z INFO [openvpn] Use --help for more information.
2024-04-08T21:07:33Z ERROR [vpn] exit status 1
2024-04-08T21:07:33Z INFO [vpn] retrying in 1m0s
```

### Share your configuration

```yml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    dns:
      - 127.0.0.1
    networks:
      - gluetun_net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000/tcp # control server - https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
      - 8008:8888/tcp # HTTP proxy - https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/http-proxy.md
      - 6666:9999/tcp # healthcheck - https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md#internal-healthcheck
      - 8053:53/tcp # blocky
      - 8053:53/udp # blocky
      - 9110:4000/tcp   # blocky prometheus exporter
    volumes:
      - /usr/local/docker/gluetun/gluetun_config:/gluetun
      - /usr/local/docker/gluetun/gluetun_config/post-rules.txt:/iptables/post-rules.txt

    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      #
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md
      #
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      # - FIREWALL_DEBUG=on
      #
      # https://github.com/qdm12/gluetun/issues/2047
      #
      ### - PUBLICIP_API=ip2location
      #
      # healthcheck - https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/healthcheck.md
      #
      - HEALTH_TARGET_ADDRESS=1.1.1.1:443
      - HEALTH_VPN_DURATION_INITIAL=10s
      - HEALTH_VPN_DURATION_ADDITION=7s
      - HEALTH_SUCCESS_WAIT_DURATION=7s
      - HEALTH_SERVER_ADDRESS=0.0.0.0:9999
      #
      # providers - https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
      #
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      #
      # server list update - https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      #
      - UPDATER_PERIOD=3h
      #
      # http proxy - https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/http-proxy.md
      #
      - HTTPPROXY=on
      - HTTPPROXY_STEALTH=on
      #
      # DNS
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/dns.md
      #
      - DOT=off
      - DNS_KEEP_NAMESERVER=on

  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: always
    network_mode: "service:gluetun"

    volumes:
      # Optional to synchronize the log timestamp with host
      - /etc/localtime:/etc/localtime:ro
      # config file
      - ./blocky_config/config.yml:/app/config.yml
      - ./blocky_config/local.blocks.txt:/app/local.blocks.txt
      - ./blocky_config/local.allow.txt:/app/local.allow.txt

networks:
  gluetun_net:
    name: gluetun_net
    ipam:
      config:
        - subnet: 10.10.10.0/24
```

**Comment by qdm12** [comment] 2024-04-29 13:03
The problem is really just an OpenVPN problem:

```
No client-side authentication method is specified.  You must use either --cert/--key, --pkcs12, or --auth-user-pass
```

I just ran Mullvad+Openvpn successfully with the latest image, are you sure it's not a configuration error? The configuration you shared indicates `VPN_TYPE=wireguard` but the logs indicate it's running OpenVPN, so there is already a mismatch there 🤔

**Comment by qdm12** [comment] 2024-04-29 14:56
It was likely due to a large settings refactoring I've done starting with https://github.com/qdm12/gluetun/commit/ecc80a5a9e3f5ba8c3096eb47c9ed8544a7e8867 about a month ago. It should be all fixed up now given there is no directly related issue report about it for now. If it's working now, let's just move on and close this, since that was on the latest image and it's now fixed (this would different if it would be a tagged "more-stable" image such as `:v3.38`).

> I'm unsure how to match up current tags with commit https://github.com/qdm12/gluetun/commit/7b4befce61a56d945c3558188d79a856ba22880a.
> This has been an ongoing knowledge gap of mine that I'd like to address.

The git commit is injected as a docker build argument from the automated build system and is set in the Gluetun Go program at compilation time ([here](https://github.com/qdm12/gluetun/blob/bdc594c2977e775a71eace18278ca87cc7372a56/Dockerfile#L59)), and is also set as a the `org.opencontainers.image.revision` Docker image label ([here](https://github.com/qdm12/gluetun/blob/bdc594c2977e775a71eace18278ca87cc7372a56/Dockerfile#L70)).
Now you can filter your local Docker images with

```
docker images --filter "label=org.opencontainers.image.revision=7b4befce61a56d945c3558188d79a856ba22880a"
```

Note the revision has to be the full git commit hash digest, not just the first 7 characters.

Although I have no idea how to find that image on Gchr or docker hub once it's deleted locally, I would even say it's likely  impossible at this time. But it's still re-buildable too! For example:

```sh
docker build -t qmcgaw/gluetun https://github.com/qdm12/gluetun.git#7b4befce61a56d945c3558188d79a856ba22880a
```

**Closed by qdm12** 2024-04-29 14:56 UTC
Labels: Category: OpenVPN 🔐, Status: 🗯️ Waiting for feedback, Category: Config problem 📝, ☁️ Mullvad
