### ISSUE TITLE
Shadowsocks: support proxying shell commands

### ISSUE THREAD

**Issue by jamie-jp** [qdm12/gluetun#436] opened 2021-04-25 17:20 UTC
The thing is... the example from the Shadowsocks wiki shows exactly this example: https://github.com/shadowsocks/shadowsocks/wiki/Using-Shadowsocks-with-Command-Line-Tools

So I would expect it to work.

_Originally posted by @jamie403https://github.com/qdm12/gluetun/issues/245#issuecomment-695060724_

**Comment by qdm12** [comment] 2021-04-25 19:32
The implementation is completely custom (I wrote it) and does not respect the standard regarding Cli operation or file based config. It was designed to work as a Golang API (the language gluetun is written in) to run a Shadowsocks server only, so it likely lacks possible options for a standardized shadowsocks which can for example run as a client as well. If you need a particular option, please create another issue and I will add it as an environment variable (to keep it simple and fit with how gluetun is configured so far). Thanks for your understanding! Also feel free to comment if you feel there is a good reasons to support such behavior.

**Comment by qdm12** [comment] 2021-04-25 19:34
Never mind I understood the problem wrongly, sorry about that. I'll see what I can do!

**Comment by qdm12** [comment] 2021-04-25 19:36
Actually I think this is out of scope. You want to setup proxy chain on other machines connected to the shadowsocks server so on the client side. I don't think there is anything to do on the server side right?

**Comment by qdm12** [comment] 2021-05-28 15:27
@jamie-jp @jamie403 it works for me. Steps to reproduce:

1. Run gluetun, with shadowsocks listening on port `8388`
2. Launch a Shadowsocks client connected to Gluetun's Shadowsocks, with local port `1080`
3. Run for example `proxychains wget -qO- https://ipinfo.io` and it works

In my particular case, case 3 was a bit more convoluted because of my setup. I run a Windows host, so I ran the Shadowsocks-windows client connected to gluetun (on a linux server in my LAN). I then ran a Debian container with `docker run -it --rm debian:bullseye-slim` and ran the following commands:

```sh
apt-get update

# Find my host IP address on the Docker network
apt-get install -y dnsutils
nslookup host.docker.internal
# Gives me 192.168.65.2 for my host

# Install proxychains4
apt-get install -y proxychains4

# Write the config (largely taken from https://github.com/shadowsocks/shadowsocks/wiki/Using-Shadowsocks-with-Command-Line-Tools)
mkdir ~/.proxychains
cat <<EOT >> ~/.proxychains/proxychains.conf
strict_chain
proxy_dns
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0

[ProxyList]
socks5  192.168.65.2 1080
EOT

# Try the command finally
apt-get install -y wget
proxychains wget -qO- https://ipinfo.io
```

**Closed by qdm12** 2021-05-28 15:27 UTC
