### ISSUE TITLE
Bug: Windscribe Openvpn certificate verify failed

### ISSUE THREAD

**Issue by Kombustor** [qdm12/gluetun#972] opened 2022-04-30 12:11 UTC
### Is this urgent?

No

### Host OS

Debian Buster

### CPU arch

x86_64

### VPN service provider

Windscribe

### What are you using to run the container

Portainer

### What is the version of Gluetun

Running version latest built on 2022-04-28T13:51:27.619Z (commit b6de603)

### What's the problem 🤔

VPN doesn't connect due to certificate error, continuously restarts.

### Share your logs

```log
2022-04-30T14:07:22+02:00 INFO [routing] default route found: interface eth0, gateway 172.23.0.1 and assigned IP 172.23.0.3
2022-04-30T14:07:22+02:00 INFO [routing] local ethernet link found: eth0
2022-04-30T14:07:22+02:00 INFO [routing] local ipnet found: 172.23.0.0/16
2022-04-30T14:07:22+02:00 INFO [firewall] enabling...
2022-04-30T14:07:22+02:00 INFO [firewall] enabled successfully
2022-04-30T14:07:23+02:00 INFO [storage] merging by most recent 11416 hardcoded servers and 11416 servers read from /gluetun/servers.json
2022-04-30T14:07:23+02:00 INFO Alpine version: 3.15.4
2022-04-30T14:07:23+02:00 INFO OpenVPN 2.4 version: 2.4.12
2022-04-30T14:07:23+02:00 INFO OpenVPN 2.5 version: 2.5.6
2022-04-30T14:07:23+02:00 INFO Unbound version: 1.13.2
2022-04-30T14:07:23+02:00 INFO IPtables version: v1.8.7
2022-04-30T14:07:23+02:00 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: windscribe
|   |   └── Server selection settings:
|   |       ├── VPN type: openvpn
|   |       ├── Regions: austria
|   |       └── OpenVPN server selection settings:
|   |           └── Protocol: UDP
|   └── OpenVPN settings:
|       ├── OpenVPN version: 2.5
|       ├── User: [set]
|       ├── Password: [set]
|       ├── Tunnel IPv6: no
|       ├── Network interface: tun0
|       ├── Run OpenVPN as: root
|       └── Verbosity level: 1
├── DNS settings:
|   ├── DNS server address to use: 127.0.0.1
|   ├── Keep existing nameserver(s): no
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:7f00:1/104
|               ├── ::ffff:a00:0/104
|               ├── ::ffff:a9fe:0/112
|               ├── ::ffff:ac10:0/108
|               └── ::ffff:c0a8:0/112
├── Firewall settings:
|   └── Enabled: yes
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: Europe/Berlin
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2022-04-30T14:07:23+02:00 INFO [routing] default route found: interface eth0, gateway 172.23.0.1 and assigned IP 172.23.0.3
2022-04-30T14:07:23+02:00 INFO [routing] adding route for 0.0.0.0/0
2022-04-30T14:07:23+02:00 INFO [firewall] setting allowed subnets...
2022-04-30T14:07:23+02:00 INFO [routing] default route found: interface eth0, gateway 172.23.0.1 and assigned IP 172.23.0.3
2022-04-30T14:07:23+02:00 INFO [pprof] http server listening on [::]:6060
2022-04-30T14:07:23+02:00 INFO [http server] http server listening on [::]:8000
2022-04-30T14:07:23+02:00 INFO [healthcheck] listening on 127.0.0.1:9999
2022-04-30T14:07:23+02:00 INFO [dns over tls] using plaintext DNS at address 1.1.1.1
2022-04-30T14:07:23+02:00 INFO [firewall] allowing VPN connection...
2022-04-30T14:07:23+02:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Mar 24 2022
2022-04-30T14:07:23+02:00 INFO [openvpn] library versions: OpenSSL 1.1.1n  15 Mar 2022, LZO 2.10
2022-04-30T14:07:23+02:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]217.64.127.10:1194
2022-04-30T14:07:23+02:00 INFO [openvpn] UDP link local: (not bound)
2022-04-30T14:07:23+02:00 INFO [openvpn] UDP link remote: [AF_INET]217.64.127.10:1194
2022-04-30T14:07:23+02:00 INFO [openvpn] OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-30T14:07:23+02:00 INFO [openvpn] TLS_ERROR: BIO read tls_read_plaintext error
2022-04-30T14:07:23+02:00 INFO [openvpn] TLS Error: TLS object -> incoming plaintext read error
2022-04-30T14:07:23+02:00 INFO [openvpn] TLS Error: TLS handshake failed
2022-04-30T14:07:23+02:00 INFO [openvpn] SIGTERM received, sending exit notification to peer
2022-04-30T14:07:23+02:00 INFO [openvpn] SIGTERM[soft,tls-error] received, process exiting
2022-04-30T14:07:23+02:00 INFO [vpn] retrying in 15s
2022-04-30T14:07:29+02:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN
```

### Share your configuration

```yml
gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun # added this later (not in windscribe config wiki)
    restart: unless-stopped
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=openvpn # also tried wireguard unsuccessfully
      - OPENVPN_USER=...
      - OPENVPN_PASSWORD=...
      - TZ=Europe/Berlin
      - SERVER_REGIONS=Austria
```

**Comment by russwuss** [comment] 2022-04-30 12:57
Experiencing the same issue here too.

**Comment by russwuss** [comment] 2022-04-30 13:05
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2022-04-28T13:51:27.619Z (commit b6de603)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable VPNSP, please consider changing it to VPN_SERVICE_PROVIDER
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable REGION, please consider changing it to SERVER_REGIONS
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable PROTOCOL, please consider changing it to OPENVPN_PROTOCOL
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable WIREGUARD_ENDPOINT_PORT, please consider changing it to VPN_ENDPOINT_PORT
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable OPENVPN_INTERFACE, please consider changing it to VPN_INTERFACE
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable OPENVPN_ROOT, please consider changing it to OPENVPN_PROCESS_USER
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable WIREGUARD_INTERFACE, please consider changing it to VPN_INTERFACE
2022-04-30T14:04:35+01:00 WARN You are using the old environment variable SHADOWSOCKS_METHOD, please consider changing it to SHADOWSOCKS_CIPHER
2022-04-30T14:04:35+01:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.9
2022-04-30T14:04:35+01:00 INFO [routing] local ethernet link found: gretap0
2022-04-30T14:04:35+01:00 INFO [routing] local ethernet link found: erspan0
2022-04-30T14:04:35+01:00 INFO [routing] local ethernet link found: eth0
2022-04-30T14:04:35+01:00 INFO [routing] local ipnet found: 172.18.0.0/16
2022-04-30T14:04:35+01:00 INFO [firewall] enabling...
2022-04-30T14:04:35+01:00 INFO [firewall] enabled successfully
2022-04-30T14:04:35+01:00 INFO [storage] merging by most recent 11416 hardcoded servers and 11416 servers read from /gluetun/servers.json
2022-04-30T14:04:35+01:00 INFO Alpine version: 3.15.4
2022-04-30T14:04:35+01:00 INFO OpenVPN 2.4 version: 2.4.12
2022-04-30T14:04:35+01:00 INFO OpenVPN 2.5 version: 2.5.6
2022-04-30T14:04:35+01:00 INFO Unbound version: 1.13.2
2022-04-30T14:04:35+01:00 INFO IPtables version: v1.8.7
2022-04-30T14:04:35+01:00 INFO Settings summary:
├── VPN settings:
| ├── VPN provider settings:
| | ├── Name: windscribe
| | └── Server selection settings:
| | ├── VPN type: openvpn
| | ├── Regions: united kingdom
| | └── OpenVPN server selection settings:
| | └── Protocol: UDP
| └── OpenVPN settings:
| ├── OpenVPN version: 2.5
| ├── User: [set]
| ├── Password: [set]
| ├── Tunnel IPv6: no
| ├── Network interface: tun0
| ├── Run OpenVPN as: nonrootuser
| └── Verbosity level: 1
├── DNS settings:
| ├── DNS server address to use: 127.0.0.1
| ├── Keep existing nameserver(s): yes
| └── DNS over TLS settings:
| ├── Enabled: yes
| ├── Update period: every 24h0m0s
| ├── Unbound settings:
| | ├── Authoritative servers:
| | | └── quad9
| | ├── Caching: yes
| | ├── IPv6: no
| | ├── Verbosity level: 1
| | ├── Verbosity details level: 0
| | ├── Validation log level: 0
| | ├── System user: root
| | └── Allowed networks:
| | ├── 0.0.0.0/0
| | └── ::/0
| └── DNS filtering settings:
| ├── Block malicious: yes
| ├── Block ads: no
| ├── Block surveillance: no
| └── Blocked IP networks:
| ├── 127.0.0.1/8
| ├── 10.0.0.0/8
| ├── 172.16.0.0/12
| ├── 192.168.0.0/16
| ├── 169.254.0.0/16
| ├── ::1/128
| ├── fc00::/7
| ├── fe80::/10
| ├── ::ffff:7f00:1/104
| ├── ::ffff:a00:0/104
| ├── ::ffff:a9fe:0/112
| ├── ::ffff:ac10:0/108
| └── ::ffff:c0a8:0/112
├── Firewall settings:
| └── Enabled: yes
├── Log settings:
| └── Log level: INFO
├── Health settings:
| ├── Server listening address: 127.0.0.1:9999
| ├── Target address: cloudflare.com:443
| └── VPN wait durations:
| ├── Initial duration: 6s
| └── Additional duration: 5s
├── Shadowsocks server settings:
| └── Enabled: no
├── HTTP proxy settings:
| └── Enabled: no
├── Control server settings:
| ├── Listening address: :8000
| └── Logging: yes
├── OS Alpine settings:
| ├── Process UID: 1000
| ├── Process GID: 1000
| └── Timezone: Europe/London
├── Public IP settings:
| ├── Fetching: every 12h0m0s
| └── IP file path: /tmp/gluetun/ip
└── Version settings:
└── Enabled: yes
2022-04-30T14:04:35+01:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.9
2022-04-30T14:04:35+01:00 INFO [routing] adding route for 0.0.0.0/0
2022-04-30T14:04:35+01:00 INFO [firewall] setting allowed subnets...
2022-04-30T14:04:35+01:00 INFO [routing] default route found: interface eth0, gateway 172.18.0.1 and assigned IP 172.18.0.9
2022-04-30T14:04:35+01:00 INFO TUN device is not available: open /dev/net/tun: no such file or directory; creating it...
2022-04-30T14:04:35+01:00 INFO [pprof] http server listening on [::]:6060
2022-04-30T14:04:35+01:00 INFO [dns over tls] using plaintext DNS at address 9.9.9.9
2022-04-30T14:04:35+01:00 INFO [http server] http server listening on [::]:8000
2022-04-30T14:04:35+01:00 INFO [healthcheck] listening on 127.0.0.1:9999
2022-04-30T14:04:35+01:00 INFO [firewall] allowing VPN connection...
2022-04-30T14:04:35+01:00 INFO [openvpn] OpenVPN 2.5.6 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Mar 24 2022
2022-04-30T14:04:35+01:00 INFO [openvpn] library versions: OpenSSL 1.1.1n 15 Mar 2022, LZO 2.10
2022-04-30T14:04:35+01:00 INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]193.36.118.227:1194
2022-04-30T14:04:35+01:00 INFO [openvpn] UDP link local: (not bound)
2022-04-30T14:04:35+01:00 INFO [openvpn] UDP link remote: [AF_INET]193.36.118.227:1194
2022-04-30T14:04:35+01:00 INFO [openvpn] OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2022-04-30T14:04:35+01:00 INFO [openvpn] TLS_ERROR: BIO read tls_read_plaintext error
2022-04-30T14:04:35+01:00 INFO [openvpn] TLS Error: TLS object -> incoming plaintext read error
2022-04-30T14:04:35+01:00 INFO [openvpn] TLS Error: TLS handshake failed
2022-04-30T14:04:35+01:00 INFO [openvpn] SIGTERM received, sending exit notification to peer
2022-04-30T14:04:35+01:00 INFO [openvpn] SIGTERM[soft,tls-error] received, process exiting
panic: close of closed channel

goroutine 150 [running]:
github.com/qdm12/gluetun/internal/vpn.(*Loop).Run(0xc0010ea140, {0xd51718, 0xc0000de440}, 0xc0010e28a0)
github.com/qdm12/gluetun/internal/vpn/run.go:99 +0xcb9
created by main._main
./main.go:386 +0x2e85

**Comment by qdm12** [comment] 2022-04-30 15:34
Does `qmcgaw/gluetun:v3.28.2` work? Or maybe `qmcgaw/gluetun:v3.27.0`?

**Comment by russwuss** [comment] 2022-04-30 16:11
> Does `qmcgaw/gluetun:v3.28.2` work? Or maybe `qmcgaw/gluetun:v3.27.0`?

I did try docker tag 958 and had the same issue (sorry complete noob so can only give the tags I tried) I did not try the test tag. 
next one I tested was 943 which worked.

Can try the test one if you like?

**Comment by frepke** [comment] 2022-04-30 16:44
Problem here 2

**Comment by qdm12** [comment] 2022-04-30 18:53
> I did try docker tag 958 and had the same issue (sorry complete noob so can only give the tags I tried) I did not try the test tag.
> next one I tested was 943 which worked.

Tag `:958` is pretty much the latest image with some modified code for PIA, so it's expected to behave the same.

Tag `:pr-943` matches commit 5d66c193aa32aee3c499563bfce46576599cfc66 from 13 days ago. Since then changes are [the following](https://github.com/qdm12/gluetun/compare/5d66c193aa32aee3c499563bfce46576599cfc66...b6de6035f644402dae7fd2bfe12ab70edff132ce) and I don't really see anything that would affect certificate verification for Windscribe.

So to help me find which code change (commit) is causing this, can you please try building some commits and test if they work? To do so, you need `git` installed, and build it with

```
docker build -t qmcgaw/gluetun:972 "https://github.com/qdm12/gluetun.git#afa51b3ff6258114020565a1da2a22e67412c87a
```

This builds an image `qmcgaw/gluetun:972` using commit afa51b3ff6258114020565a1da2a22e67412c87a from Github. You can then run that image and check if it works or not. It takes about 30s to build, 10s for a rebuild with cache.

Now repeat this step for a few commits from [this list of commits](https://github.com/qdm12/gluetun/compare/5d66c193aa32aee3c499563bfce46576599cfc66...b6de6035f644402dae7fd2bfe12ab70edff132ce) to find from where it's not working anymore? You can start at the middle at commit 0c0f1663b1bc27bb4eb32073f3f762c9d2b84239 for example, and then work your way up in the list (earlier in time) or down (later in time).

As side notes:

- I would like to fix this ASAP to do a v3.29.0 release
- You can use Wireguard as an alternative which is rather well implemented in Gluetun for Windscribe

**Comment by ldekamps** [comment] 2022-05-04 18:58
Since I ran into the same issue I did some testing. Commit 0c0f1663b1bc27bb4eb32073f3f762c9d2b84239 seems to break stuff and starts returning the TLS error messages. 306d8494d6de07a611a41e4a49d61c618d44b8d0 is the last commit that works in combination with Windscribe. Hope this helps fixing the issue.

**Comment by russwuss** [comment] 2022-05-05 20:35
> > I did try docker tag 958 and had the same issue (sorry complete noob so can only give the tags I tried) I did not try the test tag.
> > next one I tested was 943 which worked.
> 
> Tag `:958` is pretty much the latest image with some modified code for PIA, so it's expected to behave the same.
> 
> Tag `:pr-943` matches commit [5d66c19](https://github.com/qdm12/gluetun/commit/5d66c193aa32aee3c499563bfce46576599cfc66) from 13 days ago. Since then changes are [the following](https://github.com/qdm12/gluetun/compare/5d66c193aa32aee3c499563bfce46576599cfc66...b6de6035f644402dae7fd2bfe12ab70edff132ce) and I don't really see anything that would affect certificate verification for Windscribe.
> 
> So to help me find which code change (commit) is causing this, can you please try building some commits and test if they work? To do so, you need `git` installed, and build it with
> 
> ```
> DOCKER_BUILDKIT=1 docker build -t qmcgaw/gluetun:972 "https://github.com/qdm12/gluetun.git#afa51b3ff6258114020565a1da2a22e67412c87a"
> ```
> 
> This builds an image `qmcgaw/gluetun:972` using commit [afa51b3](https://github.com/qdm12/gluetun/commit/afa51b3ff6258114020565a1da2a22e67412c87a) from Github. You can then run that image and check if it works or not. It takes about 30s to build, 10s for a rebuild with cache.
> 
> Now repeat this step for a few commits from [this list of commits](https://github.com/qdm12/gluetun/compare/5d66c193aa32aee3c499563bfce46576599cfc66...b6de6035f644402dae7fd2bfe12ab70edff132ce) to find from where it's not working anymore? You can start at the middle at commit [0c0f166](https://github.com/qdm12/gluetun/commit/0c0f1663b1bc27bb4eb32073f3f762c9d2b84239) for example, and then work your way up in the list (earlier in time) or down (later in time).
> 
> As side notes:
> 
> * I would like to fix this ASAP to do a v3.29.0 release
> * You can use Wireguard as an alternative which is rather well implemented in Gluetun for Windscribe

I have tried unfortunately for several nights and couldn’t get this to work. I tried changing the build number but it would build a new image every time, then couldn’t find that image in unraid. I’m really basic when it comes to things like this. Let me know if there are any other ways I can help. Thanks!

**Comment by qdm12** [comment] 2022-05-07 07:14
@ldekamps You pretty much nailed it down for me awesome!
It should be fixed by e32d251cc192dedc299e53b40808b76ce3b90bb1 in the latest image, let me know if it works for you.

**Comment by ldekamps** [comment] 2022-05-07 08:16
I can confirm that it works. I did a manual build with commit https://github.com/qdm12/gluetun/commit/e32d251cc192dedc299e53b40808b76ce3b90bb1 on my development environment and rolled out the `qmcgaw/gluetun:latest` on my production server. Both environments are happy again. Thanks for the fix!

**Comment by qdm12** [comment] 2022-05-07 09:59
Awesome :+1: Again thanks for debugging it, with all the recent refactoring pile, I got lost in my own code :smile: Closing this for now!

**Closed by qdm12** 2022-05-07 09:59 UTC

**Comment by russwuss** [comment] 2022-05-07 10:13
Thank you @ldekamps and @qdm12 for your hard work; massively appreciated - sorry I couldn't help.
